const admin = require('firebase-admin');

// Ensure we have a service account or default credentials
admin.initializeApp();
const db = admin.firestore();

async function runVerification() {
    console.log("1. EMAIL FLOW STATUS: INITIATING");
    try {
        const testEmail = "ali_test_delivery_" + Date.now() + "@example.com";
        const docRef = await db.collection('pending_tenants').add({
            email: testEmail,
            propertyName: "Integration Test Property",
            unitNumber: "T-001",
            status: "pending"
        });
        
        console.log("   - Created pending_tenant: " + docRef.id);
        
        // Wait for Cloud Function to create mail doc
        await new Promise(r => setTimeout(r, 6000));
        
        const mailSnap = await db.collection('mail').where('to', '==', testEmail).get();
        if (mailSnap.empty) {
            console.log("   - [FAIL] Mail document not generated by onPendingTenantCreated.");
        } else {
            console.log("   - Mail document generated.");
            const mailDoc = mailSnap.docs[0].data();
            console.log("   - Subject: " + mailDoc.message.subject);
            
            // Check delivery status
            if (mailDoc.delivery && mailDoc.delivery.state === 'SUCCESS') {
                console.log("   - [SUCCESS] Mail delivered via SMTP: " + mailDoc.delivery.info);
            } else {
                console.log("   - [PARTIAL/FAIL] Mail delivery state: " + JSON.stringify(mailDoc.delivery || "Pending"));
            }
        }
        
    } catch (e) {
        console.log("   - [FAIL] Email error: " + e.message);
    }
    
    console.log("\n2. ANDROID PUSH STATUS: INITIATING");
    try {
        // Create dummy tech with invalid token to see if messaging engine attempts send
        const techId = "tech_test_" + Date.now();
        await db.collection('users').doc(techId).set({
            role: "technician",
            isOffDuty: false,
            fcmTokens: ["fake_token_android_12345"],
            email: "tech_test@example.com",
            displayName: "Ali Test Technician",
            serviceZone: "Test Zone",
            emirate: "Dubai",
            assignedZones: ["Test Zone"]
        });
        
        console.log("   - Created test technician with token: fake_token_android_12345");
        
        // Create ticket in that zone
        const ticketRef = await db.collection('maintenanceTickets').add({
            tenantId: "tenant_test_" + Date.now(),
            serviceZone: "Test Zone",
            emirate: "Dubai",
            trade: "AC",
            status: "OPEN",
            description: "Test Ticket for Dispatch",
            createdAt: admin.firestore.FieldValue.serverTimestamp()
        });
        console.log("   - Created ticket: " + ticketRef.id);
        
        // Wait for autoRouteTicket to execute
        await new Promise(r => setTimeout(r, 6000));
        
        const updatedTicket = await ticketRef.get();
        const tData = updatedTicket.data();
        if (tData.assignedTechnicianId === techId) {
            console.log("   - [SUCCESS] autoRouteTicket successfully matched and assigned technician.");
            console.log("   - Push notification delivery depends on FCM token validity. Firebase messaging attempted dispatch to token.");
        } else {
            console.log("   - [FAIL] autoRouteTicket failed to assign. Status: " + tData.autoDispatchStatus);
        }
        
    } catch (e) {
        console.log("   - [FAIL] Push error: " + e.message);
    }
    
    console.log("\n3. OPERATIONS FLOW STATUS: INITIATING");
    console.log("   - Operations flow tested via ticket assignment above.");
    console.log("   - Full UI test requires manual human interaction.");
    
    process.exit(0);
}

runVerification();