const fs = require('fs');
const path = 'packages/shared/src/context/LanguageContext.tsx';

const content = `import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";

type Language = 'en' | 'ar';

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.onboarding': 'Onboarding',
        'nav.financial': 'Financials',
        'nav.tech': 'Technician',
        'nav.admin': 'BIN-Groups Admin',
        'nav.tenants': 'Tenants',
        'nav.technicians': 'Technician Corps',
        'nav.tickets': 'Mission Logs',
        'nav.financials': 'Treasury',
        'nav.audit': 'Institutional Audit',
        'nav.orphans': 'Orphan War Room',
        'nav.docs': 'Document Vault',
        'nav.brokers': 'Brokers',
        'nav.sos_feed': 'SOS Live Feed',
        'nav.audit_log': 'Systemic Audit Log',
        'nav.hr': 'HR Command',
        'fin.payroll': 'Payroll Hub',
        'audit.title': 'Institutional Audit Log',
        'nav.live_map': 'Live Map',
        'nav.sos_feed': 'SOS Feed',
        'nav.reports': 'Reports',
        'nav.logout': 'Logout',
        'nav.admin_user': 'Admin User',
        'nav.version_info': 'v1.0.0 | Go-Live: Jun 6, 2026',
        'nav.admin_panel_title': 'BIN-ADMINISTRY™ Command',
        'nav.sovereign_core': 'SOVEREIGN CORE',
        'nav.operations': 'OPERATIONS',
        'nav.support': 'Support',
        'nav.owner_portal_link': 'Owner Portal ↗',
        'nav.administry': 'ADMINISTRY',
        'landing.title': 'The Operating System for UAE Real Estate.',
        'landing.subtitle': 'BIN GROUP covers and maintains all kinds of properties, including Government Majlis, Government Properties, Hotels, residential, commercial, towers, villas, mixed-use, and institutional assets.',
        'landing.hero_title_line1': 'BINCONSTRUCTION™',
        'landing.hero_title_line2': 'SOVEREIGN MAINTENANCE',
        'landing.cta': 'Onboard Your Asset →',
        'landing.partner_login': 'PARTNER LOGIN',
        'landing.mission_overline': 'INSTITUTIONAL MISSION',
        'landing.mission_title': 'Institutional Mission',
        'landing.mission_desc': 'To establish the gold standard for property maintenance and construction in the UAE, ensuring every asset—from government councils to private estates—reflects the nation\\'s vision for institutional excellence.',
        'landing.about_overline': 'CORPORATE PROFILE',
        'landing.about_title': 'Premium Sovereignty',
        'landing.about_desc': 'As a sovereign-aligned entity, we specialize in the high-stakes maintenance of government assets, heritage sites, and elite residential portfolios, delivering uncompromising technical precision and institutional security.',
        'landing.contact_title': 'Institutional Correspondence',
        'landing.email': 'hq@bin-groups.com',
        'landing.phone': '+971 4 888 8888',
        'landing.address': 'Binconstruction HQ, Level 88, Sovereign Tower, Sheikh Zayed Road, Dubai, UAE',
        'landing.sectors_title': 'Sectors We Master',
        'landing.sector.govt_title': 'Government & Sovereign',
        'landing.sector.govt_desc': 'Institutional-grade maintenance for Majlis, Ministries, and Federal assets with specialized protocol readiness.',
        'landing.sector.luxury_title': 'Luxury Hospitality',
        'landing.sector.luxury_desc': 'Preserving the gold standard for UAE’s elite hotel portfolios and ultra-luxury private residences.',
        'landing.sector.infra_title': 'Critical Infrastructure',
        'landing.sector.infra_desc': 'Technical support for logistics nodes, district cooling systems, and high-stakes commercial centers.',
        'onboarding.title': 'Institutional Onboarding',
        'onboarding.description': 'BIN GROUP provides elite maintenance for all asset classes: Government Majlis, Government Properties, Hotels, Residential, Commercial, and Institutional nodes.',
        'onboarding.bulk_intake': 'Bulk Property Intake (1–500)',
        'onboarding.property_details': 'Property Details',
        'onboarding.analysis': 'Asset Analysis',
        'onboarding.quote': 'BIN-Groups Quote',
        'onboarding.payment': 'Activation',
        'step.intake': 'Property Intake',
        'step.analysis': 'Asset Analysis',
        'step.quote': 'BIN-Groups Quote',
        'step.tier': 'Contract Selection',
        'step.addons': 'Service Tailoring',
        'step.summary': 'Security Deposit',
        'step.account': 'Account Activation',
        'field.emirate': 'Emirate',
        'field.area': 'Area / Cluster',
        'field.type': 'Property Type',
        'field.subtype': 'Sub-Type',
        'field.usetype': 'Usage Type',
        'field.floors': 'Floors',
        'field.units': 'Units',
        'field.sqft': 'Square Footage',
        'field.age': 'Building Age',
        'field.lifts': 'Lifts',
        'field.pool': 'Pool',
        'field.tank': 'Water Tank',
        'field.sira': 'SIRA / CCTV',
        'field.fire': 'Fire Systems',
        'field.dist_cooling': 'District Cooling',
        'field.majlis': 'Government Majlis Protocol',
        'field.heritage': 'Heritage Sensitivity',
        'field.grade': 'Asset Grade',
        'field.status': 'Current Status',
        'btn.next': 'Next',
        'btn.back': 'Back',
        'btn.add_prop': 'Add Property (+)',
        'btn.bulk_csv': 'Upload CSV',
        'btn.exit': 'Exit',
        'btn.quote': 'GET INSTITUTIONAL QUOTE',
        'status.tender_ready': 'COMPLIANCE READY',
        'status.sovereign': 'BIN-GROUPS GRADE',
        'tech.tickets_mgt': 'Mission Logistics Hub',
        'tech.search_feed': 'Search Active Dispatches',
        'tech.status': 'Mission Status',
        'tech.priority': 'Priority Level',
        'tech.all_statuses': 'All Statuses',
        'tech.all_priorities': 'All Priorities',
        'tech.table.sovereign_id': 'Mission ID',
        'tech.table.asset': 'Property Node',
        'tech.table.unit': 'Unit',
        'tech.table.floor': 'Floor',
        'tech.table.discipline': 'Discipline',
        'tech.table.res_time': 'Resolution Time',
        'tech.table.tech': 'Assigned Specialist',
        'tech.no_incidents': 'No active incidents in this sector.',
        'tech.syncing': 'Syncing with Command Node...',
        'login.portal': 'PARTNER PORTAL',
        'login.auth_access': 'AUTHENTICATED INSTITUTIONAL ACCESS',
        'login.email': 'Access Email',
        'login.password': 'Secure Key (Password)',
        'login.signin': 'SECURE SIGN IN',
        'login.google': 'SIGN IN WITH GOOGLE',
        'login.or_sso': 'OR INSTITUTIONAL SSO',
        'login.iso_secure': 'ISO 27001 SECURE',
        'login.inst_grade': 'INSTITUTIONAL GRADE',
        'login.uae_ops': 'UAE PORTFOLIO OPS',
        'login.footer': '© 2026 BIN-GROUP UAE. UNAUTHORIZED ACCESS IS MONITORED.',
        'dash.title': 'Portfolio Intelligence',
        'dash.terminal': 'Terminal',
        'dash.locked_assets': 'Locked Assets',
        'dash.onboard_cta': '+ ONBOARD NEW ASSET',
        'dash.kpi.gross_val': 'GROSS CONTRACT VALUE',
        'dash.kpi.annual_yield': 'ANNUAL YIELD (EST)',
        'dash.kpi.radius': 'PORTFOLIO RADIUS',
        'dash.kpi.majlis_readiness': 'INSTITUTIONAL READINESS',
        'dash.kpi.net_roi': 'NET ROI',
        'dash.kpi.gross_roi': 'GROSS ROI',
        'dash.kpi.esg': 'SOVEREIGN ESG',
        'dash.kpi.compliance': 'COMPLIANCE SCORE',
        'dash.kpi.integrity': 'ASSET INTEGRITY',
        'dash.kpi.satisfaction': 'TENANT SATISFACTION',
        'dash.kpi.trend.live': 'LIVE',
        'dash.kpi.trend.active': 'ACTIVE',
        'dash.kpi.trend.optimal': 'OPTIMAL',
        'dash.ledger': 'ASSET LEDGER',
        'dash.asset_node': 'ASSET NODE',
        'dash.health_index': 'HEALTH INDEX',
        'dash.annual_amc': 'ANNUAL AMC',
        'dash.protocol_status': 'PROTOCOL STATUS',
        'dash.private_asset': 'Private Asset',
        'dash.alerts': 'SOVEREIGN ALERTS',
        'dash.intel.deck': 'SOVEREIGN INTELLIGENCE DECK',
        'dash.intel.forecast': 'AI FORECAST',
        'dash.intel.integrity_decay': 'INTEGRITY DECAY',
        'dash.intel.horizon': '12-MONTH HORIZON',
        'dash.intel.projected_yield': 'PROJECTED YIELD',
        'dash.intel.annualized_net': 'ANNUALIZED NET',
        'dash.intel.guidance_title': 'STRATEGIC MISSION GUIDANCE',
        'dash.intel.protocol_commands': 'SOVEREIGN PROTOCOL COMMANDS',
        'dash.intel.download_audit': 'DOWNLOAD INTEGRITY AUDIT (PDF)',
        'dash.intel.generating_audit': 'GENERATING SOVEREIGN AUDIT...',
        'dash.command_deck': 'SOVEREIGN ASSET COMMAND',
        'dash.command_subtitle': 'Institutional Grade Auditing & National Zone Interface',
        'dash.empty_title': 'PORTFOLIO OFFLINE',
        'dash.empty_subtitle': 'You have no active bin-group institutional service contracts. Begin your sovereign asset onboarding to unlock live monitoring.',
        'dash.empty_cta': '+ START ASSET ONBOARDING',
        'dash.mission_feed': 'MISSION FEED',
        'dash.listening': 'Listening for mission-critical protocol alerts...',
        'dash.hash_anchor': 'SOVEREIGN HASH ANCHOR',
        'dash.municipality_adapter': 'MUNICIPALITY ADAPTER',
        'dash.risk_grade': 'INSURER RISK GRADE',
        'dash.gateway_status': 'GATEWAY STATUS',
        'dash.audit_btn': 'GENERATE INSTITUTIONAL AUDIT',
        'dash.sync_btn': 'MANUAL SYNC',
        'dash.status.optimal': 'P.1 (OPTIMAL)',
        'dash.status.stable': 'P.2 (STABLE)',
        'sos.btn': 'TRIGGER SOS DISPATCH',
        'sos.title': 'SOS Dispatch',
        'sos.subtitle': 'Report critical infrastructure failures for immediate institutional restoration.',
        'sos.success_title': 'DISPATCH TRIGGERED',
        'sos.success_subtitle': 'Sovereign response team notified. A verified technician will arrive within **4 HOURS** (SLA Protocol Alpha).',
        'sos.emergency_protocol': 'EMERGENCY PROTOCOL',
        'sos.fault_category': 'FAULT CATEGORY',
        'sos.mission_description': 'MISSION DESCRIPTION',
        'sos.description_placeholder': 'Provide unit details and fault specifics...',
        'sos.attach_evidence': 'ATTACH VISUAL EVIDENCE',
        'sos.trigger_btn': 'TRIGGER DISPATCH',
        'sos.cat.ac': 'AC / HVAC CRITICAL FAILURE',
        'sos.cat.plumbing': 'MAJOR PLUMBING / FLOODING',
        'sos.cat.electrical': 'ELECTRICAL SHORT / BLACKOUT',
        'sos.cat.security': 'SECURITY / ACCESS BREACH',
        'sos.return_dash': 'RETURN TO DASHBOARD',
        'tech.service_node': 'Service Node',
        'tech.subtitle': 'Live maintenance grid and sovereign asset restoration.',
        'tech.mission_dispatch': 'MISSION DISPATCH',
        'tech.active_tickets': 'ACTIVE TICKETS',
        'tech.kpi.mttr': 'MTTR (AVG)',
        'tech.kpi.sla': 'SLA COMPLIANCE',
        'tech.kpi.uptime': 'ZONE UPTIME',
        'tech.trend.live': 'LIVE',
        'tech.trend.optimal': 'OPTIMAL',
        'tech.trend.sovereign': 'SOVEREIGN',
        'tech.trend.stable': 'STABLE',
        'tech.protocol': 'PROTOCOL ALPHA-4',
        'tech.priority.normal': 'NORMAL',
        'tech.priority.emergency': 'EMERGENCY',
        'tech.status_tracking': 'STATUS TRACKING',
        'tech.open_node': 'OPEN NODE',
        'tech.empty': 'No active mission dispatches in this sector.',
        'tech.unknown_unit': 'Unknown Unit',
        'tech.status.live': 'LIVE',
        'tech.status.syncing': 'SYNCING',
        'tech.live_ops': 'LIVE OPERATIONS',
        'tech.urgent_dispatch': 'URGENT DISPATCH',
        'tech.navigate': 'NAVIGATE',
        'tech.mission_brief': 'MISSION BRIEF',
        'tech.enable_alerts': 'ENABLE ALERTS',
        'tech.alerts_on': 'ALERTS ACTIVE',
        'footer.home': 'Home',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.support': 'Institutional Support',
        'footer.copyright': '© 2026 BINCONSTRUCTION™ UAE. ALL RIGHTS RESERVED.',
        'common.system': 'SYSTEM',
        'common.sys_init_fault': 'SYSTEM INITIALIZATION FAULT',
        'common.reload_sys': 'RELOAD SYSTEM',
        'status.owner': 'Owner',
        'common.asset': 'Asset',
        'status.pending': 'Pending',
        'onboarding.payment.verify_btn': 'Verify Payment',
    },
    ar: {
        'nav.dashboard': 'لوحة القيادة',
        'nav.onboarding': 'التسجيل',
        'nav.financial': 'المالية',
        'nav.tech': 'فني',
        'nav.admin': 'إدارة مجموعة بن',
        'nav.tenants': 'المستأجرون',
        'nav.technicians': 'فيلق الفنيين',
        'nav.tickets': 'سجلات المهام',
        'nav.financials': 'الخزينة',
        'nav.audit': 'التدقيق المؤسسي',
        'nav.orphans': 'غرفة عمليات الأيتام',
        'nav.docs': 'خزينة المستندات',
        'nav.brokers': 'الوسطاء',
        'nav.sos_feed': 'تغذية الاستغاثة المباشرة',
        'nav.audit_log': 'سجل التدقيق النظامي',
        'fin.payroll': 'مركز الرواتب',
        'audit.title': 'سجل التدقيق المؤسسي',
        'nav.settings': 'سياسة الخصوصية',
        'nav.live_map': 'الخريطة المباشرة',
        'nav.sos_feed': 'تغذية الاستغاثة',
        'nav.reports': 'التقارير',
        'nav.logout': 'تسجيل الخروج',
        'nav.admin_user': 'مستخدم مسؤول',
        'nav.version_info': 'v1.0.0 | تاريخ الإطلاق: 6 يونيو 2026',
        'nav.admin_panel_title': 'لوحة تحكم BIN-ADMINISTRY™',
        'nav.sovereign_core': 'النواة السيادية',
        'nav.operations': 'العمليات',
        'nav.support': 'الدعم',
        'nav.owner_portal_link': 'بوابة الملاك ↗',
        'nav.administry': 'الإدارة',
        'landing.title': 'نظام التشغيل للعقارات في الإمارات.',
        'landing.subtitle': 'تغطي مجموعة بن وتؤمن الصيانة لجميع أنواع العقارات، بما في ذلك المجالس الحكومية، العقارات الحكومية، الفنادق، السكني، التجاري، الأبراج، الفيلات، الأصول متعددة الاستخدامات والمؤسسية.',
        'landing.hero_title_line1': 'بن للإنشاءات™',
        'landing.hero_title_line2': 'صيانة مجموعة بن',
        'landing.cta': 'سجل أصولك الآن ←',
        'landing.partner_login': 'دخول الشركاء',
        'landing.mission_overline': 'المهمة المؤسسية',
        'landing.mission_title': 'المهمة المؤسسية',
        'landing.mission_desc': 'إرساء المعايير الذهبية لصيانة العقارات والإنشاءات في دولة الإمارات، لضمان أن كل أصل - من المجالس الحكومية إلى العقارات الخاصة - يعكس رؤية الدولة للتميز المؤسسي.',
        'landing.about_overline': 'ملف الشركة',
        'landing.about_title': 'سيادة متميزة',
        'landing.about_desc': 'بصفتنا كياناً متوافقاً مع المعايير السيادية، نحن متخصصون في الصيانة عالية الأهمية للأصول الحكومية والمواقع التراثية والمحافظ السكنية النخبوية، ونقدم دقة تقنية لا تضاهى وأمناً مؤسسياً.',
        'landing.contact_title': 'المراسلات المؤسسية',
        'landing.email': 'hq@bin-groups.com',
        'landing.phone': '+971 4 888 8888',
        'landing.address': 'المقر الرئيسي لبن للإنشاءات، طابق 88، برج سوفرين، شارع الشيخ زايد، دبي، الإمارات',
        'landing.sectors_title': 'القطاعات التي نتقنها',
        'landing.sector.govt_title': 'الحكومة والجهات السيادية',
        'landing.sector.govt_desc': 'صيانة بمستوى مؤسسي للمجالس والوزارات والأصول الاتحادية مع جاهزية متخصصة للبروتوكولات.',
        'landing.sector.luxury_title': 'الضيافة الفاخرة',
        'landing.sector.luxury_desc': 'الحفاظ على المعايير الذهبية لمحفظة الفنادق النخبة في الإمارات والإقامات الخاصة فائقة الفخامة.',
        'landing.sector.infra_title': 'البنية التحتية الحيوية',
        'landing.sector.infra_desc': 'الدعم الفني للعقد اللوجستية، وأنظمة تبريد المناطق، والمراكز التجارية عالية الأهمية.',
        'onboarding.title': 'التسجيل المؤسسي',
        'onboarding.description': 'توفر مجموعة بن صيانة متميزة لجميع فئات الأصول: المجالس الحكومية، العقارات الحكومية، الفنادق، السكني، التجاري، والمراكز المؤسسية.',
        'onboarding.bulk_intake': 'إدخال العقارات بالجملة (1–500)',
        'onboarding.property_details': 'تفاصيل العقار',
        'onboarding.analysis': 'تحليل الأصول',
        'onboarding.quote': 'تسعيرة مجموعة بن',
        'onboarding.payment': 'التفعيل',
        'step.intake': 'إدخال العقار',
        'step.analysis': 'تحليل الأصول',
        'step.quote': 'تسعيرة مجموعة بن',
        'step.tier': 'اختيار العقد',
        'step.addons': 'تخصيص الخدمات',
        'step.summary': 'مبلغ التأمين',
        'step.account': 'تفعيل الحساب',
        'field.emirate': 'الإمارة',
        'field.area': 'المنطقة / المجمع',
        'field.type': 'نوع العقار',
        'field.subtype': 'النوع الفرعي',
        'field.usetype': 'نوع الاستخدام',
        'field.floors': 'الأدوار',
        'field.units': 'الوحدات',
        'field.sqft': 'المساحة (قدم مربع)',
        'field.age': 'عمر المبنى',
        'field.lifts': 'المصاعد',
        'field.pool': 'المسبح',
        'field.tank': 'خزان المياه',
        'field.sira': 'سيرا / كاميرات المراقبة',
        'field.fire': 'أنظمة الحريق',
        'field.dist_cooling': 'تكييف المناطق',
        'field.majlis': 'بروتوكول المجالس الحكومية',
        'field.heritage': 'حساسية المواقع التراثية',
        'field.grade': 'فئة الأصول',
        'field.status': 'الحالة الحالية',
        'btn.next': 'التالي',
        'btn.back': 'السابق',
        'btn.add_prop': 'إضافة عقار (+)',
        'btn.bulk_csv': 'تحميل ملف CSV',
        'btn.exit': 'خروج',
        'btn.quote': 'احصل على تسعيرة مؤسسية',
        'status.tender_ready': 'جاهز للمناقصة',
        'status.sovereign': 'فئة مجموعة بن',
        'tech.tickets_mgt': 'مركز الخدمات اللوجستية',
        'tech.search_feed': 'البحث في البلاغات النشطة',
        'tech.status': 'حالة المهمة',
        'tech.priority': 'مستوى الأولوية',
        'tech.all_statuses': 'جميع الحالات',
        'tech.all_priorities': 'جميع الأولويات',
        'tech.table.sovereign_id': 'معرف المهمة',
        'tech.table.asset': 'العقار',
        'tech.table.unit': 'الوحدة',
        'tech.table.floor': 'الطابق',
        'tech.table.discipline': 'التخصص',
        'tech.table.res_time': 'وقت الحل',
        'tech.table.tech': 'الأخصائي المعين',
        'tech.no_incidents': 'لا توجد بلاغات نشطة في هذا القطاع.',
        'tech.syncing': 'جاري المزامنة مع عقدة التحكم...',
        'login.portal': 'بوابة الشركاء',
        'login.auth_access': 'دخول مؤسسي موثق',
        'login.email': 'البريد الإلكتروني للدخول',
        'login.password': 'المفتاح الآمن (كلمة المرور)',
        'login.signin': 'دخول آمن',
        'login.google': 'الدخول عبر جوجل',
        'login.or_sso': 'أو الدخول المؤسسي الموحد',
        'login.iso_secure': 'آمن بمعايير ISO 27001',
        'login.inst_grade': 'درجة مؤسسية',
        'login.uae_ops': 'عمليات محفظة الإمارات',
        'login.footer': '© 2026 مجموعة بن الإمارات. الدخول غير المصرح به مراقب.',
        'dash.title': 'ذكاء المحفظة',
        'dash.terminal': 'المحطة',
        'dash.locked_assets': 'الأصول المقفلة',
        'dash.onboard_cta': '+ تسجيل أصل جديد',
        'dash.kpi.gross_val': 'إجمالي قيمة العقد',
        'dash.kpi.annual_yield': 'العائد السنوي (تقديري)',
        'dash.kpi.radius': 'نطاق المحفظة',
        'dash.kpi.majlis_readiness': 'الجاهزية المؤسسية',
        'dash.kpi.net_roi': 'صافي العائد على الاستثمار',
        'dash.kpi.gross_roi': 'إجمالي العائد',
        'dash.kpi.esg': 'معايير ESG',
        'dash.kpi.compliance': 'درجة الامتثال',
        'dash.kpi.integrity': 'سلامة الأصول',
        'dash.kpi.satisfaction': 'رضا المستأجرين',
        'dash.kpi.trend.live': 'مباشر',
        'dash.kpi.trend.active': 'نشط',
        'dash.kpi.trend.optimal': 'مثالي',
        'dash.ledger': 'سجل الأصول',
        'dash.asset_node': 'عقدة الأصول',
        'dash.health_index': 'HEALTH INDEX',
        'dash.annual_amc': 'عقد الصيانة السنوي (AMC)',
        'dash.protocol_status': 'حالة البروتوكول',
        'dash.private_asset': 'أصل خاص',
        'dash.alerts': 'تنبيهات مجموعة بن',
        'dash.intel.deck': 'منصة ذكاء مجموعة بن',
        'dash.intel.forecast': 'توقعات الذكاء الاصطناعي',
        'dash.intel.integrity_decay': 'تآكل السلامة',
        'dash.intel.horizon': 'أفق 12 شهراً',
        'dash.intel.projected_yield': 'العائد المتوقع',
        'dash.intel.annualized_net': 'صافي سنوي',
        'dash.intel.guidance_title': 'توجيه المهمة الاستراتيجية',
        'dash.intel.protocol_commands': 'أوامر بروتوكول مجموعة بن',
        'dash.intel.download_audit': 'تحميل تدقيق السلامة (PDF)',
        'dash.intel.generating_audit': 'جاري إصدار تدقيق مجموعة بن...',
        'dash.command_deck': 'قيادة أصول مجموعة بن',
        'dash.command_subtitle': 'التدقيق المؤسسي وواجهة المنطقة الوطنية',
        'dash.empty_title': 'المحفظة غير متصلة',
        'dash.empty_subtitle': 'ليس لديك عقود خدمات مؤسسية نشطة مع مجموعة بن. ابدأ تسجيل أصولك لفتح المراقبة المباشرة.',
        'dash.empty_cta': '+ ابدأ تسجيل الأصول',
        'dash.mission_feed': 'تغذية المهام',
        'dash.listening': 'الاستماع لتنبيهات البروتوكول للمهمات الحرجة...',
        'dash.hash_anchor': 'رابط تشفير مجموعة بن',
        'dash.municipality_adapter': 'محول البلدية',
        'dash.risk_grade': 'فئة مخاطر التأمين',
        'dash.gateway_status': 'حالة البوابة',
        'dash.audit_btn': 'إصدار تدقيق مؤسسي',
        'dash.sync_btn': 'مزامنة مع البوابة الوطنية',
        'dash.status.optimal': 'أمثل (P.1)',
        'dash.status.stable': 'مستقر (P.2)',
        'sos.btn': 'تفعيل استغاثة SOS',
        'sos.title': 'إرسال استغاثة',
        'sos.subtitle': 'الإبلاغ عن أعطال البنية التحتية الحرجة للإصلاح المؤسسي الفوري.',
        'sos.success_title': 'تم تفعيل الإرسال',
        'sos.success_subtitle': 'تم إخطار فريق الاستجابة. سيصل فني معتمد خلال **4 ساعات** (بروتوكول ألفا).',
        'sos.emergency_protocol': 'بروتوكول الطوارئ',
        'sos.fault_category': 'فئة العطل',
        'sos.mission_description': 'وصف المهمة',
        'sos.description_placeholder': 'قدم تفاصيل الوحدة وتفاصيل العطل...',
        'sos.attach_evidence': 'إرفاق دليل مرئي',
        'sos.trigger_btn': 'تفعيل الإرسال',
        'sos.cat.ac': 'عطل حرج في التكييف',
        'sos.cat.plumbing': 'عطل سباكة رئيسي / فيضان',
        'sos.cat.electrical': 'ماس كهربائي / انقطاع تيار',
        'sos.cat.security': 'خرق أمني / دخول',
        'sos.return_dash': 'العودة للوحة القيادة',
        'tech.service_node': 'عقدة الخدمة',
        'tech.subtitle': 'شبكة الصيانة المباشرة وترميم أصول مجموعة بن.',
        'tech.mission_dispatch': 'إرسال المهمة',
        'tech.active_tickets': 'التذاكر النشطة',
        'tech.kpi.mttr': 'متوسط وقت الإصلاح',
        'tech.kpi.sla': 'الالتزام بـ SLA',
        'tech.kpi.uptime': 'جاهزية المنطقة',
        'tech.trend.live': 'مباشر',
        'tech.trend.optimal': 'مثالي',
        'tech.trend.sovereign': 'مجموعة بن',
        'tech.trend.stable': 'مستقر',
        'tech.protocol': 'بروتوكول ألفا-4',
        'tech.priority.normal': 'عادي',
        'tech.priority.emergency': 'طوارئ',
        'tech.status_tracking': 'تتبع الحالة',
        'tech.open_node': 'فتح العقدة',
        'tech.empty': 'لا توجد مهمات نشطة في هذا قطاع.',
        'tech.unknown_unit': 'وحدة غير معروفة',
        'tech.status.live': 'مباشر',
        'tech.status.syncing': 'جاري المزامنة',
        'tech.live_ops': 'العمليات المباشرة',
        'tech.urgent_dispatch': 'إرسال عاجل',
        'tech.navigate': 'توجيه',
        'tech.mission_brief': 'ملخص المهمة',
        'tech.enable_alerts': 'تفعيل التنبيهات',
        'tech.alerts_on': 'التنبيهات نشطة',
        'footer.home': 'الرئيسية',
        'footer.privacy': 'سياسة الخصوصية',
        'footer.terms': 'شروط الخدمة',
        'footer.support': 'الدعم المؤسسي',
        'footer.copyright': '© 2026 بن للإنشاءات™ الإمارات. جميع الحقوق محفوظة.',
        'common.system': 'النظام',
        'common.sys_init_fault': 'خطأ في تهيئة النظام',
        'common.reload_sys': 'إعادة تحميل النظام',
        'status.owner': 'مالك',
        'common.asset': 'أصل',
        'status.pending': 'قيد الانتظار',
        'onboarding.payment.verify_btn': 'التحقق من الدفع',
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [lang, setLang] = useState<Language>(() => {
        const saved = localStorage.getItem('app_lang');
        return (saved as Language) || 'en';
    });

    useEffect(() => {
        localStorage.setItem('app_lang', lang);
        document.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key: string, variables?: Record<string, any>) => {
        let text = translations[lang]?.[key] || translations['en']?.[key] || key;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(\`{\${k}}\`, String(v));
            });
        }
        return text;
    };

    const isRTL = lang === 'ar';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
            <div 
                dir={isRTL ? 'rtl' : 'ltr'}
                style={{ 
                    direction: isRTL ? 'rtl' : 'ltr', 
                    minHeight: '100vh',
                    fontFamily: "'Cairo', 'Inter', sans-serif",
                    backgroundColor: '#000',
                    color: '#fff'
                }}
            >
                {children}
            </div>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};\`;

fs.writeFileSync(path, content);
console.log('Fixed LanguageContext.tsx');
