import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import {
  checkCommitAndDigestInputs,
  checkDeploymentDocument,
  evaluateCollectedEvidence,
  checkLiveBilling,
  checkPilotCompletion,
} from '../../scripts/postdeploy-release-gate.mjs';
import { PRODUCTION, HARD_LAUNCH_CLAIM } from '../../scripts/lib/launch-honesty.mjs';

const COMMIT = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
const OTHER_COMMIT = 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb';
const DIGEST = 'd'.repeat(64);
const OTHER_DIGEST = 'e'.repeat(64);

function tempRoot() {
  return mkdtempSync(path.join(tmpdir(), 'postdeploy-gate-'));
}

function cleanRoot(root) {
  rmSync(root, { recursive: true, force: true });
}

function writeDeploymentDoc(root, overrides = {}) {
  mkdirSync(path.join(root, 'launch_package'), { recursive: true });
  const doc = {
    status: 'passed',
    projectId: PRODUCTION.projectId,
    mainUrl: PRODUCTION.mainUrl,
    adminUrl: PRODUCTION.adminUrl,
    deployedCommitSha: COMMIT,
    artifactDigest: DIGEST,
    deployedAt: new Date().toISOString(),
    workflowRunId: '12345',
    workflowRunAttempt: 1,
    workflowRef: 'refs/heads/main',
    repository: 'rashidpvt420-lang/bin-group-super-app',
    successfulComponents: ['hosting', 'firestoreRules', 'firestoreIndexes', 'storageRules', 'functions'],
    httpChecksOk: true,
    bundleVerified: true,
    hardLaunchClaim: HARD_LAUNCH_CLAIM,
    source: 'firebase-production-deploy-workflow',
    ...overrides,
  };
  writeFileSync(path.join(root, 'launch_package/production-deployment.json'), JSON.stringify(doc, null, 2));
  return doc;
}

function writeReadiness(root, gates) {
  mkdirSync(path.join(root, 'launch_package'), { recursive: true });
  writeFileSync(path.join(root, 'launch_package/hard-launch-readiness.json'), JSON.stringify({ hardLaunchGates: gates }, null, 2));
}

describe('checkCommitAndDigestInputs', () => {
  it('fails closed with no env', () => {
    const { failures, commitSha, digest } = checkCommitAndDigestInputs({});
    assert.ok(failures.length >= 2);
    assert.equal(commitSha, null);
    assert.equal(digest, null);
  });

  it('passes with a valid SHA and digest', () => {
    const { failures } = checkCommitAndDigestInputs({ GITHUB_SHA: COMMIT, VALIDATED_ARTIFACT_DIGEST: DIGEST });
    assert.deepEqual(failures, []);
  });
});

describe('checkDeploymentDocument', () => {
  it('fails when production-deployment.json is missing (not generated by workflow yet)', () => {
    const root = tempRoot();
    try {
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.ok(failures.some((f) => /is missing/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails when deployedCommitSha does not match GITHUB_SHA (wrong commit deployed)', () => {
    const root = tempRoot();
    try {
      writeDeploymentDoc(root, { deployedCommitSha: OTHER_COMMIT });
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.ok(failures.some((f) => /deployedCommitSha/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails when the deployed artifact digest does not match VALIDATED_ARTIFACT_DIGEST', () => {
    const root = tempRoot();
    try {
      writeDeploymentDoc(root, { artifactDigest: OTHER_DIGEST });
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.ok(failures.some((f) => /artifact digest/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails when the document lacks workflow provenance (hand-written, not workflow-generated)', () => {
    const root = tempRoot();
    try {
      writeDeploymentDoc(root, { workflowRunId: null, workflowRef: null, source: 'manually-edited' });
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.ok(failures.some((f) => /workflowRunId|workflowRef|generated by the production deploy workflow/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails when httpChecksOk or bundleVerified are not true', () => {
    const root = tempRoot();
    try {
      writeDeploymentDoc(root, { httpChecksOk: false });
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.ok(failures.some((f) => /httpChecksOk/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('passes a fully valid, commit/digest-bound, workflow-generated deployment document', () => {
    const root = tempRoot();
    try {
      writeDeploymentDoc(root);
      const failures = checkDeploymentDocument(root, COMMIT, DIGEST);
      assert.deepEqual(failures, []);
    } finally {
      cleanRoot(root);
    }
  });
});

describe('evaluateCollectedEvidence (failed business workflow / App Check 403 detection)', () => {
  it('fails when no evidence has been recorded at all (failed/skipped smoke)', () => {
    const root = tempRoot();
    try {
      const failures = evaluateCollectedEvidence(root, COMMIT);
      assert.ok(failures.some((f) => /Missing required evidence/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails when a recorded App Check token-fetch failure is present in an artifact', () => {
    const root = tempRoot();
    try {
      const artifactsDir = path.join(root, 'launch_package/artifacts');
      mkdirSync(artifactsDir, { recursive: true });
      writeFileSync(path.join(artifactsDir, 'business-technician-x.json'), JSON.stringify({ log: 'appCheck/fetch-status-error' }));
      const failures = evaluateCollectedEvidence(root, COMMIT);
      assert.ok(failures.some((f) => /App Check token-fetch failures/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });
});

describe('checkLiveBilling', () => {
  it('is advisory-only under LAUNCH_BANK_ONLY=1', () => {
    const root = tempRoot();
    try {
      const { failures, note } = checkLiveBilling(root, { LAUNCH_BANK_ONLY: '1' });
      assert.deepEqual(failures, []);
      assert.match(note, /deferred/);
    } finally {
      cleanRoot(root);
    }
  });

  it('fails closed for public launch when hard-launch-readiness.json is missing', () => {
    const root = tempRoot();
    try {
      const { failures } = checkLiveBilling(root, {});
      assert.ok(failures.some((f) => /is missing/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('fails for public launch when live_billing is not attested (Stripe not proven)', () => {
    const root = tempRoot();
    try {
      writeReadiness(root, [{ id: 'live_billing', status: 'external_verification_required' }]);
      const { failures } = checkLiveBilling(root, {});
      assert.ok(failures.some((f) => /live_billing gate is not attested/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });

  it('passes for public launch when live_billing is attested', () => {
    const root = tempRoot();
    try {
      writeReadiness(root, [{ id: 'live_billing', status: 'passed' }]);
      const { failures } = checkLiveBilling(root, {});
      assert.deepEqual(failures, []);
    } finally {
      cleanRoot(root);
    }
  });
});

describe('checkPilotCompletion', () => {
  it('does not block on an unattested pilot_no_p0_p1 (informational only, first-deploy expected)', () => {
    const root = tempRoot();
    try {
      writeReadiness(root, [{ id: 'pilot_no_p0_p1', status: 'external_verification_required' }]);
      const { failures, note } = checkPilotCompletion(root);
      assert.deepEqual(failures, []);
      assert.match(note, /not yet attested/);
    } finally {
      cleanRoot(root);
    }
  });

  it('fails closed when hard-launch-readiness.json is missing', () => {
    const root = tempRoot();
    try {
      const { failures } = checkPilotCompletion(root);
      assert.ok(failures.some((f) => /is missing/.test(f)));
    } finally {
      cleanRoot(root);
    }
  });
});
