import React, { useState } from 'react';
import { Paper, Stack, Box, Typography, Chip, Divider, IconButton, Tooltip, CircularProgress, alpha } from '@mui/material';
import { FileText, Download, Eye, Clock, Shield, AlertCircle } from 'lucide-react';
import { binThemeTokens } from '../theme/binGroupTheme';
import { jsPDF } from 'jspdf';
import { savePdfMobileSafe } from '../utils/bilingualContractPdf';

interface DocumentCenterCardProps {
    doc: any;
    themeColor?: string;
    onStatusChange?: (status: string) => void;
}

export const documentUrlOf = (doc: any) => doc?.downloadUrl || doc?.pdfUrl || doc?.fileUrl || doc?.documentUrl || doc?.signedPdfUrl || doc?.leasePdfUrl || doc?.invoicePdfUrl || doc?.receiptUrl || doc?.url || '';
export const documentNameOf = (doc: any) => String(doc?.title || doc?.name || doc?.fileName || doc?.type || 'BIN-GROUP-document').replace(/[^a-z0-9._-]/gi, '_');
export const dateOf = (doc: any) => doc?.date || doc?.createdAt?.toDate?.() || (doc?.createdAt?.seconds ? new Date(doc.createdAt.seconds * 1000) : null) || doc?.uploadedAt?.toDate?.() || (doc?.uploadedAt?.seconds ? new Date(doc.uploadedAt.seconds * 1000) : null) || new Date();

export default function DocumentCenterCard({ doc, themeColor = binThemeTokens.gold, onStatusChange }: DocumentCenterCardProps) {
    const [generating, setGenerating] = useState(false);
    const hasFile = Boolean(documentUrlOf(doc));

    const handleOpen = () => {
        const url = documentUrlOf(doc);
        if (url) {
            window.open(url, '_blank', 'noopener,noreferrer');
        } else {
            alert('This document file is not available yet. Please generate it or contact support.');
        }
    };

    const handleDownload = async () => {
        const url = documentUrlOf(doc);
        if (url) {
            try {
                const response = await fetch(url);
                if (!response.ok) throw new Error(`HTTP ${response.status}`);
                const blob = await response.blob();
                const objectUrl = window.URL.createObjectURL(blob);
                const anchor = document.createElement('a');
                anchor.href = objectUrl;
                anchor.download = documentNameOf(doc).endsWith('.pdf') ? documentNameOf(doc) : `${documentNameOf(doc)}.pdf`;
                document.body.appendChild(anchor);
                anchor.click();
                anchor.remove();
                window.URL.revokeObjectURL(objectUrl);
            } catch (error) {
                console.warn('[DocumentCenterCard] direct download failed, opening file instead:', error);
                handleOpen();
            }
        } else {
            // PDF Trigger Logic - Generate PDF locally if there is no URL
            try {
                setGenerating(true);
                const pdf = new jsPDF({ unit: 'mm', format: 'a4' });
                pdf.setFontSize(20);
                pdf.text(doc?.title || doc?.name || 'Generated Document', 20, 20);
                pdf.setFontSize(12);
                pdf.text(`Type: ${doc?.type || doc?.category || 'General'}`, 20, 30);
                pdf.text(`Date: ${new Date(dateOf(doc)).toLocaleDateString()}`, 20, 40);
                pdf.text(`ID: ${doc?.id || 'N/A'}`, 20, 50);
                
                if (doc?.description || doc?.content) {
                    pdf.text(`Details:`, 20, 70);
                    pdf.setFontSize(10);
                    pdf.text(doc?.description || doc?.content || '', 20, 80, { maxWidth: 170 });
                }
                
                pdf.setFontSize(8);
                pdf.setTextColor(150);
                pdf.text('Generated by BIN GROUP Secure Vault', 20, 280);

                const filename = documentNameOf(doc).endsWith('.pdf') ? documentNameOf(doc) : `${documentNameOf(doc)}.pdf`;
                try {
                    savePdfMobileSafe(pdf, filename);
                } catch (e) {
                    pdf.save(filename);
                }
            } catch (err) {
                console.error('[DocumentCenterCard] PDF generation failed:', err);
                alert('Failed to generate document PDF.');
            } finally {
                setGenerating(false);
            }
        }
    };

    return (
        <Paper sx={{ 
            p: 3, 
            bgcolor: 'rgba(15, 23, 42, 0.4)', 
            border: '1px solid rgba(255,255,255,0.05)', 
            borderRadius: 5,
            transition: 'all 0.2s ease',
            position: 'relative',
            '&:hover': { bgcolor: 'rgba(255,255,255,0.03)', borderColor: alpha(themeColor, 0.3) }
        }}>
            <Stack direction="row" spacing={2} sx={{ mb: 3 }}>
                <Box sx={{ width: 44, height: 44, bgcolor: alpha(themeColor, 0.1), borderRadius: 2, display: 'flex', alignItems: 'center', justifyContent: 'center', color: themeColor }}>
                    <FileText size={22} />
                </Box>
                <Box sx={{ flexGrow: 1, minWidth: 0 }}>
                    <Typography variant="subtitle2" fontWeight="950" noWrap sx={{ color: '#FFF' }}>
                        {doc.name || doc.title || 'Untitled Document'}
                    </Typography>
                    <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.4)', fontWeight: 700 }}>
                        {doc.category || doc.type || 'GENERAL'} · {hasFile ? (doc.size || doc.fileSize || 'PDF') : 'AUTO-GEN'}
                    </Typography>
                </Box>
            </Stack>

            <Stack direction="row" spacing={1} sx={{ mb: 3 }}>
                <Chip label={doc.type || 'DOCUMENT'} size="small" sx={{ bgcolor: 'rgba(255,255,255,0.05)', color: 'rgba(255,255,255,0.6)', fontWeight: 900, fontSize: '0.6rem' }} />
                <Chip 
                    label={hasFile ? 'READY' : 'GENERATABLE'} 
                    size="small" 
                    icon={hasFile ? <Shield size={10} /> : <AlertCircle size={10} />} 
                    sx={{ 
                        bgcolor: alpha(hasFile ? '#10b981' : themeColor, 0.1), 
                        color: hasFile ? '#10b981' : themeColor, 
                        fontWeight: 900, 
                        fontSize: '0.6rem' 
                    }} 
                />
            </Stack>

            <Divider sx={{ mb: 2, borderColor: 'rgba(255,255,255,0.05)' }} />

            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Stack direction="row" spacing={1} alignItems="center">
                    <Clock size={12} color="rgba(255,255,255,0.2)" />
                    <Typography variant="caption" sx={{ color: 'rgba(255,255,255,0.2)', fontWeight: 700 }}>
                        {new Date(dateOf(doc)).toLocaleDateString()}
                    </Typography>
                </Stack>
                <Box>
                    <Tooltip title="Preview">
                        <span>
                            <IconButton size="small" disabled={!hasFile} sx={{ color: 'rgba(255,255,255,0.4)' }} onClick={handleOpen}>
                                <Eye size={16} />
                            </IconButton>
                        </span>
                    </Tooltip>
                    <Tooltip title={hasFile ? "Download" : "Generate & Download"}>
                        <span>
                            <IconButton size="small" disabled={generating} sx={{ color: themeColor }} onClick={handleDownload}>
                                {generating ? <CircularProgress size={16} color="inherit" /> : <Download size={16} />}
                            </IconButton>
                        </span>
                    </Tooltip>
                </Box>
            </Box>
        </Paper>
    );
}
