import React, { useState } from 'react';
import { Button, CircularProgress } from '@mui/material';
import { FileText } from 'lucide-react';
import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { formatAED } from '../utils/formatters';
import { binThemeTokens } from '../theme/binGroupTheme';

interface OwnerReportGeneratorProps {
    user: any;
    properties: any[];
    contracts: any[];
    metrics: any;
    isRTL?: boolean;
}

const OwnerReportGenerator: React.FC<OwnerReportGeneratorProps> = ({ 
    user, 
    properties, 
    contracts, 
    metrics,
    isRTL 
}) => {
    const [loading, setLoading] = useState(false);

    const generatePDFReport = async () => {
        setLoading(true);
        try {
            const doc = new jsPDF();
            
            // Header
            doc.setFontSize(22);
            doc.setTextColor(198, 167, 94); // binThemeTokens.gold
            doc.text("BIN GROUP - ASSET PERFORMANCE REPORT", 105, 20, { align: "center" });
            
            doc.setFontSize(10);
            doc.setTextColor(100);
            doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 30);
            doc.text(`Owner ID: ${user?.uid}`, 20, 35);
            doc.text(`Owner Name: ${user?.displayName || 'N/A'}`, 20, 40);

            // 1. Portfolio Summary
            doc.setFontSize(16);
            doc.setTextColor(0);
            doc.text("1. PORTFOLIO SUMMARY", 20, 55);
            
            doc.setFontSize(12);
            doc.text(`Total Managed Assets: ${properties.length}`, 25, 65);
            doc.text(`Active Contracts: ${contracts.length}`, 25, 72);
            
            if (metrics) {
                doc.text(`Annual Gross Yield (Projected): AED ${formatAED(metrics.yield?.annualGrossYield || 0)}`, 25, 79);
                doc.text(`Compliance Score: ${metrics.compliance?.overallScore || 0}%`, 25, 86);
            }

            // 2. Asset Details Table
            doc.setFontSize(16);
            doc.text("2. ASSET INVENTORY & STATUS", 20, 105);
            
            const tableData = properties.map(p => [
                p.propertyName || p.address || 'Unnamed Asset',
                p.emirate || 'N/A',
                p.propertyType || 'Standard',
                `AED ${formatAED(p.annualAMC || 0)}`,
                'ACTIVE'
            ]);

            (doc as any).autoTable({
                startY: 115,
                head: [['Property / Area', 'Emirate', 'Type', 'Annual AMC', 'Status']],
                body: tableData,
                theme: 'grid',
                headStyles: { fillColor: [198, 167, 94], textColor: [0, 0, 0], fontStyle: 'bold' },
                alternateRowStyles: { fillColor: [245, 245, 245] }
            });

            // Footer
            const pageCount = (doc as any).internal.getNumberOfPages();
            for (let i = 1; i <= pageCount; i++) {
                doc.setPage(i);
                doc.setFontSize(8);
                doc.setTextColor(150);
                doc.text(
                    "This is an automated institutional report generated by BIN-GROUPS OS. Confidential.",
                    105, 285, { align: "center" }
                );
            }

            doc.save(`BIN_GROUP_Report_${new Date().toISOString().split('T')[0]}.pdf`);
        } catch (error) {
            console.error("Failed to generate PDF:", error);
            alert("Institutional Report Engine fault. Please retry or contact Executive Support.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <Button 
            variant="outlined" 
            size="large" 
            onClick={generatePDFReport}
            disabled={loading}
            startIcon={loading ? <CircularProgress size={16} color="inherit" /> : <FileText size={18} />}
            sx={{ 
                color: binThemeTokens.gold, 
                borderColor: binThemeTokens.gold, 
                borderRadius: 8, 
                fontWeight: 950, 
                px: 4, 
                py: 1.5,
                '&:hover': {
                    borderColor: binThemeTokens.gold,
                    bgcolor: 'rgba(198, 167, 94, 0.05)'
                }
            }}
        >
            {loading ? (isRTL ? 'جاري التحميل...' : 'GENERATING...') : (isRTL ? 'تحميل التقرير' : 'EXPORT PDF REPORT')}
        </Button>
    );
};

export default OwnerReportGenerator;
