// packages/shared/src/index.ts
export * from './utils/uaePricingEngine';
export * from './pricing/uaePricingMatrix2026';
export * from './pricing/calculateUaeQuote2026';
export * from './utils/buildingHealthEngine';
export * from './utils/predictiveIntelligence';
export * from './geo/geoAnchor';
export { default as RateLimiter } from './utils/RateLimiter';
export * from './theme/binGroupTheme';
export * from './components/SafeIcon';
export * from './components/SovereignAIChat';
export * from './context/AIContext';
export * from './lib/notificationService';
export * from './utils/DesignStudioPricingEngine';
export * from './context/LanguageContext';
export * from './context/AuthProvider';
export * from './components/LegalModal';
export * from './components/CeoContactButtons';
export * from './components/SovereignSupportChat';
export * from './components/SovereignAlertHandler';
export * from './utils/auditLogger';
export * from './lib/firebase';
