/**
 * Phase 12 canonical workflow/state-machine registry.
 *
 * Contract:
 * - Canonical states are the ONLY values permitted for new writes.
 * - Legacy aliases exist for reads/migrations only.
 * - Auxiliary fields such as verificationState/paymentStatus/inspectionStatus
 *   may describe gates or evidence but must not replace the canonical status.
 */

export const WORKFLOW_STATES = {
  PROPERTY: [
    'DRAFT',
    'UNDER_REVIEW',
    'CHANGES_REQUESTED',
    'PENDING_PROPERTY_INSPECTION',
    'READY_FOR_SITE_VISIT',
    'INSPECTION_IN_PROGRESS',
    'INSPECTION_COMPLETED',
    'QUOTE_READY',
    'CONTRACT_PENDING',
    'PAYMENT_PENDING',
    'APPROVED',
    'ACTIVE',
    'REJECTED',
    'SUSPENDED',
    'CANCELLED',
  ],
  TICKET: [
    'OPEN',
    'PENDING_ASSIGNMENT',
    'PENDING_SCHEDULING',
    'SCHEDULED',
    'ASSIGNED',
    'ACCEPTED',
    'EN_ROUTE',
    'ARRIVED',
    'IN_PROGRESS',
    'WAITING_PARTS',
    'COMPLETED_PENDING_APPROVAL',
    'COMPLETED',
    'TENANT_APPROVED',
    'CLOSED',
    'RESCHEDULE_REQUESTED',
    'CANCELLATION_REQUESTED',
    'CANCELLED',
    'ESCALATED',
    'REOPENED',
    'ON_HOLD',
    'DISPUTED',
    'REJECTED',
  ],
  INSPECTION: [
    'PENDING',
    'READY_FOR_SITE_VISIT',
    'ASSIGNED',
    'IN_PROGRESS',
    'EVIDENCE_RECORDED',
    'COMPLETED',
    'OWNER_REVIEW',
    'APPROVED',
    'REINSPECTION_REQUESTED',
    'REJECTED',
    'CANCELLED',
  ],
  PAYMENT: [
    'PENDING',
    'APPROVED',
    'REJECTED',
    'FAILED',
    'CANCELLED',
    'REFUND_PENDING',
    'REFUNDED',
  ],
  QUOTE: [
    'DRAFT',
    'READY',
    'PRESENTED',
    'ACCEPTED',
    'ENGINEER_REVIEW',
    'REJECTED',
    'EXPIRED',
    'SUPERSEDED',
  ],
  CONTRACT: [
    'DRAFT',
    'PENDING_OWNER_SIGNATURE',
    'SIGNED',
    'PENDING_PAYMENT',
    'ACTIVE',
    'SUSPENDED',
    'CANCELLED',
    'EXPIRED',
    'TERMINATED',
  ],
  TENANT_LINK: [
    'PENDING_ADMIN_REVIEW',
    'APPROVED',
    'REJECTED',
    'CANCELLED',
  ],
  BROKER_KYC: [
    'NOT_SUBMITTED',
    'PENDING_REVIEW',
    'CHANGES_REQUESTED',
    'APPROVED',
    'REJECTED',
    'EXPIRED',
    'SUSPENDED',
  ],
  TECHNICIAN_JOB: [
    'PENDING_ASSIGNMENT',
    'ASSIGNED',
    'ACCEPTED',
    'EN_ROUTE',
    'ARRIVED',
    'IN_PROGRESS',
    'WAITING_PARTS',
    'EVIDENCE_RECORDED',
    'COMPLETED',
    'CANCELLED',
  ],
  ONBOARDING: [
    'DRAFT',
    'ACCOUNT_CREATED',
    'PROPERTY_DETAILS_COMPLETE',
    'DOCUMENTS_PENDING',
    'UNDER_REVIEW',
    'CHANGES_REQUESTED',
    'INSPECTION_REQUIRED',
    'INSPECTION_IN_PROGRESS',
    'QUOTE_READY',
    'CONTRACT_SELECTED',
    'SIGNATURE_PENDING',
    'PAYMENT_PENDING',
    'PAYMENT_PROCESSING',
    'PAYMENT_CONFIRMED',
    'APPROVED',
    'ACTIVE',
    'REJECTED',
    'EXPIRED',
    'SUSPENDED',
  ],
} as const;

export type WorkflowDomain = keyof typeof WORKFLOW_STATES;
export type CanonicalWorkflowState = (typeof WORKFLOW_STATES)[WorkflowDomain][number];

const ALIASES: Record<WorkflowDomain, Readonly<Record<string, CanonicalWorkflowState>>> = {
  PROPERTY: {
    PENDING: 'UNDER_REVIEW',
    PENDING_APPROVAL: 'UNDER_REVIEW',
    PENDING_REVIEW: 'UNDER_REVIEW',
    PENDING_ADMIN_APPROVAL: 'UNDER_REVIEW',
    PENDING_ADMIN_REVIEW: 'UNDER_REVIEW',
    ONBOARDING: 'UNDER_REVIEW',
    SUBMITTED: 'UNDER_REVIEW',
    ADMIN_REVIEW: 'UNDER_REVIEW',
    SUBMITTED_FOR_PROPERTY_INSPECTION: 'PENDING_PROPERTY_INSPECTION',
    AWAITING_SITE_INSPECTION: 'PENDING_PROPERTY_INSPECTION',
    PENDING_ADMIN_SITE_VISIT: 'PENDING_PROPERTY_INSPECTION',
    READY_FOR_SITE_VISITS: 'READY_FOR_SITE_VISIT',
    FINAL_QUOTE_VERIFIED_AWAITING_15_PERCENT_PAYMENT: 'PAYMENT_PENDING',
    AWAITING_15_PERCENT_PAYMENT: 'PAYMENT_PENDING',
    AWAITING_ACTIVATION_PAYMENT: 'PAYMENT_PENDING',
    PENDING_ADMIN_PAYMENT_VERIFICATION: 'PAYMENT_PENDING',
    READY_FOR_ACTIVATION: 'APPROVED',
    ACTIVATED: 'ACTIVE',
    LIVE: 'ACTIVE',
    DENIED: 'REJECTED',
    CANCELED: 'CANCELLED',
  },
  TICKET: {
    NEW: 'OPEN',
    PENDING: 'OPEN',
    UNASSIGNED: 'OPEN',
    AUTO_ASSIGNED: 'ASSIGNED',
    DISPATCHED: 'ASSIGNED',
    TECHNICIAN_ASSIGNED: 'ASSIGNED',
    CLAIMED: 'ACCEPTED',
    ON_THE_WAY: 'EN_ROUTE',
    LIVE_TRACKING: 'EN_ROUTE',
    WORK_STARTED: 'IN_PROGRESS',
    STARTED: 'IN_PROGRESS',
    RESOLVED: 'CLOSED',
    DONE: 'CLOSED',
    QUOTE_REJECTED: 'ON_HOLD',
    CANCELED: 'CANCELLED',
  },
  INSPECTION: {
    PENDING_ADMIN_SITE_VISIT: 'PENDING',
    READY_FOR_SITE_VISITS: 'READY_FOR_SITE_VISIT',
    EVIDENCE_RECORDED_PENDING_COMPLETION: 'EVIDENCE_RECORDED',
    INSPECTION_EVIDENCE_RECORDED: 'EVIDENCE_RECORDED',
    SUBMITTED: 'OWNER_REVIEW',
    VERIFIED: 'APPROVED',
    CANCELED: 'CANCELLED',
  },
  PAYMENT: {
    PENDING_ADMIN_PAYMENT_VERIFICATION: 'PENDING',
    PENDING_ADMIN_APPROVAL: 'PENDING',
    PENDING_VERIFICATION: 'PENDING',
    PAYMENT_PENDING: 'PENDING',
    PAYMENT_SUBMITTED: 'PENDING',
    ADMIN_VERIFIED: 'APPROVED',
    VERIFIED: 'APPROVED',
    PAID: 'APPROVED',
    SETTLED: 'APPROVED',
    RECONCILED: 'APPROVED',
    DENIED: 'REJECTED',
    CANCELED: 'CANCELLED',
  },
  QUOTE: {
    QUOTE_READY: 'READY',
    OWNER_REVIEW: 'PRESENTED',
    OWNER_APPROVED_OWNER_TO_PAY: 'ACCEPTED',
    OWNER_APPROVED_TENANT_TO_PAY: 'ACCEPTED',
    DEPOSIT_PENDING: 'ACCEPTED',
    PAYMENT_PENDING: 'ACCEPTED',
    PAID: 'ACCEPTED',
    OWNER_REJECTED: 'REJECTED',
  },
  CONTRACT: {
    AWAITING_OWNER_SIGNATURE: 'PENDING_OWNER_SIGNATURE',
    APPROVED_AWAITING_OWNER_SIGNATURE: 'PENDING_OWNER_SIGNATURE',
    APPROVED_PENDING_OWNER_SIGNATURE: 'PENDING_OWNER_SIGNATURE',
    OWNER_SIGNED: 'SIGNED',
    SIGNED_PENDING_PROPERTY_INSPECTION: 'SIGNED',
    READY_FOR_ACTIVATION: 'PENDING_PAYMENT',
    SIGNED_AWAITING_15_PERCENT_PAYMENT: 'PENDING_PAYMENT',
    PENDING_ADMIN_PAYMENT_VERIFICATION: 'PENDING_PAYMENT',
    PAYMENT_REJECTED: 'PENDING_PAYMENT',
    ACTIVATED: 'ACTIVE',
    LIVE: 'ACTIVE',
    CANCELED: 'CANCELLED',
  },
  TENANT_LINK: {
    PENDING: 'PENDING_ADMIN_REVIEW',
    PENDING_REVIEW: 'PENDING_ADMIN_REVIEW',
    ADMIN_REVIEW: 'PENDING_ADMIN_REVIEW',
    DENIED: 'REJECTED',
    CANCELED: 'CANCELLED',
  },
  BROKER_KYC: {
    PENDING: 'PENDING_REVIEW',
    UNDER_REVIEW: 'PENDING_REVIEW',
    VERIFIED: 'APPROVED',
    DENIED: 'REJECTED',
  },
  TECHNICIAN_JOB: {
    AUTO_ASSIGNED: 'ASSIGNED',
    DISPATCHED: 'ASSIGNED',
    ON_THE_WAY: 'EN_ROUTE',
    WORK_STARTED: 'IN_PROGRESS',
    INSPECTION_EVIDENCE_RECORDED: 'EVIDENCE_RECORDED',
    CANCELED: 'CANCELLED',
  },
  ONBOARDING: {
    PENDING: 'DRAFT',
    AUTH_CREATED: 'ACCOUNT_CREATED',
    OWNER_ACCOUNT_CREATED: 'ACCOUNT_CREATED',
    ADMIN_REVIEW: 'UNDER_REVIEW',
    PENDING_ADMIN_REVIEW: 'UNDER_REVIEW',
    PENDING_ADMIN_APPROVAL: 'UNDER_REVIEW',
    PAYMENT_VERIFIED_PENDING_ADMIN_APPROVAL: 'UNDER_REVIEW',
    PENDING_PROPERTY_INSPECTION: 'INSPECTION_REQUIRED',
    SUBMITTED_FOR_PROPERTY_INSPECTION: 'INSPECTION_REQUIRED',
    AWAITING_SITE_INSPECTION: 'INSPECTION_REQUIRED',
    READY_FOR_SITE_VISIT: 'INSPECTION_REQUIRED',
    READY_FOR_SITE_VISITS: 'INSPECTION_REQUIRED',
    INSPECTION_COMPLETED: 'QUOTE_READY',
    DEPOSIT_PENDING: 'PAYMENT_PENDING',
    AWAITING_PAYMENT: 'PAYMENT_PENDING',
    AWAITING_15_PERCENT_PAYMENT: 'PAYMENT_PENDING',
    AWAITING_ACTIVATION_PAYMENT: 'PAYMENT_PENDING',
    DEPOSIT_PROCESSING: 'PAYMENT_PROCESSING',
    PAYMENT_PENDING_APPROVAL: 'PAYMENT_PROCESSING',
    PENDING_ADMIN_PAYMENT_VERIFICATION: 'PAYMENT_PROCESSING',
    PENDING_PAYMENT_VERIFICATION: 'PAYMENT_PROCESSING',
    PAYMENT_SUBMITTED: 'PAYMENT_PROCESSING',
    PAYMENT_PROCESSING: 'PAYMENT_PROCESSING',
    DEPOSIT_PAID: 'PAYMENT_CONFIRMED',
    PAID: 'PAYMENT_CONFIRMED',
    PAYMENT_VERIFIED: 'PAYMENT_CONFIRMED',
    IDENTITY_PENDING: 'SIGNATURE_PENDING',
    AWAITING_SIGNATURE: 'SIGNATURE_PENDING',
    APPROVED_AWAITING_OWNER_SIGNATURE: 'SIGNATURE_PENDING',
    APPROVED_PENDING_OWNER_SIGNATURE: 'SIGNATURE_PENDING',
    READY_FOR_ACTIVATION: 'APPROVED',
    APPROVED_AWAITING_ACTIVATION: 'APPROVED',
    ACTIVATED: 'ACTIVE',
    LIVE: 'ACTIVE',
    DENIED: 'REJECTED',
    CANCELLED: 'EXPIRED',
    CANCELED: 'EXPIRED',
  },
};

const TRANSITIONS: Record<WorkflowDomain, Readonly<Record<string, readonly string[]>>> = {
  PROPERTY: {
    DRAFT: ['UNDER_REVIEW', 'CANCELLED'],
    UNDER_REVIEW: ['CHANGES_REQUESTED', 'PENDING_PROPERTY_INSPECTION', 'REJECTED', 'SUSPENDED'],
    CHANGES_REQUESTED: ['UNDER_REVIEW', 'CANCELLED'],
    PENDING_PROPERTY_INSPECTION: ['READY_FOR_SITE_VISIT', 'CHANGES_REQUESTED', 'REJECTED', 'SUSPENDED'],
    READY_FOR_SITE_VISIT: ['INSPECTION_IN_PROGRESS', 'CHANGES_REQUESTED', 'CANCELLED'],
    INSPECTION_IN_PROGRESS: ['INSPECTION_COMPLETED', 'CHANGES_REQUESTED', 'CANCELLED'],
    INSPECTION_COMPLETED: ['QUOTE_READY', 'CHANGES_REQUESTED', 'REJECTED'],
    QUOTE_READY: ['CONTRACT_PENDING', 'CHANGES_REQUESTED', 'REJECTED'],
    CONTRACT_PENDING: ['PAYMENT_PENDING', 'CHANGES_REQUESTED', 'CANCELLED'],
    PAYMENT_PENDING: ['APPROVED', 'CHANGES_REQUESTED', 'CANCELLED'],
    APPROVED: ['ACTIVE', 'SUSPENDED'],
    ACTIVE: ['SUSPENDED', 'CANCELLED'],
    REJECTED: ['DRAFT'],
    SUSPENDED: ['UNDER_REVIEW', 'ACTIVE', 'CANCELLED'],
    CANCELLED: [],
  },
  TICKET: {
    OPEN: ['PENDING_ASSIGNMENT', 'PENDING_SCHEDULING', 'SCHEDULED', 'ASSIGNED', 'CANCELLED', 'ESCALATED'],
    PENDING_ASSIGNMENT: ['ASSIGNED', 'SCHEDULED', 'CANCELLED', 'ESCALATED'],
    PENDING_SCHEDULING: ['SCHEDULED', 'ASSIGNED', 'CANCELLED'],
    SCHEDULED: ['ASSIGNED', 'RESCHEDULE_REQUESTED', 'CANCELLATION_REQUESTED', 'CANCELLED'],
    ASSIGNED: ['ACCEPTED', 'EN_ROUTE', 'CANCELLED', 'ESCALATED'],
    ACCEPTED: ['EN_ROUTE', 'ARRIVED', 'CANCELLED', 'ESCALATED'],
    EN_ROUTE: ['ARRIVED', 'CANCELLED', 'ESCALATED'],
    ARRIVED: ['IN_PROGRESS', 'CANCELLED', 'ESCALATED'],
    IN_PROGRESS: ['WAITING_PARTS', 'COMPLETED_PENDING_APPROVAL', 'COMPLETED', 'ON_HOLD', 'ESCALATED'],
    WAITING_PARTS: ['IN_PROGRESS', 'ON_HOLD', 'CANCELLED'],
    COMPLETED_PENDING_APPROVAL: ['COMPLETED', 'DISPUTED', 'REOPENED'],
    COMPLETED: ['TENANT_APPROVED', 'CLOSED', 'DISPUTED', 'REOPENED'],
    TENANT_APPROVED: ['CLOSED', 'REOPENED'],
    RESCHEDULE_REQUESTED: ['SCHEDULED', 'CANCELLED'],
    CANCELLATION_REQUESTED: ['CANCELLED', 'SCHEDULED'],
    ESCALATED: ['ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'CANCELLED'],
    REOPENED: ['OPEN', 'ASSIGNED', 'IN_PROGRESS'],
    ON_HOLD: ['OPEN', 'ASSIGNED', 'IN_PROGRESS', 'CANCELLED'],
    DISPUTED: ['REOPENED', 'CLOSED'],
    REJECTED: ['OPEN', 'CLOSED'],
    CLOSED: [],
    CANCELLED: [],
  },
  INSPECTION: {
    PENDING: ['READY_FOR_SITE_VISIT', 'ASSIGNED', 'CANCELLED'],
    READY_FOR_SITE_VISIT: ['ASSIGNED', 'IN_PROGRESS', 'CANCELLED'],
    ASSIGNED: ['IN_PROGRESS', 'CANCELLED'],
    IN_PROGRESS: ['EVIDENCE_RECORDED', 'COMPLETED', 'CANCELLED'],
    EVIDENCE_RECORDED: ['COMPLETED', 'REINSPECTION_REQUESTED', 'REJECTED'],
    COMPLETED: ['OWNER_REVIEW', 'APPROVED', 'REINSPECTION_REQUESTED'],
    OWNER_REVIEW: ['APPROVED', 'REINSPECTION_REQUESTED', 'REJECTED'],
    REINSPECTION_REQUESTED: ['READY_FOR_SITE_VISIT', 'ASSIGNED', 'CANCELLED'],
    APPROVED: [],
    REJECTED: ['REINSPECTION_REQUESTED'],
    CANCELLED: [],
  },
  PAYMENT: {
    PENDING: ['APPROVED', 'REJECTED', 'FAILED', 'CANCELLED'],
    APPROVED: ['REFUND_PENDING'],
    REJECTED: ['PENDING', 'CANCELLED'],
    FAILED: ['PENDING', 'CANCELLED'],
    REFUND_PENDING: ['REFUNDED', 'APPROVED'],
    REFUNDED: [],
    CANCELLED: [],
  },
  QUOTE: {
    DRAFT: ['READY', 'REJECTED', 'EXPIRED'],
    READY: ['PRESENTED', 'SUPERSEDED', 'EXPIRED'],
    PRESENTED: ['ACCEPTED', 'REJECTED', 'SUPERSEDED', 'EXPIRED'],
    ACCEPTED: ['ENGINEER_REVIEW', 'SUPERSEDED'],
    ENGINEER_REVIEW: ['ACCEPTED', 'REJECTED', 'SUPERSEDED'],
    REJECTED: ['DRAFT'],
    EXPIRED: ['DRAFT'],
    SUPERSEDED: [],
  },
  CONTRACT: {
    DRAFT: ['PENDING_OWNER_SIGNATURE', 'CANCELLED'],
    PENDING_OWNER_SIGNATURE: ['SIGNED', 'CANCELLED', 'EXPIRED'],
    SIGNED: ['PENDING_PAYMENT', 'ACTIVE', 'CANCELLED', 'EXPIRED'],
    PENDING_PAYMENT: ['ACTIVE', 'CANCELLED', 'EXPIRED'],
    ACTIVE: ['SUSPENDED', 'CANCELLED', 'TERMINATED', 'EXPIRED'],
    SUSPENDED: ['ACTIVE', 'TERMINATED', 'CANCELLED'],
    CANCELLED: [],
    EXPIRED: [],
    TERMINATED: [],
  },
  TENANT_LINK: {
    PENDING_ADMIN_REVIEW: ['APPROVED', 'REJECTED', 'CANCELLED'],
    APPROVED: [],
    REJECTED: ['PENDING_ADMIN_REVIEW'],
    CANCELLED: [],
  },
  BROKER_KYC: {
    NOT_SUBMITTED: ['PENDING_REVIEW'],
    PENDING_REVIEW: ['CHANGES_REQUESTED', 'APPROVED', 'REJECTED', 'EXPIRED'],
    CHANGES_REQUESTED: ['PENDING_REVIEW', 'REJECTED', 'EXPIRED'],
    APPROVED: ['PENDING_REVIEW', 'SUSPENDED', 'EXPIRED'],
    REJECTED: ['PENDING_REVIEW'],
    EXPIRED: ['PENDING_REVIEW'],
    SUSPENDED: ['PENDING_REVIEW', 'APPROVED'],
  },
  TECHNICIAN_JOB: {
    PENDING_ASSIGNMENT: ['ASSIGNED', 'CANCELLED'],
    ASSIGNED: ['ACCEPTED', 'EN_ROUTE', 'CANCELLED'],
    ACCEPTED: ['EN_ROUTE', 'ARRIVED', 'CANCELLED'],
    EN_ROUTE: ['ARRIVED', 'CANCELLED'],
    ARRIVED: ['IN_PROGRESS', 'CANCELLED'],
    IN_PROGRESS: ['WAITING_PARTS', 'EVIDENCE_RECORDED', 'COMPLETED', 'CANCELLED'],
    WAITING_PARTS: ['IN_PROGRESS', 'CANCELLED'],
    EVIDENCE_RECORDED: ['COMPLETED', 'IN_PROGRESS'],
    COMPLETED: [],
    CANCELLED: [],
  },
  ONBOARDING: {
    DRAFT: ['ACCOUNT_CREATED', 'EXPIRED', 'SUSPENDED'],
    ACCOUNT_CREATED: ['PROPERTY_DETAILS_COMPLETE', 'DOCUMENTS_PENDING', 'EXPIRED', 'SUSPENDED'],
    PROPERTY_DETAILS_COMPLETE: ['DOCUMENTS_PENDING', 'UNDER_REVIEW', 'EXPIRED', 'SUSPENDED'],
    DOCUMENTS_PENDING: ['UNDER_REVIEW', 'CHANGES_REQUESTED', 'EXPIRED', 'SUSPENDED'],
    UNDER_REVIEW: ['CHANGES_REQUESTED', 'INSPECTION_REQUIRED', 'QUOTE_READY', 'REJECTED', 'SUSPENDED'],
    CHANGES_REQUESTED: ['UNDER_REVIEW', 'DOCUMENTS_PENDING', 'EXPIRED', 'SUSPENDED'],
    INSPECTION_REQUIRED: ['INSPECTION_IN_PROGRESS', 'CHANGES_REQUESTED', 'REJECTED', 'SUSPENDED'],
    INSPECTION_IN_PROGRESS: ['QUOTE_READY', 'CHANGES_REQUESTED', 'REJECTED', 'SUSPENDED'],
    QUOTE_READY: ['CONTRACT_SELECTED', 'CHANGES_REQUESTED', 'REJECTED', 'EXPIRED'],
    CONTRACT_SELECTED: ['SIGNATURE_PENDING', 'CANCELLED'],
    SIGNATURE_PENDING: ['PAYMENT_PENDING', 'APPROVED', 'CANCELLED'],
    PAYMENT_PENDING: ['PAYMENT_PROCESSING', 'CANCELLED'],
    PAYMENT_PROCESSING: ['PAYMENT_CONFIRMED', 'PAYMENT_PENDING', 'CHANGES_REQUESTED'],
    PAYMENT_CONFIRMED: ['APPROVED', 'SUSPENDED'],
    APPROVED: ['ACTIVE', 'SUSPENDED'],
    ACTIVE: ['SUSPENDED'],
    REJECTED: ['DRAFT'],
    EXPIRED: ['DRAFT'],
    SUSPENDED: ['UNDER_REVIEW', 'ACTIVE', 'DRAFT'],
  },
};

function token(value: unknown): string {
  return String(value ?? '')
    .trim()
    .replace(/[\s-]+/g, '_')
    .toUpperCase();
}

export function workflowStates(domain: WorkflowDomain): readonly string[] {
  return WORKFLOW_STATES[domain];
}

export function isCanonicalWorkflowState(domain: WorkflowDomain, value: unknown): boolean {
  return workflowStates(domain).includes(token(value) as never);
}

export function normalizeWorkflowState(
  domain: WorkflowDomain,
  value: unknown,
  fallback?: string,
): string {
  const normalized = token(value);
  if (isCanonicalWorkflowState(domain, normalized)) return normalized;
  const alias = ALIASES[domain][normalized];
  if (alias) return alias;
  if (fallback !== undefined) return assertCanonicalWorkflowState(domain, fallback);
  throw new Error(`Unknown ${domain} workflow state: ${normalized || '(empty)'}`);
}

export function assertCanonicalWorkflowState(domain: WorkflowDomain, value: unknown): string {
  const normalized = token(value);
  if (!isCanonicalWorkflowState(domain, normalized)) {
    throw new Error(`Non-canonical ${domain} workflow state write rejected: ${normalized || '(empty)'}`);
  }
  return normalized;
}

export function canTransitionWorkflow(
  domain: WorkflowDomain,
  fromRaw: unknown,
  toRaw: unknown,
): boolean {
  const from = normalizeWorkflowState(domain, fromRaw);
  const to = normalizeWorkflowState(domain, toRaw);
  if (from === to) return true;
  return (TRANSITIONS[domain][from] || []).includes(to);
}

export function assertWorkflowTransition(
  domain: WorkflowDomain,
  fromRaw: unknown,
  toRaw: unknown,
): string {
  const from = normalizeWorkflowState(domain, fromRaw);
  const to = assertCanonicalWorkflowState(domain, toRaw);
  if (!canTransitionWorkflow(domain, from, to)) {
    throw new Error(`Invalid ${domain} workflow transition: ${from} -> ${to}`);
  }
  return to;
}

export function legacyWorkflowAliases(domain: WorkflowDomain): Readonly<Record<string, CanonicalWorkflowState>> {
  return ALIASES[domain];
}
