import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";
import { Box } from "@mui/material";

type Language = 'en' | 'ar';

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.onboarding': 'Onboarding',
        'nav.financial': 'Financials',
        'nav.tech': 'Technician',
        'nav.admin': 'BIN-Groups Admin',
        'nav.tenants': 'Tenants',
        'nav.technicians': 'Technician Corps',
        'nav.tickets': 'Mission Logs',
        'nav.financials': 'Treasury',
        'nav.audit': 'Institutional Audit',
        'nav.brokers': 'Brokers',
        'nav.settings': 'Privacy Policy',
        'nav.live_map': 'Live Map',
        'nav.sos_feed': 'SOS Feed',
        'nav.reports': 'Reports',
        'nav.logout': 'Logout',
        'nav.admin_user': 'Admin User',
        'nav.version_info': 'v1.0.0 | Go-Go-Live: Jun 6, 2026',
        'nav.admin_panel_title': 'BIN-ADMINISTRY™ Command',
        'nav.sovereign_core': 'SOVEREIGN CORE',
        'nav.operations': 'OPERATIONS',
        'nav.support': 'Support',
        'nav.owner_portal_link': 'Owner Portal ↗',
        'nav.administry': 'ADMINISTRY',
        'landing.title': 'The Operating System for UAE Real Estate.',
        'landing.subtitle': 'BIN GROUP is the UAE\'s premier institutional asset management platform. We solve the complexity of large-scale property operations by unifying tenant management, predictive maintenance, and sovereign data compliance.',
        'landing.hero_title_line1': 'BINCONSTRUCTION™',
        'landing.hero_title_line2': 'SOVEREIGN MAINTENANCE',
        'landing.cta': 'Onboard Your Asset →',
        'landing.partner_login': 'PARTNER LOGIN',
        'landing.mission_overline': 'INSTITUTIONAL MISSION',
        'landing.mission_title': 'Institutional Mission',
        'landing.mission_desc': 'To establish the gold standard for property maintenance and construction in the UAE, ensuring every asset—from government councils to private estates—reflects the nation\'s vision for institutional excellence.',
        'landing.about_overline': 'CORPORATE PROFILE',
        'landing.about_title': 'Premium Sovereignty',
        'landing.about_desc': 'As a sovereign-aligned entity, we specialize in the high-stakes maintenance of government assets, heritage sites, and elite residential portfolios, delivering uncompromising technical precision and institutional security.',
        'landing.contact_title': 'Institutional Correspondence',
        'landing.email': 'hq@bin-groups.com',
        'landing.phone': '+971 4 888 8888',
        'landing.address': 'Binconstruction HQ, Level 88, Sovereign Tower, Sheikh Zayed Road, Dubai, UAE',
        'landing.sectors_title': 'Sectors We Master',
        'landing.sector.govt_title': 'Government & Sovereign',
        'landing.sector.govt_desc': 'Institutional-grade maintenance for Majlis, Ministries, and Federal assets with specialized protocol readiness.',
        'landing.sector.luxury_title': 'Luxury Hospitality',
        'landing.sector.luxury_desc': 'Preserving the gold standard for UAE’s elite hotel portfolios and ultra-luxury private residences.',
        'landing.sector.infra_title': 'Critical Infrastructure',
        'landing.sector.infra_desc': 'Technical support for logistics nodes, district cooling systems, and high-stakes commercial centers.',
        'landing.about_us': 'About Us',
        'landing.contact_us': 'Contact Us',
        'landing.support': 'Support',
        'landing.get_quote': 'Get Quote',
        'landing.who_we_are': 'Who We Are',
        'landing.who_we_are_desc': 'BIN GROUP is a UAE-based institutional powerhouse dedicated to the lifecycle management of premium and sovereign assets. We represent the intersection of advanced engineering and national data security.',
        'landing.what_we_do': 'What We Do',
        'landing.what_we_do_desc': 'From predictive maintenance for government Majlis to structural retrofitting for luxury towers, we provide the technical infrastructure that keeps the UAE\'s most valuable assets operational.',
        'landing.why_choose_us': 'Why BIN GROUP?',
        'landing.why_choose_us_desc': 'We are the only platform in the region that guarantees 100% data sovereignty on UAE soil while providing military-grade maintenance SLAs.',
        'landing.how_it_works': 'How It Works',
        'landing.how_it_works_desc': 'Onboard your portfolio, receive an institutional-grade audit, and deploy our specialized technician corps via our centralized command terminal.',
        'onboarding.title': 'Institutional Onboarding',
        'onboarding.description': 'BIN GROUP provides elite maintenance for all asset classes: Government Majlis, Government Properties, Hotels, Residential, Commercial, and Institutional nodes.',
        'onboarding.bulk_intake': 'Bulk Property Intake (1–500)',
        'onboarding.property_details': 'Property Details',
        'onboarding.analysis': 'Asset Analysis',
        'onboarding.quote': 'BIN-Groups Quote',
        'onboarding.payment': 'Activation',
        'step.intake': 'Property Intake',
        'step.analysis': 'Asset Analysis',
        'step.quote': 'BIN-Groups Quote',
        'step.tier': 'Contract Selection',
        'step.addons': 'Service Tailoring',
        'step.summary': 'Security Deposit',
        'step.account': 'Account Activation',
        'field.emirate': 'Emirate',
        'field.area': 'Area / Cluster',
        'field.type': 'Property Type',
        'field.subtype': 'Sub-Type',
        'field.usetype': 'Usage Type',
        'field.floors': 'Floors',
        'field.units': 'Units',
        'field.sqft': 'Square Footage',
        'field.age': 'Building Age',
        'field.lifts': 'Lifts',
        'field.pool': 'Pool',
        'field.tank': 'Water Tank',
        'field.sira': 'SIRA / CCTV',
        'field.fire': 'Fire Systems',
        'field.dist_cooling': 'District Cooling',
        'field.majlis': 'Government Majlis Protocol',
        'field.heritage': 'Heritage Sensitivity',
        'field.grade': 'Asset Grade',
        'field.status': 'Current Status',
        'btn.next': 'Next',
        'btn.back': 'Back',
        'btn.add_prop': 'Add Property (+)',
        'btn.bulk_csv': 'Upload CSV',
        'btn.exit': 'Exit',
        'btn.quote': 'GET INSTITUTIONAL QUOTE',
        'status.tender_ready': 'TENDER READY',
        'status.sovereign': 'BIN-GROUPS GRADE',
        'login.portal': 'PARTNER PORTAL',
        'login.auth_access': 'AUTHENTICATED INSTITUTIONAL ACCESS',
        'login.email': 'Access Email',
        'login.password': 'Secure Key (Password)',
        'login.signin': 'SECURE SIGN IN',
        'login.google': 'SIGN IN WITH GOOGLE',
        'login.or_sso': 'OR INSTITUTIONAL SSO',
        'login.iso_secure': 'ISO 27001 SECURE',
        'login.inst_grade': 'INSTITUTIONAL GRADE',
        'login.uae_ops': 'UAE PORTFOLIO OPS',
        'login.footer': '© 2026 BIN-GROUP UAE. UNAUTHORIZED ACCESS IS MONITORED.',
        'dash.title': 'Portfolio Intelligence',
        'dash.terminal': 'Terminal',
        'dash.locked_assets': 'Locked Assets',
        'dash.onboard_cta': '+ ONBOARD NEW ASSET',
        'dash.kpi.gross_val': 'GROSS CONTRACT VALUE',
        'dash.kpi.annual_yield': 'ANNUAL YIELD (EST)',
        'dash.kpi.radius': 'PORTFOLIO RADIUS',
        'dash.kpi.majlis_readiness': 'INSTITUTIONAL READINESS',
        'dash.kpi.net_roi': 'NET ROI',
        'dash.kpi.gross_roi': 'GROSS ROI',
        'dash.kpi.esg': 'SOVEREIGN ESG',
        'dash.kpi.compliance': 'COMPLIANCE SCORE',
        'dash.kpi.integrity': 'ASSET INTEGRITY',
        'dash.kpi.satisfaction': 'TENANT SATISFACTION',
        'dash.kpi.trend.live': 'LIVE',
        'dash.kpi.trend.active': 'ACTIVE',
        'dash.kpi.trend.optimal': 'OPTIMAL',
        'dash.ledger': 'ASSET LEDGER',
        'dash.asset_node': 'ASSET NODE',
        'dash.health_index': 'HEALTH INDEX',
        'dash.annual_amc': 'ANNUAL AMC',
        'dash.protocol_status': 'PROTOCOL STATUS',
        'dash.private_asset': 'Private Asset',
        'dash.alerts': 'SOVEREIGN ALERTS',
        'dash.intel.deck': 'SOVEREIGN INTELLIGENCE DECK',
        'dash.intel.forecast': 'AI FORECAST',
        'dash.intel.integrity_decay': 'INTEGRITY DECAY',
        'dash.intel.horizon': '12-MONTH HORIZON',
        'dash.intel.projected_yield': 'PROJECTED YIELD',
        'dash.intel.annualized_net': 'ANNUALIZED NET',
        'dash.intel.guidance_title': 'STRATEGIC MISSION GUIDANCE',
        'dash.intel.protocol_commands': 'SOVEREIGN PROTOCOL COMMANDS',
        'dash.intel.download_audit': 'DOWNLOAD INTEGRITY AUDIT (PDF)',
        'dash.intel.generating_audit': 'GENERATING SOVEREIGN AUDIT...',
        'dash.command_deck': 'SOVEREIGN ASSET COMMAND',
        'dash.command_subtitle': 'Institutional Grade Auditing & National Zone Interface',
        'dash.empty_title': 'PORTFOLIO OFFLINE',
        'dash.empty_subtitle': 'You have no active bin-group institutional service contracts. Begin your sovereign asset onboarding to unlock live monitoring.',
        'dash.empty_cta': '+ START ASSET ONBOARDING',
        'dash.mission_feed': 'MISSION FEED',
        'dash.listening': 'Listening for mission-critical protocol alerts...',
        'dash.hash_anchor': 'SOVEREIGN HASH ANCHOR',
        'dash.municipality_adapter': 'MUNICIPALITY ADAPTER',
        'dash.risk_grade': 'INSURER RISK GRADE',
        'dash.gateway_status': 'GATEWAY STATUS',
        'dash.audit_btn': 'GENERATE INSTITUTIONAL AUDIT',
        'dash.sync_btn': 'MANUAL SYNC',
        'dash.status.optimal': 'P.1 (OPTIMAL)',
        'dash.status.stable': 'P.2 (STABLE)',
        'sos.btn': 'TRIGGER SOS DISPATCH',
        'sos.title': 'SOS Dispatch',
        'sos.subtitle': 'Report critical infrastructure failures for immediate institutional restoration.',
        'sos.success_title': 'DISPATCH TRIGGERED',
        'sos.success_subtitle': 'Mission parameters received. V4 Geo-Engine is routing your request.',
        'sos.emergency_protocol': 'EMERGENCY PROTOCOL',
        'sos.fault_category': 'FAULT CATEGORY',
        'sos.mission_description': 'MISSION DESCRIPTION',
        'sos.description_placeholder': 'Provide unit details and fault specifics...',
        'sos.attach_evidence': 'ATTACH VISUAL EVIDENCE',
        'sos.trigger_btn': 'TRIGGER DISPATCH',
        'sos.cat.ac': 'AC / HVAC CRITICAL FAILURE',
        'sos.cat.plumbing': 'MAJOR PLUMBING / FLOODING',
        'sos.cat.electrical': 'ELECTRICAL SHORT / BLACKOUT',
        'sos.cat.security': 'SECURITY / ACCESS BREACH',
        'sos.return_dash': 'RETURN TO DASHBOARD',
        'sos.location_locked': 'MISSION LOCATION LOCKED',
        'sos.timing_label': 'Preferred Timing',
        'sos.asap': 'ASAP (Emergency)',
        'sos.morning': 'Morning (8AM - 12PM)',
        'sos.afternoon': 'Afternoon (12PM - 4PM)',
        'sos.evening': 'Evening (4PM - 8PM)',
        'sos.photo_attached': 'Photo Attached',
        'sos.attach_photo': 'Attach Photo Proof',
        'tech.service_node': 'Service Node',
        'tech.subtitle': 'Live maintenance grid and sovereign asset restoration.',
        'tech.mission_dispatch': 'MISSION DISPATCH',
        'tech.active_tickets': 'ACTIVE TICKETS',
        'tech.kpi.mttr': 'MTTR (AVG)',
        'tech.kpi.sla': 'SLA COMPLIANCE',
        'tech.kpi.uptime': 'ZONE UPTIME',
        'tech.trend.live': 'LIVE',
        'tech.trend.optimal': 'OPTIMAL',
        'tech.trend.sovereign': 'SOVEREIGN',
        'tech.trend.stable': 'STABLE',
        'tech.protocol': 'PROTOCOL ALPHA-4',
        'tech.priority.normal': 'NORMAL',
        'tech.priority.emergency': 'EMERGENCY',
        'tech.status_tracking': 'STATUS TRACKING',
        'tech.open_node': 'OPEN NODE',
        'tech.empty': 'No active mission dispatches in this sector.',
        'tech.unknown_unit': 'Unknown Unit',
        'tech.status.live': 'LIVE',
        'tech.status.syncing': 'SYNCING',
        'tech.live_ops': 'LIVE OPERATIONS',
        'tech.urgent_dispatch': 'URGENT DISPATCH',
        'tech.navigate': 'NAVIGATE',
        'tech.mission_brief': 'MISSION BRIEF',
        'tech.enable_alerts': 'ENABLE ALERTS',
        'tech.alerts_on': 'ALERTS ACTIVE',
        'tech.missions': 'Missions',
        'tech.hr_duty': 'HR & Duty',
        'tech.mission_pool': 'Mission Pool',
        'tech.pool_id': 'POOL ID',
        'tech.accept': 'Accept',
        'tech.notif_handshake_success': 'SUCCESS: Sovereign Notification Channel Established.',
        'tech.notif_link': 'Notification Link',
        'tech.notif_ios_pwa': 'Required for emergency dispatches on iOS PWAs.',
        'tech.notif_active': 'DISPATCH LINK ACTIVE',
        'tech.notif_enable': 'Enable Push Notifications',
        'tech.duty_sync': 'Duty Synchronization',
        'tech.duty_subtitle': 'Set your availability for the automated dispatch engine.',
        'tech.on_duty': 'ON DUTY',
        'tech.off_duty': 'OFF DUTY',
        'tech.workload_node': 'Workload Node',
        'tech.standard_hours': 'Standard Hours (This Week)',
        'tech.reward_unlocked': 'SOVEREIGN REWARD UNLOCKED',
        'tech.vacation_unlocked': 'Congratulations! You have unlocked your 35-Day Annual Vacation.',
        'footer.home': 'Home',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.support': 'Institutional Support',
        'footer.copyright': '© 2026 BINCONSTRUCTION™ UAE. ALL RIGHTS RESERVED.',
        'common.system': 'SYSTEM',
        'common.sys_init_fault': 'SYSTEM INITIALIZATION FAULT',
        'common.reload_sys': 'RELOAD SYSTEM',
        'status.owner': 'Owner',
        'common.asset': 'Asset',
        'status.pending': 'Pending',
        'onboarding.payment.verify_btn': 'Verify Payment',
        'support.title': 'Institutional Support',
        'support.subtitle': 'Secure communication channel for asset owners and institutional partners.',
        'support.email': 'Email Support',
        'support.phone': 'Direct Hotline',
        'support.office': 'Headquarters',
        'support.office_address': 'Binconstruction HQ, Level 88, Sovereign Tower, Sheikh Zayed Road, Dubai, UAE',
        'tech.table.floor': 'Floor',
        'tech.table.tech': 'Specialist',
        'common.action': 'Action',
        'tech.action.evidence_required': 'Evidence Required',
        'tech.photo.before_uploaded': 'Before Photo Uploaded',
        'tech.photo.after_uploaded': 'After Photo Uploaded',
    },
    ar: {
        'nav.dashboard': 'لوحة القيادة',
        'nav.onboarding': 'التسجيل',
        'nav.financial': 'المالية',
        'nav.tech': 'فني',
        'nav.admin': 'إدارة مجموعة بن',
        'nav.tenants': 'المستأجرون',
        'nav.technicians': 'فيلق الفنيين',
        'nav.tickets': 'سجلات المهام',
        'nav.financials': 'الخزينة',
        'nav.audit': 'التدقيق المؤسسي',
        'nav.brokers': 'الوسطاء',
        'nav.settings': 'سياسة الخصوصية',
        'nav.live_map': 'الخريطة المباشرة',
        'nav.sos_feed': 'تغذية الاستغاثة',
        'nav.reports': 'التقارير',
        'nav.logout': 'تسجيل الخروج',
        'nav.admin_user': 'مستخدم مسؤول',
        'nav.version_info': 'v1.0.0 | تاريخ الإطلاق: 6 يونيو 2026',
        'nav.admin_panel_title': 'لوحة تحكم BIN-ADMINISTRY™',
        'nav.sovereign_core': 'النواة السيادية',
        'nav.operations': 'العمليات',
        'nav.support': 'الدعم',
        'nav.owner_portal_link': 'بوابة الملاك ↗',
        'nav.administry': 'الإدارة',
        'landing.title': 'نظام التشغيل للعقارات في الإمارات.',
        'landing.subtitle': 'مجموعة بن هي المنصة المؤسسية الرائدة في الإمارات لإدارة الأصول. نحن نحل تعقيدات العمليات العقارية واسعة النطاق من خلال توحيد إدارة المستأجرين، والصيانة التنبؤية، والامتثال للبيانات السيادية.',
        'landing.hero_title_line1': 'بن للإنشاءات™',
        'landing.hero_title_line2': 'صيانة مجموعة بن',
        'landing.cta': 'سجل أصولك الآن ←',
        'landing.partner_login': 'دخول الشركاء',
        'landing.mission_overline': 'المهمة المؤسسية',
        'landing.mission_title': 'المهمة المؤسسية',
        'landing.mission_desc': 'إرساء المعايير الذهبية لصيانة العقارات والإنشاءات في دولة الإمارات، لضمان أن كل أصل - من المجالس الحكومية إلى العقارات الخاصة - يعكس رؤية الدولة للتميز المؤسسي.',
        'landing.about_overline': 'ملف الشركة',
        'landing.about_title': 'سيادة متميزة',
        'landing.about_desc': 'بصفتنا كياناً متوافقاً مع المعايير السيادية، نحن متخصصون في الصيانة عالية الأهمية للأصول الحكومية والمواقع التراثية والمحافظ السكنية النخبوية، ونقدم دقة تقنية لا تضاهى وأمناً مؤسسياً.',
        'landing.contact_title': 'المراسلات المؤسسية',
        'landing.email': 'hq@bin-groups.com',
        'landing.phone': '+971 4 888 8888',
        'landing.address': 'المقر الرئيسي لبن للإنشاءات، طابق 88، برج سوفرين، شارع الشيخ زايد، دبي، الإمارات',
        'landing.sectors_title': 'القطاعات التي نتقنها',
        'landing.sector.govt_title': 'الحكومة والجهات السيادية',
        'landing.sector.govt_desc': 'صيانة بمستوى مؤسسي للمجالس والوزارات والأصول الاتحادية مع جاهزية متخصصة للبروتوكولات.',
        'landing.sector.luxury_title': 'الضيافة الفاخرة',
        'landing.sector.luxury_desc': 'الحفاظ على المعايير الذهبية لمحفظة الفنادق النخبة في الإمارات والإقامات الخاصة فائقة الفخامة.',
        'landing.sector.infra_title': 'البنية التحتية الحيوية',
        'landing.sector.infra_desc': 'الدعم الفني للعقد اللوجستية، وأنظمة تبريد المناطق، والمراكز التجارية عالية الأهمية.',
        'landing.about_us': 'من نحن',
        'landing.contact_us': 'اتصل بنا',
        'landing.support': 'الدعم',
        'landing.get_quote': 'احصل على تسعيرة',
        'landing.who_we_are': 'من نحن',
        'landing.who_we_are_desc': 'مجموعة بن هي قوة مؤسسية مقرها الإمارات مكرسة لإدارة دورة حياة الأصول الممتازة والسيادية. نحن نمثل نقطة التلاقي بين الهندسة المتقدمة وأمن البيانات الوطني.',
        'landing.what_we_do': 'ماذا نفعل',
        'landing.what_we_do_desc': 'من الصيانة التنبؤية للمجالس الحكومية إلى التحديث الهيكلي للأبراج الفاخرة، نوفر البنية التحتية التقنية التي تحافظ على تشغيل أهم الأصول في الإمارات.',
        'landing.why_choose_us': 'لماذا مجموعة بن؟',
        'landing.why_choose_us_desc': 'نحن المنصة الوحيدة في المنطقة التي تضمن سيادة البيانات بنسبة 100% على أراضي الإمارات مع تقديم اتفاقيات مستوى خدمة صيانة بمستوى عسكري.',
        'landing.how_it_works': 'كيف يعمل النظام',
        'landing.how_it_works_desc': 'قم بتسجيل محفظتك، واحصل على تدقيق بمستوى مؤسسي، وانشر فيلق الفنيين المتخصصين لدينا عبر محطة القيادة المركزية الخاصة بنا.',
        'onboarding.title': 'التسجيل المؤسسي',
        'onboarding.description': 'توفر مجموعة بن صيانة متميزة لجميع فئات الأصول: المجالس الحكومية، العقارات الحكومية، الفنادق، السكني، التجاري، والمراكز المؤسسية.',
        'onboarding.bulk_intake': 'إدخال العقارات بالجملة (1–500)',
        'onboarding.property_details': 'تفاصيل العقار',
        'onboarding.analysis': 'تحليل الأصول',
        'onboarding.quote': 'تسعيرة مجموعة بن',
        'onboarding.payment': 'التفعيل',
        'step.intake': 'إدخال العقار',
        'step.analysis': 'تحليل الأصول',
        'step.quote': 'تسعيرة مجموعة بن',
        'step.tier': 'اختيار العقد',
        'step.addons': 'تخصيص الخدمات',
        'step.summary': 'مبلغ التأمين',
        'step.account': 'تفعيل الحساب',
        'field.emirate': 'الإمارة',
        'field.area': 'المنطقة / المجمع',
        'field.type': 'نوع العقار',
        'field.subtype': 'النوع الفرعي',
        'field.usetype': 'نوع الاستخدام',
        'field.floors': 'الأدوار',
        'field.units': 'الوحدات',
        'field.sqft': 'المساحة (قدم مربع)',
        'field.age': 'عمر المبنى',
        'field.lifts': 'المصاعد',
        'field.pool': 'المسبح',
        'field.tank': 'خزان المياه',
        'field.sira': 'سيرا / كاميرات المراقبة',
        'field.fire': 'أنظمة الحريق',
        'field.dist_cooling': 'تكييف المناطق',
        'field.majlis': 'بروتوكول المجالس الحكومية',
        'field.heritage': 'حساسية المواقع التراثية',
        'field.grade': 'فئة الأصول',
        'field.status': 'الحالة الحالية',
        'btn.next': 'التالي',
        'btn.back': 'السابق',
        'btn.add_prop': 'إضافة عقار (+)',
        'btn.bulk_csv': 'تحميل ملف CSV',
        'btn.exit': 'خروج',
        'btn.quote': 'احصل على تسعيرة مؤسسية',
        'status.tender_ready': 'جاهز للمناقصة',
        'status.sovereign': 'فئة مجموعة بن',
        'login.portal': 'بوابة الشركاء',
        'login.auth_access': 'دخول مؤسسي موثق',
        'login.email': 'البريد الإلكتروني للدخول',
        'login.password': 'المفتاح الآمن (كلمة المرور)',
        'login.signin': 'دخول آمن',
        'login.google': 'الدخول عبر جوجل',
        'login.or_sso': 'أو الدخول المؤسسي الموحد',
        'login.iso_secure': 'آمن بمعايير ISO 27001',
        'login.inst_grade': 'درجة مؤسسية',
        'login.uae_ops': 'عمليات محفظة الإمارات',
        'login.footer': '© 2026 مجموعة بن الإمارات. الدخول غير المصرح به مراقب.',
        'dash.title': 'ذكاء المحفظة',
        'dash.terminal': 'المحطة',
        'dash.locked_assets': 'الأصول المقفلة',
        'dash.onboard_cta': '+ تسجيل أصل جديد',
        'dash.kpi.gross_val': 'إجمالي قيمة العقد',
        'dash.kpi.annual_yield': 'العائد السنوي (تقديري)',
        'dash.kpi.radius': 'نطاق المحفظة',
        'dash.kpi.majlis_readiness': 'الجاهزية المؤسسية',
        'dash.kpi.net_roi': 'صافي العائد على الاستثمار',
        'dash.kpi.gross_roi': 'إجمالي العائد',
        'dash.kpi.esg': 'معايير ESG',
        'dash.kpi.compliance': 'درجة الامتثال',
        'dash.kpi.integrity': 'سلامة الأصول',
        'dash.kpi.satisfaction': 'رضا المستأجرين',
        'dash.kpi.trend.live': 'مباشر',
        'dash.kpi.trend.active': 'نشط',
        'dash.kpi.trend.optimal': 'مثالي',
        'dash.ledger': 'سجل الأصول',
        'dash.asset_node': 'عقدة الأصول',
        'dash.health_index': 'HEALTH INDEX',
        'dash.annual_amc': 'عقد الصيانة السنوي (AMC)',
        'dash.protocol_status': 'حالة البروتوكول',
        'dash.private_asset': 'أصل خاص',
        'dash.alerts': 'تنبيهات مجموعة بن',
        'dash.intel.deck': 'منصة ذكاء مجموعة بن',
        'dash.intel.forecast': 'توقعات الذكاء الاصطناعي',
        'dash.intel.integrity_decay': 'تآكل السلامة',
        'dash.intel.horizon': 'أفق 12 شهراً',
        'dash.intel.projected_yield': 'العائد المتوقع',
        'dash.intel.annualized_net': 'صافي سنوي',
        'dash.intel.guidance_title': 'توجيه المهمة الاستراتيجية',
        'dash.intel.protocol_commands': 'أوامر بروتوكول مجموعة بن',
        'dash.intel.download_audit': 'تحميل تدقيق السلامة (PDF)',
        'dash.intel.generating_audit': 'جاري إصدار تدقيق مجموعة بن...',
        'dash.command_deck': 'قيادة أصول مجموعة بن',
        'dash.command_subtitle': 'التدقيق المؤسسي وواجهة المنطقة الوطنية',
        'dash.empty_title': 'المحفظة غير متصلة',
        'dash.empty_subtitle': 'ليس لديك عقود خدمات مؤسسية نشطة مع مجموعة بن. ابدأ تسجيل أصولك لفتح المراقبة المباشرة.',
        'dash.empty_cta': '+ ابدأ تسجيل الأصول',
        'dash.mission_feed': 'تغذية المهام',
        'dash.listening': 'الاستماع لتنبيهات البروتول للمهمات الحرجة...',
        'dash.hash_anchor': 'رابط تشفير مجموعة بن',
        'dash.municipality_adapter': 'محول البلدية',
        'dash.risk_grade': 'فئة مخاطر التأمين',
        'dash.gateway_status': 'حالة البوابة',
        'dash.audit_btn': 'إصدار تدقيق مؤسسي',
        'dash.sync_btn': 'مزامنة مع البوابة الوطنية',
        'dash.status.optimal': 'أمثل (P.1)',
        'dash.status.stable': 'مستقر (P.2)',
        'sos.btn': 'تفعيل استغاثة SOS',
        'sos.title': 'إرسال استغاثة',
        'sos.subtitle': 'الإبلاغ عن أعطال البنية التحتية الحرجة للإصلاح المؤسسي الفوري.',
        'sos.success_title': 'تم تفعيل الإرسال',
        'sos.success_subtitle': 'تم استلام معايير المهمة. محرك الجغرافيا V4 يقوم بتوجيه طلبك.',
        'sos.emergency_protocol': 'بروتوكول الطوارئ',
        'sos.fault_category': 'فئة العطل',
        'sos.mission_description': 'وصف المهمة',
        'sos.description_placeholder': 'قدم تفاصيل الوحدة وتفاصيل العطل...',
        'sos.attach_evidence': 'إرفاق دليل مرئي',
        'sos.trigger_btn': 'تفعيل الإرسال',
        'sos.cat.ac': 'عطل حرج في التكييف',
        'sos.cat.plumbing': 'عطل سباكة رئيسي / فيضان',
        'sos.cat.electrical': 'ماس كهربائي / انقطاع تيار',
        'sos.cat.security': 'خرق أمني / دخول',
        'sos.return_dash': 'العودة للوحة القيادة',
        'sos.location_locked': 'تم قفل موقع المهمة',
        'sos.timing_label': 'التوقيت المفضل',
        'sos.asap': 'في أسرع وقت (طوارئ)',
        'sos.morning': 'صباحاً (8ص - 12ظ)',
        'sos.afternoon': 'بعد الظهر (12ظ - 4ع)',
        'sos.evening': 'مساءً (4ع - 8م)',
        'sos.photo_attached': 'تم إرفاق الصورة',
        'sos.attach_photo': 'إرفاق دليل مصور',
        'tech.service_node': 'عقدة الخدمة',
        'tech.subtitle': 'شبكة الصيانة المباشرة وترميم أصول مجموعة بن.',
        'tech.mission_dispatch': 'إرسال المهمة',
        'tech.active_tickets': 'التذاكر النشطة',
        'tech.kpi.mttr': 'متوسط وقت الإصلاح',
        'tech.kpi.sla': 'الالتزام بـ SLA',
        'tech.kpi.uptime': 'جاهزية المنطقة',
        'tech.trend.live': 'مباشر',
        'tech.trend.optimal': 'مثالي',
        'tech.trend.sovereign': 'مجموعة بن',
        'tech.trend.stable': 'مستقر',
        'tech.protocol': 'بروتوكول ألفا-4',
        'tech.priority.normal': 'عادي',
        'tech.priority.emergency': 'طوارئ',
        'tech.status_tracking': 'تتبع الحالة',
        'tech.open_node': 'فتح العقدة',
        'tech.empty': 'لا توجد مهمات نشطة في هذا القطاع.',
        'tech.unknown_unit': 'وحدة غير معروفة',
        'tech.status.live': 'مباشر',
        'tech.status.syncing': 'جاري المزامنة',
        'tech.live_ops': 'العمليات المباشرة',
        'tech.urgent_dispatch': 'إرسال عاجل',
        'tech.navigate': 'توجيه',
        'tech.mission_brief': 'ملخص المهمة',
        'tech.enable_alerts': 'تفعيل التنبيهات',
        'tech.alerts_on': 'التنبيهات نشطة',
        'tech.missions': 'المهمات',
        'tech.hr_duty': 'الموارد البشرية والدوام',
        'tech.mission_pool': 'مجمع المهمات',
        'tech.pool_id': 'معرف المجمع',
        'tech.accept': 'قبول',
        'tech.notif_handshake_success': 'نجاح: تم إنشاء قناة تنبيهات مجموعة بن.',
        'tech.notif_link': 'رابط التنبيهات',
        'tech.notif_ios_pwa': 'مطلوب للإرسال العاجل على تطبيقات iOS PWA.',
        'tech.notif_active': 'رابط الإرسال نشط',
        'tech.notif_enable': 'تفعيل تنبيهات الدفع',
        'tech.duty_sync': 'مزامنة الدوام',
        'tech.duty_subtitle': 'حدد توافرك لمحرك الإرسال الآلي.',
        'tech.on_duty': 'في الدوام',
        'tech.off_duty': 'خارج الدوام',
        'tech.workload_node': 'عقدة عبء العمل',
        'tech.standard_hours': 'الساعات القياسية (هذا الأسبوع)',
        'tech.reward_unlocked': 'تم فتح مكافأة سيادية',
        'tech.vacation_unlocked': 'تهانينا! لقد حصلت على إجازتك السنوية لمدة 35 يوماً.',
        'footer.home': 'الرئيسية',
        'footer.privacy': 'سياسة الخصوصية',
        'footer.terms': 'شروط الخدمة',
        'footer.support': 'الدعم المؤسسي',
        'footer.copyright': '© 2026 بن للإنشاءات™ الإمارات. جميع الحقوق محفوظة.',
        'common.system': 'النظام',
        'common.sys_init_fault': 'خطأ في تهيئة النظام',
        'common.reload_sys': 'إعادة تحميل النظام',
        'status.owner': 'مالك',
        'common.asset': 'أصل',
        'status.pending': 'قيد الانتظار',
        'onboarding.payment.verify_btn': 'التحقق من الدفع',
        'support.title': 'الدعم المؤسسي',
        'support.subtitle': 'قناة اتصال آمنة لملاك الأصول والشركاء المؤسسيين.',
        'support.email': 'دعم البريد الإلكتروني',
        'support.phone': 'الخط الساخن المباشر',
        'support.office': 'المقر الرئيسي',
        'support.office_address': 'المقر الرئيسي لبن للإنشاءات، طابق 88، برج سوفرين، شارع الشيخ زايد، دبي، الإمارات',
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [lang, setLang] = useState<Language>(() => {
        const saved = localStorage.getItem('app_lang');
        return (saved as Language) || 'en';
    });

    useEffect(() => {
        localStorage.setItem('app_lang', lang);
        document.dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key: string, variables?: Record<string, any>) => {
        let text = translations[lang]?.[key] || translations['en']?.[key] || key;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v));
            });
        }
        return text;
    };

    const isRTL = lang === 'ar';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
            <Box 
                id="bin-app-root"
                dir={isRTL ? 'rtl' : 'ltr'}
                sx={{ 
                    direction: isRTL ? 'rtl' : 'ltr', 
                    minHeight: '100vh',
                    fontFamily: "'Cairo', 'Inter', sans-serif",
                    backgroundColor: '#000',
                    color: '#fff'
                }}
            >
                {children}
            </Box>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
