import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";
import { Box } from "@mui/material";

type Language = 'en' | 'ar';

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
    tx: (key: string, fallback: string, variables?: Record<string, any>) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        'admin.active_tenants': 'ACTIVE TENANTS',
        'admin.active_tickets': 'ACTIVE TICKETS',
        'admin.amount': 'AMOUNT',
        'admin.contract_ref': 'CONTRACT REF',
        'admin.dashboard': 'ADMIN DASHBOARD',
        'admin.system_health': 'SYSTEM HEALTH',
        'admin.total_revenue': 'TOTAL REVENUE',
        'analysis.efficiency': 'OPERATIONAL EFFICIENCY',
        'common.currency': 'AED',
        'common.currency_aed': 'AED',
        'dash.command_subtitle': 'Institutional Grade Auditing & National Zone Interface',
        'dash.declined': 'DECLINED',
        'dash.kpi.net_roi': 'NET ROI',
        'dash.proposed': 'PROPOSED',
        'dash.proposed_roi': 'PROPOSED ROI',
        'dash.realized_roi': 'REALIZED ROI',
        'dash.risk_mitigation': 'RISK MITIGATION',
        'dash.sanctioned': 'SANCTIONED',
        'dash.sovereign_ai': 'SOVEREIGN AI',
        'fin.burn': 'BURN',
        'fin.income': 'INCOME',
        'fin.logs_title': 'SYSTEMIC LEDGER LOGS',
        'fin.log.date': 'DATE',
        'fin.log.status': 'STATUS',
        'fin.total_deductions': 'TOTAL DEDUCTIONS',
        'landing.cta': 'Onboard Your Asset →',
        'landing.subtitle': 'BIN GROUP is the UAE\'s premier institutional asset management platform.',
        'landing.title': 'The Operating System for UAE Real Estate.',
        'landing.transparency_title': 'GROWTH & RISK TRANSPARENCY',
        'nav.admin': 'BIN-Groups Admin',
        'nav.administry': 'ADMINISTRY',
        'nav.audit': 'Institutional Audit',
        'nav.brokers': 'Brokers',
        'nav.dashboard': 'Dashboard',
        'nav.financial': 'Financials',
        'nav.financials': 'Treasury',
        'nav.live_map': 'Live Map',
        'nav.logout': 'Logout',
        'nav.onboarding': 'Onboarding',
        'nav.operations': 'OPERATIONS',
        'nav.owner_portal_link': 'Owner Portal ↗',
        'nav.reports': 'Reports',
        'nav.settings': 'Privacy Policy',
        'nav.sos_feed': 'SOS Feed',
        'nav.sovereign_core': 'SOVEREIGN CORE',
        'nav.support': 'Support',
        'nav.tech': 'Technician',
        'nav.technicians': 'TECHNICIAN CORPS',
        'nav.tenants': 'Tenants',
        'nav.tickets': 'Mission Logs',
        'onboarding.payment.proceed_btn': 'ENTER DASHBOARD',
        'onboarding.property_details': 'PROPERTIES',
        'onboarding.title': 'Institutional Onboarding',
        'status.settled': 'SETTLED',
        'status.estimated': 'ESTIMATED',
        'status.awaiting_owner_approval': 'AWAITING OWNER APPROVAL',
        'status.approved': 'APPROVED',
        'status.rejected': 'REJECTED',
        'status.revised_quote_sent': 'REVISED QUOTE SENT',
        'status.overdue_approval': 'OVERDUE APPROVAL',
        'support.phone': 'Hotline',
        'tech.active_tickets': 'ASSIGNED SPECIALISTS',
        'tech.ai_proposal': 'AI PROTOCOL PROPOSALS',
        'onboarding.save_later': 'Save & Resume Later',
        'onboarding.institutional': 'INSTITUTIONAL ONBOARDING',
        'onboarding.back_website': 'Back to website',
        'onboarding.payment': 'Payment',
        'onboarding.review': 'Review Summary',
        'onboarding.verification': 'Verification',
        'onboarding.documents': 'Documents',
        'onboarding.service_plan': 'Service Plan',
        'onboarding.addons': 'Add-Ons',
        'onboarding.systems': 'Systems & Services',
        'onboarding.asset': 'Asset',
        'onboarding.company': 'Company',
        'onboarding.location': 'Location',
        'onboarding.acc_creation': 'Account Creation',
        'onboarding.acc_creation_desc': 'Create the owner login after property and proof details have been completed.',
        'onboarding.acc_creation_warning': 'Dashboard access stays locked until admin approval and mobilization payment verification.',
        'onboarding.full_name': 'Full Name',
        'onboarding.mobile': 'Mobile Number',
        'onboarding.email': 'Email',
        'onboarding.password': 'Password',
        'onboarding.confirm_password': 'Confirm Password',
        'onboarding.create_btn': 'Create Account',
        'onboarding.back': 'Back',
        'onboarding.loading': 'Creating...',
        'onboarding.success_locked': 'Account created. Dashboard access remains locked until admin approval and mobilization payment verification.',
        'onboarding.error.email_exists': 'This email already has an account. Please sign in or use password reset.',
        'onboarding.error.google_only': 'This email is registered with Google. Please continue with Google Sign-In.',
        'onboarding.error.role_conflict': 'This email is already registered under another role. Please contact BIN GROUP support or use a different owner email.',
        'onboarding.company_profile': 'COMPANY PROFILE',
        'onboarding.company_desc': 'Establish your institutional identity within the BIN GROUP Sovereign OS.',
        'onboarding.company_name': 'Company / Entity Name',
        'onboarding.trade_license': 'Trade License Number (Optional)',
        'onboarding.primary_contact': 'PRIMARY CONTACT',
        'onboarding.contact_name': 'Contact Person Name',
        'onboarding.contact_phone': 'Contact Phone',
        'onboarding.contact_email': 'Contact Email',
        'onboarding.onboard_btn': 'ONBOARD YOUR PROPERTY',
        'onboarding.asset_profile': 'ASSET PROFILE',
        'onboarding.asset_desc': 'Define the technical and commercial parameters of your property.',
        'onboarding.asset_name': 'Property / Asset Name',
        'onboarding.asset_type': 'Asset Category',
        'onboarding.unit_count': 'Total Units',
        'onboarding.floor_count': 'Total Floors',
        'onboarding.property_age': 'Property Age (Years)',
        'onboarding.systems_title': 'SYSTEMS & SERVICES',
        'onboarding.systems_desc': 'Select critical systems requiring institutional maintenance and audit.',
        'onboarding.systems.hvac': 'Central HVAC',
        'onboarding.systems.elevators': 'Elevator Systems',
        'onboarding.systems.fire': 'Fire & Life Safety',
        'onboarding.systems.cctv': 'SIRA CCTV & Security',
        'onboarding.systems.pool': 'Swimming Pool / Water Features',
        'onboarding.systems.generator': 'Backup Power / Generators',
        'onboarding.location_title': 'PROPERTY LOCATION',
        'onboarding.location_desc': 'Pinpoint the geographical coordinates for operational dispatch.',
        'onboarding.emirate': 'Emirate',
        'onboarding.zone': 'Service Zone',
        'onboarding.address': 'Physical Address',
        'onboarding.documents_title': 'COMPLIANCE DOCUMENTS',
        'onboarding.documents_desc': 'Upload proof of ownership and technical certifications.',
        'onboarding.doc.title_deed': 'Title Deed / Ownership Proof',
        'onboarding.doc.passport': 'Owner Passport / Emirates ID',
        'onboarding.doc.license': 'Trade License (for Entities)',
        'onboarding.doc.mou': 'MOU / Management Agreement',
        'onboarding.service_plan_title': 'CHOOSE SERVICE PLAN',
        'onboarding.service_plan_desc': 'Select the institutional coverage tier for your asset.',
        'onboarding.type.villa': 'Villa',
        'onboarding.type.apartment': 'Apartment',
        'onboarding.type.res_building': 'Residential Building',
        'onboarding.type.com_building': 'Commercial Building',
        'onboarding.type.office': 'Office',
        'onboarding.type.retail': 'Retail Center',
        'onboarding.type.mall': 'Mall',
        'onboarding.type.hotel': 'Hotel',
        'onboarding.type.hospital': 'Hospital',
        'onboarding.type.clinic': 'Clinic',
        'onboarding.type.school': 'School',
        'onboarding.type.warehouse': 'Warehouse',
        'onboarding.type.labour_camp': 'Labour Camp',
        'onboarding.type.gov_prop': 'Government Property',
        'onboarding.type.gov_majlis': 'Government Majlis',
        'onboarding.type.priv_majlis': 'Private Majlis',
        'onboarding.type.mixed_tower': 'Mixed-Use Tower',
        'onboarding.type.skyscraper': 'Skyscraper',
        'onboarding.type.stadium': 'Stadium',
        'onboarding.type.sports_complex': 'Sports Complex',
        'onboarding.type.event_venue': 'Event Venue',
        'onboarding.type.resort': 'Resort',
        'onboarding.type.industrial': 'Industrial Property',
        'onboarding.type.staff_acc': 'Staff Accommodation',
        'onboarding.type.farm': 'Farm / Estate',
        'onboarding.grade.standard': 'Standard',
        'onboarding.grade.premium': 'Premium',
        'onboarding.grade.luxury': 'Luxury',
        'onboarding.grade.sovereign': 'Sovereign',
        'onboarding.units': 'Units',
        'onboarding.floors': 'Floors',
        'onboarding.sqft': 'Sqft',
        'onboarding.age': 'Age (Yrs)',
        'onboarding.scan_btn': 'SCAN TITLE DEED (AUTO-FILL)',
        'onboarding.scanning': 'SCANNING DOCUMENT...',
        'onboarding.scanned': 'TITLE DEED VERIFIED',
        'onboarding.retry_scan': 'RETRY SCAN',
        'onboarding.continue': 'CONTINUE',
        'onboarding.emirate.dubai': 'Dubai',
        'onboarding.emirate.abudhabi': 'Abu Dhabi',
        'onboarding.emirate.sharjah': 'Sharjah',
        'onboarding.emirate.ajman': 'Ajman',
        'onboarding.emirate.ummalquwain': 'Umm Al Quwain',
        'onboarding.emirate.rasalkhaimah': 'Ras Al Khaimah',
        'onboarding.emirate.fujairah': 'Fujairah',
        'onboarding.location_manual': 'Manual Review Mode',
        'onboarding.location_manual_title': 'MANUAL LOCATION ENTRY',
        'onboarding.location_placeholder': 'Search for property address in UAE...',
        'onboarding.location_manual_info': 'Manual geo requires Administrative Review before technician dispatch.',
        'onboarding.systems_matrix': 'PROPERTY OPERATIONAL MATRIX',
        'onboarding.systems_audit': 'SYSTEMS AUDIT',
        'onboarding.initialize_analysis': 'INITIALIZE ANALYSIS',
        'onboarding.sys.core': 'CORE CLIMATE & FLOW',
        'onboarding.sys.safety': 'SAFETY & COMPLIANCE',
        'onboarding.sys.amenities': 'AMENITIES & SPECIALTY',
        'onboarding.sys.hvac': 'Central HVAC',
        'onboarding.sys.districtCooling': 'District Cooling',
        'onboarding.sys.tank': 'Water Tank / Pump',
        'onboarding.sys.gen': 'Emergency Generator',
        'onboarding.sys.lifts': 'Elevators / Lifts',
        'onboarding.sys.fireAlarm': 'Civil Defense Alarm',
        'onboarding.sys.firePump': 'Fire Suppression Pump',
        'onboarding.sys.sira': 'SIRA / CCTV System',
        'onboarding.sys.bmu': 'BMU / Cradle',
        'onboarding.sys.wasteMan': 'Waste Management',
        'onboarding.sys.pool': 'Swimming Pool',
        'onboarding.sys.gasSystem': 'Central Gas System',
        'onboarding.sys.greaseTrap': 'Grease Trap',
        'onboarding.sys.majlisGarden': 'Majlis Garden',
        'onboarding.sys.solarIntegration': 'Solar Integration',
        'onboarding.sys.evReadiness': 'EV Charging Station',
        'onboarding.commercial_title': 'COMMERCIAL TERMS 2026',
        'onboarding.commercial_desc': 'Finalize your contract type, service level, and payment frequency based on the 2026 UAE Matrix.',
        'onboarding.plan_select': 'CONTRACT SELECTION',
        'onboarding.plan.amc': 'Maintenance (AMC)',
        'onboarding.plan.amc_desc': 'Technical maintenance coverage for responsive repairs and asset integrity.',
        'onboarding.plan.pm': 'Property Management',
        'onboarding.plan.pm_desc': 'Tenant, rent, document and reporting operations for managed properties.',
        'onboarding.plan.ifm': 'Total Care (IFM)',
        'onboarding.plan.ifm_desc': 'Full operating visibility for owners who want maintenance and tenant service together.',
        'onboarding.sla_title': 'SLA PERFORMANCE TIER',
        'onboarding.sla.standard': 'STANDARD',
        'onboarding.sla.standard_desc': '4hr Emergency Response',
        'onboarding.sla.premium': 'PREMIUM',
        'onboarding.sla.premium_desc': '2hr Priority Response (+15%)',
        'onboarding.sla.elite': 'ELITE',
        'onboarding.sla.elite_desc': '1hr Dedicated Response (+30%)',
        'onboarding.payment_title': 'PAYMENT FREQUENCY',
        'onboarding.payment.annual': 'ANNUAL',
        'onboarding.payment.annual_desc': 'No surcharge',
        'onboarding.payment.quarterly': 'QUARTERLY',
        'onboarding.payment.quarterly_desc': '+3% Surcharge',
        'onboarding.payment.monthly': 'MONTHLY',
        'onboarding.payment.monthly_desc': '+6% Surcharge',
        'onboarding.quote_est': 'ESTIMATED ANNUAL QUOTE',
        'onboarding.mobilization': 'Mobilization Fee (15%)',
        'onboarding.vat_excl': 'Excl. 5% VAT',
        'onboarding.confirm_btn': 'CONFIRM & CONTINUE',
        'onboarding.revise_btn': 'REVISE PROPERTY DETAILS',
        'onboarding.docs_subtitle': 'Upload title deed/property proof and identity documents. Verified title deed data will override manual property fields after admin review.',
        'onboarding.docs_staged': 'Files are staged locally until account verification and final submission. Refreshing before submission requires reselecting files.',
        'onboarding.docs_required_count': 'Required documents staged',
        'onboarding.docs_max_size': 'PDF, JPG, PNG (Max 10MB)',
        'onboarding.docs_awaiting': 'Awaiting Selection...',
        'onboarding.docs_ready': 'Ready',
        'onboarding.docs_change': 'Change',
        'onboarding.docs_select': 'Select File',
        'onboarding.docs_continue': 'Continue to Verification',
        'onboarding.scanner_title': 'Title Deed Scanner',
        'onboarding.scanner_desc': 'This OCR node extracts authority fields from your title deed for institutional verification and property record locking.',
        'onboarding.scanner_analyzing': 'Analyzing...',
        'onboarding.scanner_analyze_btn': 'Analyze Property',
        'onboarding.scanner_retry': 'Retry Scan',
        'onboarding.scanner_extracted': 'EXTRACTED DATA (PRE-VERIFIED)',
        'onboarding.scanner_warning': 'Automated authority verification is not yet connected. This document will be marked for admin verification after submission.',
        'onboarding.scanner_confidence': 'Confidence Score',
        'onboarding.scanner_match': 'Match',
        'onboarding.review_title': 'REVIEW BEFORE SUBMIT',
        'onboarding.review_desc': 'Confirm your 2026 Sovereign Onboarding package.',
        'onboarding.review_info': 'System access and institutional dashboards remain locked until document verification and mobilization payment.',
        'onboarding.owner_company': 'OWNER & COMPANY',
        'onboarding.property_identity': 'PROPERTY IDENTITY',
        'onboarding.contract_perf': 'CONTRACT & PERFORMANCE',
        'onboarding.financial_recap': 'FINANCIAL RECAP',
        'onboarding.annual_val': 'Annual Contract Value',
        'onboarding.installment': 'Installment',
        'onboarding.mobilization_due': 'MOBILIZATION FEE DUE (15%)',
        'onboarding.risk_advisory': 'CRITICAL SYSTEM ADVISORY',
        'onboarding.finalize_btn': 'FINALIZE & PAY',
        'onboarding.payment_submission': 'PAYMENT & SUBMISSION',
        'onboarding.payment_confirm_desc': 'Confirm the selected protocol and submit for admin verification.',
        'onboarding.selected_contract': 'SELECTED CONTRACT',
        'onboarding.portfolio_addons': 'PORTFOLIO & ADD-ONS',
        'onboarding.total_assets': 'Total Assets',
        'onboarding.payment_method': 'Payment Method',
        'onboarding.bank_transfer': 'Bank Transfer',
        'onboarding.corp_cheque': 'Corporate Cheque',
        'onboarding.cash_payment': 'Cash Payment',
        'onboarding.admin_lock_title': 'ADMIN REVIEW LOCK',
        'onboarding.admin_lock_desc': 'Submission creates an intake, contract shell, and payment transaction. Live owner/property/unit records are only activated after admin approval.',
        'onboarding.submit_btn': 'SUBMIT ONBOARDING',
        'onboarding.submitting': 'SUBMITTING...',
        'onboarding.submission_secured': 'SUBMISSION SECURED',
        'onboarding.dashboard_locked_info': 'Your dashboard remains locked while admin verifies documents and the 15% mobilization payment.',
        'onboarding.admin_ids': 'ADMIN REVIEW IDS',
        'onboarding.go_dashboard': 'GO TO LOCKED DASHBOARD',
        'login.portal': 'PARTNER PORTAL',
        'login.authorized_only': 'Authorized client and partner access only.',
        'login.signin': 'SECURE SIGN IN',
        'login.google': 'SIGN IN WITH GOOGLE',
        'login.change_role': 'CHANGE ROLE',
        'login.email': 'Email Address',
        'login.password': 'Password',
        'login.get_started': 'GET STARTED',
        'gateway.role.owner': 'Owners',
        'gateway.role.tenant': 'Tenants',
        'gateway.role.technician': 'Technicians',
        'gateway.role.broker': 'Brokers',
        'gateway.role.security': 'Security',
        'gateway.login': 'LOGIN'
    },
    ar: {
        'admin.active_tenants': 'المستأجرون النشطون',
        'admin.active_tickets': 'التذاكر النشطة',
        'admin.amount': 'المبلغ',
        'admin.contract_ref': 'مرجع العقد',
        'admin.dashboard': 'لوحة تحكم المسؤول',
        'admin.system_health': 'صحة النظام',
        'admin.total_revenue': 'إجمالي الإيرادات',
        'analysis.efficiency': 'الكفاءة التشغيلية',
        'common.currency': 'درهم',
        'common.currency_aed': 'درهم',
        'dash.command_subtitle': 'التدقيق المؤسسي وواجهة المنطقة الوطنية',
        'dash.declined': 'مرفوض',
        'dash.kpi.net_roi': 'صافي العائد',
        'dash.proposed': 'مقترح',
        'dash.proposed_roi': 'العائد المقترح',
        'dash.realized_roi': 'العائد المحقق',
        'dash.risk_mitigation': 'تخفيف المخاطر',
        'dash.sanctioned': 'موافق عليه',
        'dash.sovereign_ai': 'الذكاء الاصطناعي السيادي',
        'fin.burn': 'المصروفات',
        'fin.income': 'الدخل',
        'fin.logs_title': 'سجلات الدفتر النظامي',
        'fin.log.date': 'التاريخ',
        'fin.log.status': 'الحالة',
        'fin.total_deductions': 'إجمالي الاستقطاعات',
        'landing.cta': 'سجل أصولك الآن ←',
        'landing.subtitle': 'مجموعة بن هي المنصة المؤسسية الرائدة في الإمارات لإدارة الأصول.',
        'landing.title': 'نظام التشغيل للعقارات في الإمارات.',
        'landing.transparency_title': 'شفافية النمو والمخاطر',
        'nav.admin': 'إدارة مجموعة بن',
        'nav.administry': 'الإدارة',
        'nav.audit': 'التدقيق المؤسسي',
        'nav.brokers': 'الوسطاء',
        'nav.dashboard': 'لوحة القيادة',
        'nav.financial': 'المالية',
        'nav.financials': 'الخزينة',
        'nav.live_map': 'الخريطة المباشرة',
        'nav.logout': 'تسجيل الخروج',
        'nav.onboarding': 'التسجيل',
        'nav.operations': 'العمليات',
        'nav.owner_portal_link': 'بوابة الملاك ↗',
        'nav.reports': 'التقارير',
        'nav.settings': 'سياسة الخصوصية',
        'nav.sos_feed': 'تغذية الاستغاثة',
        'nav.sovereign_core': 'النواة السيادية',
        'nav.support': 'الدعم',
        'nav.tech': 'فني',
        'nav.technicians': 'فيلق الفنيين',
        'nav.tenants': 'المستأجرون',
        'nav.tickets': 'سجلات المهام',
        'onboarding.payment.proceed_btn': 'الدخول للوحة القيادة',
        'onboarding.property_details': 'العقارات',
        'onboarding.title': 'التسجيل المؤسسي',
        'status.settled': 'تمت التسوية',
        'status.estimated': 'تم التقدير',
        'status.awaiting_owner_approval': 'بانتظار موافقة المالك',
        'status.approved': 'تمت الموافقة',
        'status.rejected': 'مرفوض',
        'status.revised_quote_sent': 'تم إرسال تسعيرة معدلة',
        'status.overdue_approval': 'موافقة متأخرة',
        'support.phone': 'الخط الساخن',
        'tech.active_tickets': 'الأخصائيون المعينون',
        'tech.ai_proposal': 'مقترحات بروتوكول الذكاء الاصطناعي',
        'onboarding.save_later': 'حفظ والمتابعة لاحقاً',
        'onboarding.institutional': 'التسجيل المؤسسي',
        'onboarding.back_website': 'العودة إلى الموقع',
        'onboarding.payment': 'الدفع',
        'onboarding.review': 'ملخص المراجعة',
        'onboarding.verification': 'التحقق',
        'onboarding.documents': 'المستندات',
        'onboarding.service_plan': 'خطة الخدمة',
        'onboarding.addons': 'الإضافات التشغيلية',
        'onboarding.systems': 'الأنظمة والخدمات',
        'onboarding.asset': 'الأصل',
        'onboarding.company': 'الشركة',
        'onboarding.location': 'الموقع',
        'onboarding.acc_creation': 'إنشاء الحساب',
        'onboarding.acc_creation_desc': 'أنشئ حساب دخول المالك بعد استكمال بيانات العقار والمستندات المطلوبة.',
        'onboarding.acc_creation_warning': 'سيبقى الوصول إلى لوحة التحكم مقفلاً حتى موافقة الإدارة والتحقق من دفعة التعبئة.',
        'onboarding.full_name': 'الاسم الكامل',
        'onboarding.mobile': 'رقم الهاتف',
        'onboarding.email': 'البريد الإلكتروني',
        'onboarding.password': 'كلمة المرور',
        'onboarding.confirm_password': 'تأكيد كلمة المرور',
        'onboarding.create_btn': 'إنشاء الحساب',
        'onboarding.back': 'رجوع',
        'onboarding.loading': 'جاري الإنشاء...',
        'onboarding.success_locked': 'تم إنشاء الحساب. سيبقى الوصول إلى لوحة التحكم مقفلاً حتى موافقة الإدارة والتحقق من دفعة التعبئة.',
        'onboarding.error.email_exists': 'هذا البريد الإلكتروني لديه حساب بالفعل. يرجى تسجيل الدخول أو استخدام إعادة تعيين كلمة المرور.',
        'onboarding.error.google_only': 'هذا البريد الإلكتروني مسجل عبر Google. يرجى المتابعة بتسجيل الدخول عبر Google.',
        'onboarding.error.role_conflict': 'هذا البريد الإلكتروني مسجل بالفعل تحت دور آخر. يرجى الاتصال بدعم مجموعة بن أو استخدام بريد إلكتروني مختلف للمالك.',
        'onboarding.company_profile': 'ملف الشركة',
        'onboarding.company_desc': 'قم بتأسيس هويتك المؤسسية داخل نظام تشغيل مجموعة بن السيادي.',
        'onboarding.company_name': 'اسم الشركة / الكيان',
        'onboarding.trade_license': 'رقم الرخصة التجارية (اختياري)',
        'onboarding.primary_contact': 'جهة الاتصال الرئيسية',
        'onboarding.contact_name': 'اسم الشخص المسؤول',
        'onboarding.contact_phone': 'هاتف التواصل',
        'onboarding.contact_email': 'البريد الإلكتروني للتواصل',
        'onboarding.onboard_btn': 'تسجيل عقارك الآن',
        'onboarding.asset_profile': 'ملف الأصل',
        'onboarding.asset_desc': 'حدد المعايير الفنية والتجارية لعقارك.',
        'onboarding.asset_name': 'اسم العقار / الأصل',
        'onboarding.asset_type': 'فئة الأصل',
        'onboarding.unit_count': 'إجمالي الوحدات',
        'onboarding.floor_count': 'إجمالي الطوابق',
        'onboarding.property_age': 'عمر العقار (بالسنوات)',
        'onboarding.systems_title': 'الأنظمة والخدمات',
        'onboarding.systems_desc': 'حدد الأنظمة الحيوية التي تتطلب صيانة وتدقيقاً مؤسسياً.',
        'onboarding.systems.hvac': 'التكييف المركزي',
        'onboarding.systems.elevators': 'أنظمة المصاعد',
        'onboarding.systems.fire': 'أنظمة الحريق والسلامة',
        'onboarding.systems.cctv': 'كاميرات المراقبة والأمن (سيرا)',
        'onboarding.systems.pool': 'حمامات السباحة / المرافق المائية',
        'onboarding.systems.generator': 'مولدات الاحتياط / الطاقة البديلة',
        'onboarding.location_title': 'موقع العقار',
        'onboarding.location_desc': 'حدد الإحداثيات الجغرافية لعمليات الإرسال الميداني.',
        'onboarding.emirate': 'الإمارة',
        'onboarding.zone': 'منطقة الخدمة',
        'onboarding.address': 'العنوان الفعلي',
        'onboarding.documents_title': 'مستندات الامتثال',
        'onboarding.documents_desc': 'تحميل سندات الملكية والشهادات الفنية المطلوبة.',
        'onboarding.doc.title_deed': 'سند الملكية / إثبات الملكية',
        'onboarding.doc.passport': 'جواز سفر المالك / الهوية الإماراتية',
        'onboarding.doc.license': 'الرخصة التجارية (للكيانات)',
        'onboarding.doc.mou': 'اتفاقية الإدارة / مذكرة التفاهم',
        'onboarding.service_plan_title': 'اختر خطة الخدمة',
        'onboarding.service_plan_desc': 'حدد مستوى التغطية المؤسسية لأصولك.',
        'onboarding.type.villa': 'فيلا',
        'onboarding.type.apartment': 'شقة',
        'onboarding.type.res_building': 'مبنى سكني',
        'onboarding.type.com_building': 'مبنى تجاري',
        'onboarding.type.office': 'مكتب',
        'onboarding.type.retail': 'مركز تجزئة',
        'onboarding.type.mall': 'مول / مركز تسوق',
        'onboarding.type.hotel': 'فندق',
        'onboarding.type.hospital': 'مستشفى',
        'onboarding.type.clinic': 'عيادة',
        'onboarding.type.school': 'مدرسة',
        'onboarding.type.warehouse': 'مستودع',
        'onboarding.type.labour_camp': 'سكن عمال',
        'onboarding.type.gov_prop': 'عقار حكومي',
        'onboarding.type.gov_majlis': 'مجلس حكومي',
        'onboarding.type.priv_majlis': 'مجلس خاص',
        'onboarding.type.mixed_tower': 'برج متعدد الاستخدامات',
        'onboarding.type.skyscraper': 'ناطحة سحاب',
        'onboarding.type.stadium': 'ملعب / ستاد',
        'onboarding.type.sports_complex': 'مجمع رياضي',
        'onboarding.type.event_venue': 'قاعة فعاليات',
        'onboarding.type.resort': 'منتجع',
        'onboarding.type.industrial': 'عقار صناعي',
        'onboarding.type.staff_acc': 'سكن موظفين',
        'onboarding.type.farm': 'مزرعة / عزبة',
        'onboarding.grade.standard': 'قياسي',
        'onboarding.grade.premium': 'مميز',
        'onboarding.grade.luxury': 'فاخر',
        'onboarding.grade.sovereign': 'سيادي',
        'onboarding.units': 'الوحدات',
        'onboarding.floors': 'الطوابق',
        'onboarding.sqft': 'قدم مربع',
        'onboarding.age': 'العمر (سنوات)',
        'onboarding.scan_btn': 'مسح سند الملكية (تعبئة تلقائية)',
        'onboarding.scanning': 'جاري مسح المستند...',
        'onboarding.scanned': 'تم التحقق من السند',
        'onboarding.retry_scan': 'إعادة المحاولة',
        'onboarding.continue': 'استمرار',
        'onboarding.emirate.dubai': 'دبي',
        'onboarding.emirate.abudhabi': 'أبوظبي',
        'onboarding.emirate.sharjah': 'الشارقة',
        'onboarding.emirate.ajman': 'عجمان',
        'onboarding.emirate.ummalquwain': 'أم القيوين',
        'onboarding.emirate.rasalkhaimah': 'رأس الخيمة',
        'onboarding.emirate.fujairah': 'الفجيرة',
        'onboarding.location_manual': 'وضع المراجعة اليدوية',
        'onboarding.location_manual_title': 'إدخال الموقع يدوياً',
        'onboarding.location_placeholder': 'ابحث عن عنوان العقار في الإمارات...',
        'onboarding.location_manual_info': 'يتطلب الموقع اليدوي مراجعة إدارية قبل إرسال الفنيين.',
        'onboarding.systems_matrix': 'مصفوفة التشغيل العقاري',
        'onboarding.systems_audit': 'تدقيق الأنظمة',
        'onboarding.initialize_analysis': 'بدء التحليل الفني',
        'onboarding.sys.core': 'المناخ والتدفق الأساسي',
        'onboarding.sys.safety': 'السلامة والامتثال',
        'onboarding.sys.amenities': 'المرافق والتخصصات',
        'onboarding.sys.hvac': 'التكييف المركزي',
        'onboarding.sys.districtCooling': 'تبريد المناطق',
        'onboarding.sys.tank': 'خزانات ومضخات المياه',
        'onboarding.sys.gen': 'مولدات الطوارئ',
        'onboarding.sys.lifts': 'المصاعد والرافعات',
        'onboarding.sys.fireAlarm': 'إنذار الدفاع المدني',
        'onboarding.sys.firePump': 'مضخات إخماد الحريق',
        'onboarding.sys.sira': 'نظام سيرا والمراقبة',
        'onboarding.sys.bmu': 'رافعات تنظيف الواجهات',
        'onboarding.sys.wasteMan': 'إدارة النفايات',
        'onboarding.sys.pool': 'حمام السباحة',
        'onboarding.sys.gasSystem': 'نظام الغاز المركزي',
        'onboarding.sys.greaseTrap': 'مصيدة الدهون',
        'onboarding.sys.majlisGarden': 'حديقة المجلس',
        'onboarding.sys.solarIntegration': 'تكامل الطاقة الشمسية',
        'onboarding.sys.evReadiness': 'محطة شحن السيارات الكهربائية',
        'onboarding.commercial_title': 'الشروط التجارية لعام 2026',
        'onboarding.commercial_desc': 'حدد نوع العقد ومستوى الخدمة ووتيرة الدفع بناءً على مصفوفة الإمارات لعام 2026.',
        'onboarding.plan_select': 'اختيار العقد',
        'onboarding.plan.amc': 'الصيانة (AMC)',
        'onboarding.plan.amc_desc': 'تغطية الصيانة الفنية للإصلاحات السريعة وسلامة الأصول.',
        'onboarding.plan.pm': 'إدارة العقارات',
        'onboarding.plan.pm_desc': 'عمليات المستأجرين والإيجارات والمستندات والتقارير.',
        'onboarding.plan.ifm': 'الرعاية الكاملة (IFM)',
        'onboarding.plan.ifm_desc': 'رؤية تشغيلية كاملة للملاك الذين يرغبون في الصيانة وخدمة المستأجرين معاً.',
        'onboarding.sla_title': 'فئة أداء مستوى الخدمة (SLA)',
        'onboarding.sla.standard': 'قياسي',
        'onboarding.sla.standard_desc': 'استجابة للطوارئ خلال 4 ساعات',
        'onboarding.sla.premium': 'مميز',
        'onboarding.sla.premium_desc': 'استجابة أولوية خلال ساعتين (+15%)',
        'onboarding.sla.elite': 'نخبة',
        'onboarding.sla.elite_desc': 'استجابة مخصصة خلال ساعة واحدة (+30%)',
        'onboarding.payment_title': 'وتيرة الدفع',
        'onboarding.payment.annual': 'سنوي',
        'onboarding.payment.annual_desc': 'بدون رسوم إضافية',
        'onboarding.payment.quarterly': 'ربع سنوي',
        'onboarding.payment.quarterly_desc': 'رسوم إضافية +3%',
        'onboarding.payment.monthly': 'شهري',
        'onboarding.payment.monthly_desc': 'رسوم إضافية +6%',
        'onboarding.quote_est': 'عرض السعر السنوي التقديري',
        'onboarding.mobilization': 'رسوم التعبئة (15%)',
        'onboarding.vat_excl': 'غير شامل ضريبة القيمة المضافة 5%',
        'onboarding.confirm_btn': 'تأكيد واستمرار',
        'onboarding.revise_btn': 'تعديل بيانات العقار',
        'onboarding.docs_subtitle': 'قم بتحميل سند الملكية وإثباتات الهوية. ستقوم بيانات سند الملكية التي تم التحقق منها باستبدال حقول العقار اليدوية بعد مراجعة المسؤول.',
        'onboarding.docs_staged': 'يتم تخزين الملفات محلياً حتى التحقق من الحساب والتقديم النهائي. إعادة تحميل الصفحة قبل التقديم تتطلب إعادة اختيار الملفات.',
        'onboarding.docs_required_count': 'المستندات المطلوبة المخزنة',
        'onboarding.docs_max_size': 'PDF, JPG, PNG (بحد أقصى 10 ميجابايت)',
        'onboarding.docs_awaiting': 'في انتظار الاختيار...',
        'onboarding.docs_ready': 'جاهز',
        'onboarding.docs_change': 'تغيير',
        'onboarding.docs_select': 'اختر ملف',
        'onboarding.docs_continue': 'المتابعة للتحقق',
        'onboarding.scanner_title': 'ماسح سند الملكية',
        'onboarding.scanner_desc': 'يقوم هذا النظام باستخراج الحقول الرسمية من سند الملكية للتحقق المؤسسي وقفل سجل العقار.',
        'onboarding.scanner_analyzing': 'جاري التحليل...',
        'onboarding.scanner_analyze_btn': 'تحليل العقار',
        'onboarding.scanner_retry': 'إعادة المحاولة',
        'onboarding.scanner_extracted': 'البيانات المستخرجة (تحقق أولي)',
        'onboarding.scanner_warning': 'التحقق الآلي من السلطات غير متصل بعد. سيتم تحديد هذا المستند للتحقق اليدوي بعد التقديم.',
        'onboarding.scanner_confidence': 'درجة الثقة',
        'onboarding.scanner_match': 'تطابق',
        'onboarding.review_title': 'مراجعة قبل التقديم',
        'onboarding.review_desc': 'تأكيد حزمة الانضمام السيادية لعام 2026.',
        'onboarding.review_info': 'تظل صلاحيات الوصول إلى النظام ولوحات المعلومات المؤسسية مغلقة حتى يتم التحقق من المستندات ودفع رسوم التعبئة.',
        'onboarding.owner_company': 'المالك والشركة',
        'onboarding.property_identity': 'هوية العقار',
        'onboarding.contract_perf': 'العقد والأداء',
        'onboarding.financial_recap': 'ملخص مالي',
        'onboarding.annual_val': 'قيمة العقد السنوية',
        'onboarding.installment': 'قسط',
        'onboarding.mobilization_due': 'رسوم التعبئة المستحقة (15%)',
        'onboarding.risk_advisory': 'تنبيه الأنظمة الحرجة',
        'onboarding.finalize_btn': 'إنهاء ودفع',
        'onboarding.payment_submission': 'الدفع والتقديم',
        'onboarding.payment_confirm_desc': 'تأكيد البروتوكول المختار والتقديم لمراجعة المسؤول.',
        'onboarding.selected_contract': 'العقد المختار',
        'onboarding.portfolio_addons': 'المحفظة والإضافات',
        'onboarding.total_assets': 'إجمالي الأصول',
        'onboarding.payment_method': 'طريقة الدفع',
        'onboarding.bank_transfer': 'تحويل بنكي',
        'onboarding.corp_cheque': 'شيك مؤسسي',
        'onboarding.cash_payment': 'دفع نقدي',
        'onboarding.admin_lock_title': 'قفل مراجعة المسؤول',
        'onboarding.admin_lock_desc': 'يؤدي التقديم إلى إنشاء طلب وعقد ومعاملة دفع. يتم تفعيل سجلات المالك/العقار/الوحدة فقط بعد موافقة المسؤول.',
        'onboarding.submit_btn': 'تقديم طلب الانضمام',
        'onboarding.submitting': 'جاري التقديم...',
        'onboarding.submission_secured': 'تم تأمين التقديم',
        'onboarding.dashboard_locked_info': 'تظل لوحة المعلومات الخاصة بك مغلقة بينما يقوم المسؤول بالتحقق من المستندات ودفع رسوم التعبئة بنسبة 15%.',
        'onboarding.admin_ids': 'معرفات مراجعة المسؤول',
        'onboarding.go_dashboard': 'الذهاب إلى لوحة المعلومات المغلقة',
        'login.portal': 'بوابة الشركاء',
        'login.authorized_only': 'دخول مخصص للعملاء والشركاء المعتمدين فقط',
        'login.signin': 'تسجيل دخول آمن',
        'login.google': 'تسجيل الدخول عبر Google',
        'login.change_role': 'تغيير الدور',
        'login.email': 'البريد الإلكتروني',
        'login.password': 'كلمة المرور',
        'login.get_started': 'ابدأ الآن',
        'gateway.role.owner': 'الملاك',
        'gateway.role.tenant': 'المستأجرون',
        'gateway.role.technician': 'الفنيون',
        'gateway.role.broker': 'الوسطاء',
        'gateway.role.security': 'الأمن',
        'gateway.login': 'تسجيل الدخول'
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [lang, setLang] = useState<Language>(() => {
        const saved = localStorage.getItem('app_lang');
        if (saved === 'en' || saved === 'ar') return saved as Language;
        return 'en';
    });

    useEffect(() => {
        localStorage.setItem('app_lang', lang);
        const dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.dir = dir;
        document.documentElement.dir = dir;
        document.body.dir = dir;
        document.documentElement.lang = lang;
    }, [lang]);

    const t = (key: string, variables?: Record<string, any>) => {
        let text = translations[lang]?.[key] || translations['en']?.[key] || key;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v));
            });
        }
        return text;
    };

    const tx = (key: string, fallback: string, variables?: Record<string, any>) => {
        const text = translations[lang]?.[key] || translations['en']?.[key];
        if (!text) return fallback;
        
        let result = text;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                result = result.replace(`{${k}}`, String(v));
            });
        }
        return result;
    };

    const isRTL = lang === 'ar';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, tx, isRTL }}>
            <Box 
                id="bin-app-root"
                dir={isRTL ? 'rtl' : 'ltr'}
                sx={{ 
                    direction: isRTL ? 'rtl' : 'ltr', 
                    minHeight: '100vh',
                    fontFamily: "'Cairo', 'Inter', sans-serif",
                    backgroundColor: '#020617',
                    color: '#fff'
                }}
            >
                {children}
            </Box>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
