import React, { createContext, useContext, useState, ReactNode, useEffect } from "react";
import { Box } from "@mui/material";

type Language = 'en' | 'ar';

interface LanguageContextType {
    lang: Language;
    setLang: (lang: Language) => void;
    t: (key: string, variables?: Record<string, any>) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.onboarding': 'Onboarding',
        'nav.financial': 'Financials',
        'nav.tech': 'Technician',
        'nav.admin': 'Sovereign Admin',
        'landing.title': 'The Operating System for UAE Real Estate.',
        'landing.subtitle': 'BIN GROUP covers and maintains all kinds of properties, including Government Majlis, Government Properties, Hotels, residential, commercial, towers, villas, mixed-use, and institutional assets.',
        'landing.cta': 'Onboard Your Asset →',
        'landing.partner_login': 'PARTNER LOGIN',
        'onboarding.title': 'Institutional Onboarding',
        'onboarding.description': 'BIN GROUP provides elite maintenance for all asset classes: Government Majlis, Government Properties, Hotels, Residential, Commercial, and Institutional nodes.',
        'onboarding.bulk_intake': 'Bulk Property Intake (1–500)',
        'onboarding.property_details': 'Property Details',
        'onboarding.analysis': 'Asset Analysis',
        'onboarding.quote': 'Sovereign Quote',
        'onboarding.payment': 'Activation',
        'onboarding.step.landing': 'Landing',
        'onboarding.step.intake': 'Property Intake',
        'onboarding.step.analysis': 'Asset Analysis',
        'onboarding.step.quote': 'Quote & Plan',
        'onboarding.step.selection': 'Contract Selection',
        'onboarding.step.tailoring': 'Service Tailoring',
        'onboarding.step.deposit': 'Security Deposit',
        'onboarding.step.activation': 'Account Selection',
        'step.intake': 'Property Intake',
        'step.analysis': 'Asset Analysis',
        'step.quote': 'Sovereign Quote',
        'step.tier': 'Contract Selection',
        'step.addons': 'Service Tailoring',
        'step.summary': 'Security Deposit',
        'step.account': 'Account Activation',
        'field.emirate': 'Emirate',
        'field.area': 'Area / Cluster',
        'field.type': 'Property Type',
        'field.subtype': 'Sub-Type',
        'field.usetype': 'Usage Type',
        'field.floors': 'Floors',
        'field.units': 'Units',
        'field.sqft': 'Square Footage',
        'field.age': 'Building Age',
        'field.lifts': 'Lifts',
        'field.pool': 'Pool',
        'field.tank': 'Water Tank',
        'field.sira': 'SIRA / CCTV',
        'field.fire': 'Fire Systems',
        'field.dist_cooling': 'District Cooling',
        'field.majlis': 'Government Majlis Protocol',
        'field.heritage': 'Heritage Sensitivity',
        'field.grade': 'Asset Grade',
        'field.status': 'Current Status',
        'majlis.government': 'Government Majlis',
        'property.rental': 'Rental Asset',
        'property.personal': 'Personal Use',
        'property.mixed': 'Mixed-Use / Hybrid',
        'property.gov': 'Government / Public',
        'summary.total_props': 'Total Properties',
        'summary.total_acv': 'Total Contract Value',
        'summary.tier': 'Recommended Tier',
        'toggle.language': 'العربية (AR)',
        'btn.next': 'Next',
        'btn.back': 'Back',
        'btn.add_prop': 'Add Property (+)',
        'btn.bulk_csv': 'Upload CSV',
        'btn.exit': 'Exit',
        'btn.quote': 'GET INSTITUTIONAL QUOTE',
        'status.tender_ready': 'TENDER READY',
        'status.sovereign': 'SOVEREIGN GRADE',
        'login.portal': 'PARTNER PORTAL',
        'login.auth_access': 'AUTHENTICATED INSTITUTIONAL ACCESS',
        'login.email': 'Access Email',
        'login.password': 'Secure Key (Password)',
        'login.signin': 'SECURE SIGN IN',
        'login.google': 'SIGN IN WITH GOOGLE',
        'button.next_asset_analysis': 'Next: Asset Analysis',
        'button.add_property': 'Add Property to Portfolio',
        'button.manual_entry': 'Manual Portfolio Entry',
        'button.bulk_csv': 'Bulk CSV Upload',
        'button.select_csv': 'Select CSV File',
        'intake.identification': 'Asset Identification & Sovereign Portfolio Setup',
        'dash.title': 'Portfolio Intelligence',
        'dash.terminal': 'Terminal',
        'dash.locked_assets': 'Locked Assets',
        'dash.onboard_cta': '+ ONBOARD NEW ASSET',
        'onboarding.payment.title': 'Institutional Portfolio Activation',
        'onboarding.payment.agreement_summary': 'Institutional Agreement Summary',
        'onboarding.payment.official_settlement': 'Official Settlement',
        'onboarding.payment.cheque': 'Cheque',
        'onboarding.payment.cash': 'Cash Deposit',
        'onboarding.payment.bank_transfer': 'Bank Transfer',
        'onboarding.payment.coming_soon': 'COMING SOON',
        'onboarding.payment.instructions': 'OFFICIAL SETTLEMENT INSTRUCTIONS',
        'onboarding.payment.due_now': '15% ACTIVATION DEPOSIT (DUE NOW)',
        'onboarding.payment.generate_manifest': 'Select a manual payment method to generate your institutional manifest.',
        'onboarding.payment.verifying': 'VERIFYING LEDGER...',
        'onboarding.payment.verify_btn': 'VERIFY PAYMENT STATUS',
        'onboarding.payment.change_method': 'Change Payment Method',
        'onboarding.payment.verified_title': 'SETTLEMENT VERIFIED',
        'onboarding.payment.verified_desc': 'Your activation deposit has been confirmed by the BIN-ADMINISTRY™.',
        'onboarding.payment.proceed_btn': 'PROCEED TO ACCOUNT LOCK',
        'onboarding.payment.secure_note': 'SOVEREIGN SECURE SETTLEMENT',
        'onboarding.payment.total_amc': 'TOTAL PORTFOLIO AMC',
        'onboarding.payment.vat_excl': 'VAT EXCL.',
        'onboarding.payment.appreciation_title': 'Asset Appreciation Multiplier',
        'onboarding.payment.appreciation_desc': 'By activating this contract, your portfolio qualifies for BIN-CERTIFIED™ status. Manual administrative settlement ensures sovereign-grade audit compliance for your institutional records.',
        'onboarding.payment.manifest_prefix': 'MANIFEST:',
        'onboarding.payment.cheque_desc': 'Cheques are verified within 2-3 business days.',
        'onboarding.payment.cash_desc': 'Please contact our office to schedule a cash deposit.',
        'onboarding.payment.portfolio_agreement': 'Service Agreement for Portfolio of {count} Mixed-Use Assets.',
        'onboarding.payment.base_amc': 'Base Annual Management Contract (AMC)',
        'onboarding.payment.generating_manifest': 'GENERATING DEPOSIT MANIFEST...',
        'onboarding.payment.awaiting_verification': 'Verification Pending: Awaiting Administrative Settlement.',
        'onboarding.payment.verified_success': 'PAYMENT VERIFIED: Institutional Registry Updated.',
        'onboarding.payment.verification_note': 'Verification Note',
        'onboarding.payment.contact_instruction': 'Contact Instruction',
        'onboarding.payment.initiation_desc': 'Once you have initiated the payment, our administrative team will verify the settlement.',
        'activation.title': 'SETTLEMENT VERIFIED',
        'activation.title_pending': 'SETTLEMENT PROVISIONING',
        'activation.subtitle': 'Provisioning Sovereign Infrastructure...',
        'activation.subtitle_pending': 'Binding identity to offline settlement manifest...',
        'activation.sovereign_access': 'SOVEREIGN ACCESS',
        'activation.benefit1.title': 'Real-time ROI Engine',
        'activation.benefit1.desc': 'Track institutional appreciation & asset integrity metrics live.',
        'activation.benefit2.title': 'Global BMS-Link™',
        'activation.benefit2.desc': 'Proprietary integration between our intelligence layers and your asset.',
        'activation.selected_contract': 'SELECTED ASSET CONTRACT',
        'activation.node_status': 'ACTIVE PORTFOLIO NODE',
        'activation.identity_creation': 'OWNER IDENTITY CREATION',
        'activation.pending_handshake': 'Pending Sovereign Handshake: Your contract identity is pending payment verification from the registry.',
        'activation.field.name': 'Full Corporate / Individual Name',
        'activation.field.name_placeholder': 'BIN-GROUP Holding L.L.C',
        'activation.field.name_helper': 'Ensure this matches your trade license or identity.',
        'activation.field.locked_helper': 'Protocol Locked: Verify payment to unlock identity binding.',
        'activation.field.portfolio_id': 'Primary Portfolio ID (Email)',
        'activation.field.encryption_guard': 'Secure Encryption Guard (Password)',
        'activation.field.contact_phone': 'Mission-Critical Contact (Phone)',
        'activation.btn.activate': 'ACTIVATE SOVEREIGN HUB',
        'activation.btn.awaiting': 'AWAITING PAYMENT',
        'activation.progress.establishing': 'Establishing Secure Link...',
        'activation.progress.encryption': 'Generating encryption keys and linking mission-critical property BMS assets.',
        'activation.progress.sync': 'BIN-IDENTITY™ SYNC: PROXY LAYER 4',
        'activation.error.name': 'Sovereign Protocol: Please enter a valid Corporate or Individual Name (3-50 characters).',
        'activation.error.credentials': 'Profile Error: Missing identity credentials.',
        'activation.error.phone': 'Identity Alert: Invalid UAE Contact Format. Use +971-50-XXX-XXXX.',
        'activation.error.contract_id': 'Sovereign Protocol Error: Missing Contract ID.',
        'activation.error.payment_failed': 'SECURITY ALERT: Payment verification failed in registry. Cannot provision account.',
        'activation.info.existing_detected': '💎 [SOVEREIGN-RECOGNITION] Existing Portfolio Detected. Verifying credentials...',
        'activation.error.existing_rejection': 'RECOGNITION_FAILED: Credentials rejected for existing sovereign profile.',
        'activation.error.generic': 'Provisioning Error: {message}',
        'dash.kpi.gross_val': 'GROSS CONTRACT VALUE',
        'dash.kpi.annual_yield': 'ANNUAL YIELD (EST)',
        'dash.kpi.radius': 'PORTFOLIO RADIUS',
        'dash.kpi.majlis_readiness': 'INSTITUTIONAL READINESS',
        'dash.kpi.net_roi': 'NET ROI',
        'field.property': 'Property',
        'field.usage': 'Usage',
        'common.action': 'Action',
        'common.assets': 'ASSETS',
        'common.asset': 'Asset',
        'onboarding.csv_helper': 'Maximum 500 properties per upload. Schema must match BIN-GENESIS Template.',
        'onboarding.asset_details': 'Asset Details',
        'onboarding.asset_scale': 'Asset Scale & Composition',
        'onboarding.majlis_profile': 'Government Majlis Profile',
        'onboarding.fm_systems': 'Essential FM Systems',
        'onboarding.portfolio_intel': 'PORTFOLIO INTELLIGENCE',
        'onboarding.mixed_use_alert': 'MIXED-USE ASSET DETECTED',
        'onboarding.mixed_use_helper': 'Engine will apply differential maintenance rates for Offices, Shops & Pools.',
        'onboarding.sovereign_protocol': 'GOVERNMENT MAJLIS PROTOCOL',
        'onboarding.sovereign_helper': 'Mandatory Civil Defense & SIRA audits included in base contract.',
        'onboarding.audit_log': 'BIN-GENESIS™ AUDIT LOG',
        'onboarding.verifying_assets': 'Verifying {count} assets against municipal records...',
        'onboarding.normalization_active': 'Asset grade normalization active: {tier}',
        'summary.total_units': 'Total Units / Assets',
        'summary.total_sqft': 'Total SqFt Managed',
        'type.residential': 'Residential',
        'type.commercial': 'Commercial',
        'type.mixed': 'Mixed-Use Tower / Development',
        'type.institutional': 'Institutional (Hospital/School)',
        'type.majlis': 'Government Majlis',
        'type.govt_property': 'Government Property',
        'type.hotel': 'Hotel / Hospitality',
        'grade.standard': 'Standard',
        'grade.premium': 'Premium',
        'grade.luxury': 'Luxury',
        'grade.ultra': 'Ultra-Luxury',
        'grade.sovereign': 'Sovereign / Government',
        'field.shops': 'Retail Shops',
        'field.offices': 'Offices',
        'field.serviced_rooms': 'Serviced Rooms',
        'field.civil_defense': 'Civil Defense Alarm',
        'field.district_cooling': 'District Cooling',
        'field.solar': 'Solar Power',
        'field.ev': 'EV Charging',
        'dash.kpi.gross_roi': 'GROSS ROI',
        'dash.kpi.esg': 'SOVEREIGN ESG',
        'dash.kpi.compliance': 'COMPLIANCE SCORE',
        'dash.kpi.integrity': 'ASSET INTEGRITY',
        'dash.kpi.satisfaction': 'TENANT SATISFACTION',
        'dash.ledger': 'ASSET LEDGER',
        'dash.alerts': 'SOVEREIGN ALERTS',
        'dash.command_deck': 'SOVEREIGN ASSET COMMAND',
        'dash.command_subtitle': 'Institutional Grade Auditing & National Zone Interface',
        'dash.empty_title': 'PORTFOLIO OFFLINE',
        'dash.empty_subtitle': 'You have no active bin-group institutional service contracts. Begin your sovereign asset onboarding to unlock live monitoring.',
        'dash.empty_cta': '+ START ASSET ONBOARDING',
        'sos.btn': 'TRIGGER SOS DISPATCH',
        'sos.title': 'SOS Dispatch',
        'sos.subtitle': 'Report critical infrastructure failures for immediate institutional restoration.',
        'sos.success_title': 'DISPATCH TRIGGERED',
        'sos.success_subtitle': 'Sovereign response team notified. A verified technician will arrive within **4 HOURS** (SLA Protocol Alpha).',
        'tech.service_node': 'Service Node',
        'tech.subtitle': 'Live maintenance grid and sovereign asset restoration.',
        'tech.mission_dispatch': 'MISSION DISPATCH',
        'tech.active_tickets': 'ACTIVE TICKETS',
        'tech.kpi.mttr': 'MTTR (AVG)',
        'tech.kpi.sla': 'SLA COMPLIANCE',
        'tech.kpi.uptime': 'ZONE UPTIME',
        'tech.trend.live': 'LIVE',
        'tech.trend.optimal': 'OPTIMAL',
        'tech.trend.sovereign': 'SOVEREIGN',
        'tech.trend.stable': 'STABLE',
        'tech.protocol': 'PROTOCOL ALPHA-4',
        'tech.priority.normal': 'NORMAL',
        'tech.priority.emergency': 'EMERGENCY',
        'tech.status_tracking': 'STATUS TRACKING',
        'tech.open_node': 'OPEN NODE',
        'tech.empty': 'No active mission dispatches in this sector.',
        'tech.unknown_unit': 'Unknown Unit',
        'sos.emergency_protocol': 'EMERGENCY PROTOCOL',
        'sos.fault_category': 'FAULT CATEGORY',
        'sos.mission_description': 'MISSION DESCRIPTION',
        'sos.description_placeholder': 'Provide unit details and fault specifics...',
        'sos.attach_evidence': 'ATTACH VISUAL EVIDENCE',
        'sos.trigger_btn': 'TRIGGER DISPATCH',
        'sos.cat.ac': 'AC / HVAC CRITICAL FAILURE',
        'sos.cat.plumbing': 'MAJOR PLUMBING / FLOODING',
        'sos.cat.electrical': 'ELECTRICAL SHORT / BLACKOUT',
        'sos.cat.security': 'SECURITY / ACCESS BREACH',
        'sos.return_dash': 'RETURN TO DASHBOARD',
        'broker.title': 'Broker Ledger',
        'broker.subtitle': 'Sovereign asset distribution and high-yield inventory.',
        'broker.list_new': '+ LIST NEW ASSET',
        'broker.kpi.inventory': 'TOTAL INVENTORY',
        'broker.kpi.leads': 'ACTIVE LEADS',
        'broker.kpi.market': 'MARKET APPRECIATION',
        'broker.kpi.commission': 'COMMISSION INDEX',
        'broker.listings': 'PREMIUM LISTINGS',
        'broker.unit_type': 'SOVEREIGN UNIT',
        'broker.yield_label': 'YIELD',
        'broker.details': 'DETAILS',
        'landing.hero_title_line1': 'INSTITUTIONAL ASSET',
        'landing.hero_title_line2': 'INTELLIGENCE',
        'landing.feature.risk_title': 'SIRA & CD Compliance',
        'landing.feature.risk_desc': 'Automated risk audits for institutional safety.',
        'landing.feature.maintenance_title': 'Precision Maintenance',
        'landing.feature.maintenance_desc': 'Predictive lifecycle management for high-risk systems.',
        'landing.feature.yield_title': 'Yield Maximization',
        'landing.feature.yield_desc': 'Data-driven strategy for GCC asset holders.',
        'landing.footer': '© 2026 BIN GROUP | ARCHITECTED FOR THE SEVEN EMIRATES',
        'login.or_sso': 'OR INSTITUTIONAL SSO',
        'login.iso_secure': 'ISO 27001 SECURE',
        'login.inst_grade': 'INSTITUTIONAL GRADE',
        'login.uae_ops': 'UAE PORTFOLIO OPS',
        'login.footer': '© 2026 BIN-GROUP UAE. UNAUTHORIZED ACCESS IS MONITORED.',
        'common.system': 'SYSTEM',
        'analysis.log_init': 'Initializing BIN-GENESIS™ Portfolio Scanner...',
        'analysis.log_batch': 'Batch processing {count} asset identities...',
        'analysis.log_benchmarks': 'Mapping Community Benchmarks across Emirates...',
        'analysis.log_mixed': 'Differential maintenance logic applied for Mixed-Use units...',
        'analysis.log_compliance': 'Cross-checking SIRA & Civil Defense mandatory missions...',
        'analysis.log_volume': 'Applying Institutional Volume efficiency multipliers...',
        'analysis.log_volume_institutional': 'Applying institutional rate card for Government & Hospitality nodes...',
        'analysis.log_vault': 'Securing data via Sovereign Vault Archive...',
        'analysis.log_complete': 'Portfolio modeling complete.',
        'analysis.synthesizing': 'Synthesizing institutional data for {count} properties...',
        'analysis.classified': 'PORTFOLIO CLASSIFIED',
        'analysis.grade_assets': '{tier} GRADE ASSETS',
        'analysis.scale': 'PORTFOLIO SCALE',
        'analysis.managed_area': 'Managed Area',
        'analysis.composition': 'ASSET COMPOSITION',
        'analysis.efficiency': 'EFFICIENCY GAIN',
        'analysis.efficiency_desc': 'Applied volume discount based on institutional portfolio scale. Verified against BIN-GENESIS™ benchmarks.',
        'fin.title': 'Financial Ledger',
        'fin.subtitle': 'Institutional yield auditing and sovereign liquidity gateways.',
        'fin.export_btn': 'EXPORT AUDIT',
        'fin.kpi.total_collection': 'TOTAL ASSET COLLECTION',
        'fin.kpi.sovereign_payout': 'SOVEREIGN PAYOUT',
        'fin.kpi.pending_liquidity': 'PENDING LIQUIDITY',
        'fin.kpi.overdue_deficit': 'OVERDUE DEFICIT',
        'fin.deductions_title': 'DEDUCTIONS BREAKDOWN',
        'fin.deduction.fee': 'BIN-GROUP MANAGEMENT FEE (5%)',
        'fin.deduction.fee_desc': 'Institutional oversight and service guarantee.',
        'fin.deduction.maint': 'MAINTENANCE INVOICES (OFFSET)',
        'fin.deduction.maint_desc': 'Non-contractual mission repairs and parts.',
        'fin.deduction.turnover': 'TURNOVER ENGINE COSTS',
        'fin.deduction.turnover_desc': 'Deep-clean and asset restoration cycles.',
        'fin.total_deductions': 'TOTAL INSTITUTIONAL DEDUCTIONS',
        'fin.trends_title': 'COLLECTION TRENDS',
        'fin.advance_title': 'ANNUAL ADVANCE',
        'fin.advance_desc': 'Unlock your **Full Year\'s Portfolio Liquidity** instantly. Zero-wait interface to institutional banking bridges.',
        'fin.advance_btn': 'ACTIVATE LIQUIDITY BRIDGE',
        'fin.logs_title': 'SETTLEMENT LOGS',
        'fin.log.date': 'DATE',
        'fin.log.hash': 'TRANSACTION HASH',
        'fin.log.amount': 'AMOUNT',
        'fin.log.status': 'STATUS',
        'fin.log.empty': 'No transactions found in this protocol. Portfolio ledger is empty.',
        'fin.export_success': 'Institutional Audit Ledger exported to CSV.',
        'fin.bridge_pending': 'Institutional Bridge Status: Connection pending final banking partner authorization.',
        'status.settled': 'SETTLED',
        'status.pending': 'PENDING',
        'dash.mission_feed': 'MISSION FEED',
        'dash.listening': 'Listening for mission-critical protocol alerts...',
        'dash.hash_anchor': 'SOVEREIGN HASH ANCHOR',
        'dash.municipality_adapter': 'MUNICIPALITY ADAPTER',
        'dash.risk_grade': 'INSURER RISK GRADE',
        'dash.gateway_status': 'GATEWAY STATUS',
        'dash.audit_btn': 'GENERATE INSTITUTIONAL AUDIT',
        'dash.sync_btn': 'SYNC WITH NATIONAL GATEWAY',
        'contract.govt_majlis.title': 'GOVERNMENT MAJLIS MAINTENANCE & PROTOCOL AGREEMENT',
        'contract.govt_majlis.body': 'This agreement covers elite maintenance and VIP protocol readiness for the Government Majlis. BIN GROUP ensures 24/7 readiness, heritage sensitivity management, and specialized HVAC/hospitality support. All services are governed by Sovereign Protocol Alpha-4.',
        'contract.govt_property.title': 'GOVERNMENT PROPERTY COMPREHENSIVE FM CONTRACT',
        'contract.govt_property.body': 'This contract provides comprehensive Facility Management for Government Properties, focusing on departmental compliance, security integration, and multi-tenant operational efficiency. Scope includes Civil Defense, SIRA, and municipal health & safety certification.',
        'contract.hotel.title': 'HOSPITALITY MAINTENANCE & OPERATIONS AGREEMENT',
        'contract.hotel.body': 'Specialized FM for Hotel assets, including guest-facing systems, 24/7 technical support, pool/spa maintenance, and back-of-house complexity management. Includes guest-readiness audits and critical infrastructure lifecycle monitoring.',
        'contract.standard.title': 'MASTER SERVICE AGREEMENT',
        'contract.standard.body': 'This Master Service Agreement covers general maintenance and FM services for residential, commercial, and mixed-use properties. Scope includes preventive maintenance, reactive call-outs, and basic compliance management.',
    },
    ar: {
        'nav.dashboard': 'لوحة التحكم',
        'nav.onboarding': 'التهيئة',
        'nav.financial': 'المالية',
        'nav.tech': 'فني',
        'nav.admin': 'إدارة سيادية',
        'landing.title': 'نظام التشغيل للعقارات في الإمارات.',
        'landing.subtitle': 'تغطي مجموعة بن وتصون جميع أنواع العقارات، بما في ذلك المجالس الحكومية، والعقارات الحكومية، والفنادق، والعقارات السكنية، والتجارية، والأبراج، والفلل، والمجمعات متعددة الاستخدامات، والأصول المؤسسية.',
        'landing.cta': 'ابدأ تهيئة أصولك ←',
        'landing.partner_login': 'تسجيل دخول الشركاء',
        'onboarding.title': 'التهيئة المؤسسية',
        'onboarding.description': 'توفر مجموعة بن صيانة متميزة لجميع فئات الأصول: المجالس الحكومية، والعقارات الحكومية، والفنادق، والعقارات السكنية، والتجارية، والعقد المؤسسية.',
        'onboarding.bulk_intake': 'إدخال العقارات بالجملة (1-500)',
        'onboarding.property_details': 'تفاصيل العقار',
        'onboarding.analysis': 'تحليل الأصول',
        'onboarding.quote': 'عرض سعر سيادي',
        'onboarding.payment': 'التفعيل',
        'onboarding.step.landing': 'البداية',
        'onboarding.step.intake': 'إدخال العقارات',
        'onboarding.step.analysis': 'تحليل الأصول',
        'onboarding.step.quote': 'عرض السعر والخطة',
        'onboarding.step.selection': 'اختيار العقد',
        'onboarding.step.tailoring': 'تخصيص الخطة',
        'onboarding.step.deposit': 'مبلغ التأمين',
        'onboarding.step.activation': 'اختيار الحساب',
        'step.intake': 'إدخال العقارات',
        'step.analysis': 'تحليل الأصول',
        'step.quote': 'عرض سعر سيادي',
        'step.tier': 'اختيار العقد',
        'step.addons': 'تخصيص الخدمة',
        'step.summary': 'مبلغ التأمين',
        'step.account': 'تفعيل الحساب',
        'field.emirate': 'الإمارة',
        'field.area': 'المنطقة / التجمع',
        'field.type': 'نوع العقار',
        'field.subtype': 'النوع الفرعي',
        'field.usetype': 'نوع الاستخدام',
        'field.floors': 'الطوابق',
        'field.units': 'الوحدات',
        'field.sqft': 'المساحة بالقدم المربع',
        'field.age': 'عمر البناء',
        'field.lifts': 'المصاعد',
        'field.pool': 'مسبح',
        'field.tank': 'خزان مياه',
        'field.sira': 'سيرا / كاميرات المراقبة',
        'field.fire': 'أنظمة الحريق',
        'field.dist_cooling': 'تبريد المناطق',
        'field.majlis': 'بروتوكول المجلس الحكومي',
        'field.heritage': 'حساسية التراث',
        'field.grade': 'درجة الأصول',
        'field.status': 'الوضع الحالي',
        'majlis.government': 'مجلس حكومي',
        'property.rental': 'أصل إيجاري',
        'property.personal': 'استخدام شخصي',
        'property.mixed': 'استخدام مختلط / هجين',
        'property.gov': 'حكومي / عام',
        'summary.total_props': 'إجمالي العقارات',
        'summary.total_acv': 'إجمالي قيمة العقد',
        'summary.tier': 'الفئة الموصى بها',
        'toggle.language': 'English (EN)',
        'btn.next': 'التالي',
        'btn.back': 'رجوع',
        'btn.add_prop': 'إضافة عقار (+)',
        'btn.bulk_csv': 'تحميل CSV',
        'status.tender_ready': 'جاهز للمناقصة',
        'status.sovereign': 'درجة سيادية',
        'dash.title': 'استخبارات المحفظة',
        'dash.terminal': 'محطة',
        'dash.locked_assets': 'أصول مقفلة',
        'dash.onboard_cta': '+ إضافة أصل جديد',
        'dash.kpi.gross_val': 'إجمالي قيمة العقد',
        'dash.kpi.annual_yield': 'العائد السنوي (تقديري)',
        'dash.kpi.radius': 'نطاق المحفظة',
        'dash.kpi.majlis_readiness': 'الجاهزية المؤسسية',
        'dash.kpi.net_roi': 'صافي العائد على الاستثمار',
        'dash.kpi.gross_roi': 'إجمالي العائد على الاستثمار',
        'dash.kpi.esg': 'الحوكمة البيئية والاجتماعية السيادية',
        'dash.kpi.compliance': 'درجة الامتثال',
        'dash.kpi.integrity': 'سلامة الأصول',
        'dash.kpi.satisfaction': 'رضا المستأجرين',
        'dash.ledger': 'سجل الأصول',
        'dash.alerts': 'تنبيهات سيادية',
        'dash.command_deck': 'قيادة الأصول السيادية',
        'dash.command_subtitle': 'التدقيق المؤسسي وواجهة المنطقة الوطنية',
        'dash.empty_title': 'المحفظة غير متصلة',
        'dash.empty_subtitle': 'ليس لديك عقود خدمة مؤسسية نشطة مع مجموعة بن. ابدأ تهيئة أصولك لفتح المراقبة المباشرة.',
        'dash.empty_cta': '+ ابدأ تهيئة الأصول',
        'sos.btn': 'تفعيل إرسال الاستغاثة',
        'sos.title': 'إرسال استغاثة (SOS)',
        'sos.subtitle': 'الإبلاغ عن أعطال البنية التحتية الحرجة للترميم المؤسسي الفوري.',
        'sos.success_title': 'تم تفعيل الإرسال',
        'sos.success_subtitle': 'تم إخطار فريق الاستجابة السيادي. سيصل فني معتمد خلال **4 ساعات** (بروتوكول اتفاقية مستوى الخدمة ألفا).',
        'tech.service_node': 'عقدة الخدمة',
        'tech.subtitle': 'شبكة الصيانة المباشرة وترميم الأصول السيادية.',
        'tech.mission_dispatch': 'إرسال المهمة',
        'tech.active_tickets': 'التذاكر النشطة',
        'tech.kpi.mttr': 'متوسط وقت الإصلاح',
        'tech.kpi.sla': 'الالتزام باتفاقية الخدمة',
        'tech.kpi.uptime': 'جاهزية المنطقة',
        'tech.trend.live': 'مباشر',
        'tech.trend.optimal': 'مثالي',
        'tech.trend.sovereign': 'سيادي',
        'tech.trend.stable': 'مستقر',
        'tech.protocol': 'بروتوكول ألفا-4',
        'tech.priority.normal': 'عادي',
        'tech.priority.emergency': 'طوارئ',
        'tech.status_tracking': 'تتبع الحالة',
        'tech.open_node': 'فتح العقدة',
        'tech.empty': 'لا توجد مهمات نشطة في هذا القطاع.',
        'tech.unknown_unit': 'وحدة غير معروفة',
        'sos.emergency_protocol': 'بروتوكول الطوارئ',
        'sos.fault_category': 'فئة العطل',
        'sos.mission_description': 'وصف المهمة',
        'sos.description_placeholder': 'يرجى تقديم تفاصيل الوحدة ووصف العطل...',
        'sos.attach_evidence': 'إرفاق دليل مرئي',
        'sos.trigger_btn': 'تفعيل الإرسال',
        'sos.cat.ac': 'عطل حرج في التكييف',
        'sos.cat.plumbing': 'عطل كبير في السباكة / فيضان',
        'sos.cat.electrical': 'ماس كهربائي / انقطاع تيار',
        'sos.cat.security': 'خرق أمني / دخول غير مصرح',
        'sos.return_dash': 'العودة إلى لوحة التحكم',
        'broker.title': 'سجل الوسيط',
        'broker.subtitle': 'توزيع الأصول السيادية والمخزون عالي العائد.',
        'broker.list_new': '+ إدراج أصل جديد',
        'broker.kpi.inventory': 'إجمالي المخزون',
        'broker.kpi.leads': 'العملاء المهتمون',
        'broker.kpi.market': 'تقدير السوق',
        'broker.kpi.commission': 'مؤشر العمولات',
        'broker.listings': 'العقارات المميزة',
        'broker.unit_type': 'وحدة سيادية',
        'broker.yield_label': 'العائد',
        'broker.details': 'التفاصيل',
        'landing.hero_title_line1': 'استخبارات الأصول',
        'landing.hero_title_line2': 'المؤسسية',
        'landing.feature.risk_title': 'الامتثال لـ SIRA و CD',
        'landing.feature.risk_desc': 'تدقيق تلقائي للمخاطر لسلامة المؤسسات.',
        'landing.feature.maintenance_title': 'صيانة دقيقة',
        'landing.feature.maintenance_desc': 'إدارة دورة الحياة التنبؤية للأنظمة عالية المخاطر.',
        'landing.feature.yield_title': 'تعظيم العائد',
        'landing.feature.yield_desc': 'استراتيجية مدفوعة بالبيانات لأصحاب الأصول في الخليج.',
        'landing.footer': '© 2026 مجموعة بن الإمارات | هندست للإمارات السبع',
        'login.or_sso': 'أو الدخول الموحد للمؤسسات',
        'login.iso_secure': 'آمن بمعيار ISO 27001',
        'login.inst_grade': 'درجة مؤسسية',
        'login.uae_ops': 'عمليات المحفظة في الإمارات',
        'login.footer': '© 2026 مجموعة بن الإمارات. الدخول غير المصرح به مراقب.',
        'common.system': 'النظام',
        'analysis.log_init': 'جاري تهيئة ماسح المحفظة BIN-GENESIS™...',
        'analysis.log_batch': 'جاري معالجة {count} من هويات الأصول...',
        'analysis.log_benchmarks': 'رسم خرائط المعايير المجتمعية عبر الإمارات...',
        'analysis.log_mixed': 'تطبيق منطق الصيانة التفاضلية للوحدات مختلطة الاستخدام...',
        'analysis.log_compliance': 'مراجعة مهام SIRA والدفاع المدني الإلزامية...',
        'analysis.log_volume': 'تطبيق مضاعفات كفاءة الحجم المؤسسي...',
        'analysis.log_volume_institutional': 'تطبيق بطاقة الأسعار المؤسسية للعقد الحكومية والضيافة...',
        'analysis.log_vault': 'تأمين البيانات عبر أرشيف الخزنة السيادية...',
        'analysis.log_complete': 'اكتملت نمذجة المحفظة.',
        'analysis.synthesizing': 'توليف البيانات المؤسسية لـ {count} عقار...',
        'analysis.classified': 'تم تصنيف المحفظة',
        'analysis.grade_assets': 'أصول من فئة {tier}',
        'analysis.scale': 'نطاق المحفظة',
        'analysis.managed_area': 'المساحة المدارة',
        'analysis.composition': 'تكوين الأصول',
        'analysis.efficiency': 'مكاسب الكفاءة',
        'analysis.efficiency_desc': 'تم تطبيق خصم الحجم بناءً على نطاق المحفظة المؤسسية. تم التحقق منه مقابل معايير BIN-GENESIS™.',
        'fin.title': 'السجل المالي',
        'fin.subtitle': 'تدقيق العائد المؤسسي وبوابات السيولة السيادية.',
        'fin.export_btn': 'تصدير التدقيق',
        'fin.kpi.total_collection': 'إجمالي تحصيل الأصول',
        'fin.kpi.sovereign_payout': 'الصرف السيادي',
        'fin.kpi.pending_liquidity': 'السيولة المعلقة',
        'fin.kpi.overdue_deficit': 'العجز المتأخر',
        'fin.deductions_title': 'تفاصيل الاستقطاعات',
        'fin.deduction.fee': 'رسوم إدارة مجموعة بن (5%)',
        'fin.deduction.fee_desc': 'الرقابة المؤسسية وضمان الخدمة.',
        'fin.deduction.maint': 'فواتير الصيانة (مقاصة)',
        'fin.deduction.maint_desc': 'إصلاحات وقطع غيار غير تعاقدية.',
        'fin.deduction.turnover': 'تكاليف محرك التدفق',
        'fin.deduction.turnover_desc': 'دورات التنظيف العميق واستعادة الأصول.',
        'fin.total_deductions': 'إجمالي الاستقطاعات المؤسسية',
        'fin.trends_title': 'اتجاهات التحصيل',
        'fin.advance_title': 'دفعة سنوية مقدمة',
        'fin.advance_desc': 'قم بفتح **سيولة محفظتك لعام كامل** فوراً. واجهة بدون انتظار لجسور الخدمات المصرفية المؤسسية.',
        'fin.advance_btn': 'تفعيل جسر السيولة',
        'fin.logs_title': 'سجلات التسوية',
        'fin.log.date': 'التاريخ',
        'fin.log.hash': 'رمز المعاملة',
        'fin.log.amount': 'المبلغ',
        'fin.log.status': 'الحالة',
        'fin.log.empty': 'لم يتم العثور على معاملات في هذا البروتوكول. سجل المحفظة فارغ.',
        'fin.export_success': 'تم تصدير سجل التدقيق المؤسسي إلى CSV.',
        'fin.bridge_pending': 'حالة الجسر المؤسسي: الاتصال معلق بانتظار التفويض النهائي من الشريك المصرفي.',
        'status.settled': 'تمت التسوية',
        'status.pending': 'قيد الانتظار',
        'dash.mission_feed': 'تغذية المهمة',
        'dash.listening': 'جاري الاستماع لتنبيهات البروتوكول الحرجة...',
        'dash.hash_anchor': 'مرساة التجزئة السيادية',
        'dash.municipality_adapter': 'محول البلدية',
        'dash.risk_grade': 'درجة مخاطر المؤمن',
        'dash.gateway_status': 'حالة البوابة',
        'dash.audit_btn': 'إنشاء تدقيق مؤسسي',
        'dash.sync_btn': 'مزامنة مع البوابة الوطنية',
        'field.property': 'العقار',
        'field.usage': 'الاستخدام',
        'common.action': 'الإجراء',
        'common.assets': 'أصول',
        'common.asset': 'أصل',
        'onboarding.csv_helper': 'الحد الأقصى 500 عقار لكل تحميل. يجب أن يتطابق المخطط مع قالب BIN-GENESIS.',
        'onboarding.asset_details': 'تفاصيل الأصول',
        'onboarding.asset_scale': 'حجم وتكوين الأصول',
        'onboarding.majlis_profile': 'ملف المجلس الحكومي',
        'onboarding.fm_systems': 'أنظمة إدارة المرافق الأساسية',
        'onboarding.portfolio_intel': 'استخبارات المحفظة',
        'onboarding.mixed_use_alert': 'تم اكتشاف أصول متعددة الاستخدامات',
        'onboarding.mixed_use_helper': 'سيطبق المحرك معدلات صيانة تفاضلية للمكاتب والمحلات التجارية والمسابح.',
        'onboarding.sovereign_protocol': 'بروتوكول المجلس الحكومي',
        'onboarding.sovereign_helper': 'عمليات تدقيق الدفاع المدني و SIRA الإلزامية مدرجة في العقد الأساسي.',
        'onboarding.audit_log': 'سجل تدقيق BIN-GENESIS™',
        'onboarding.verifying_assets': 'جاري التحقق من {count} أصل مقابل السجلات البلدية...',
        'onboarding.normalization_active': 'تطبيع درجة الأصول نشط: {tier}',
        'summary.total_units': 'إجمالي الوحدات / الأصول',
        'summary.total_sqft': 'إجمالي المساحة المدارة (قدم مربع)',
        'type.residential': 'سكني',
        'type.commercial': 'تجاري',
        'type.mixed': 'برج / تطوير متعدد الاستخدامات',
        'type.institutional': 'مؤسسي (مستشفى / مدرسة)',
        'type.majlis': 'مجلس حكومي',
        'type.govt_property': 'عقار حكومي',
        'type.hotel': 'فندق / ضيافة',
        'grade.standard': 'قياسي',
        'grade.premium': 'ممتاز',
        'grade.luxury': 'فاخر',
        'grade.ultra': 'فائق الفخامة',
        'grade.sovereign': 'سيادي / حكومي',
        'field.shops': 'محلات التجزئة',
        'field.offices': 'مكاتب',
        'field.serviced_rooms': 'غرف مخدمة',
        'field.civil_defense': 'إنذار الدفاع المدني',
        'field.district_cooling': 'تبريد المناطق',
        'field.solar': 'طاقة شمسية',
        'field.ev': 'شحن سيارات كهربائية',
        'onboarding.payment.title': 'تفعيل المحفظة المؤسسية',
        'onboarding.payment.agreement_summary': 'ملخص الاتفاقية المؤسسية',
        'onboarding.payment.official_settlement': 'التسوية الرسمية',
        'onboarding.payment.cheque': 'شيك',
        'onboarding.payment.cash': 'إيداع نقدي',
        'onboarding.payment.bank_transfer': 'تحويل مصرفي',
        'onboarding.payment.coming_soon': 'قريباً',
        'onboarding.payment.instructions': 'تعليمات التسوية الرسمية',
        'onboarding.payment.due_now': 'إيداع التفعيل بنسبة 15% (مستحق الآن)',
        'onboarding.payment.generate_manifest': 'اختر طريقة دفع يدوية لإنشاء بيان الإيداع المؤسسي الخاص بك.',
        'onboarding.payment.verifying': 'جاري التحقق من السجل...',
        'onboarding.payment.verify_btn': 'التحقق من حالة الدفع',
        'onboarding.payment.change_method': 'تغيير طريقة الدفع',
        'onboarding.payment.verified_title': 'تم التحقق من التسوية',
        'onboarding.payment.verified_desc': 'تم تأكيد إيداع التفعيل الخاص بك من قبل إدارة مجموعة بن.',
        'onboarding.payment.proceed_btn': 'المتابعة لقفل الحساب',
        'onboarding.payment.secure_note': 'تسوية سيادية آمنة',
        'onboarding.payment.total_amc': 'إجمالي عقد الصيانة السنوي للمحفظة',
        'onboarding.payment.vat_excl': 'غير شامل ضريبة القيمة المضافة',
        'onboarding.payment.appreciation_title': 'مضاعف تقدير الأصول',
        'onboarding.payment.appreciation_desc': 'من خلال تفعيل هذا العقد، تتأهل محفظتك للحصول على وضع BIN-CERTIFIED™. تضمن التسوية الإدارية اليدوية الامتثال لتدقيق الدرجة السيادية لسجلاتك المؤسسية.',
        'onboarding.payment.manifest_prefix': 'البيان:',
        'onboarding.payment.cheque_desc': 'يتم التحقق من الشيكات خلال 2-3 أيام عمل.',
        'onboarding.payment.cash_desc': 'يرجى الاتصال بمكتبنا لتحديد موعد للإيداع النقدي.',
        'onboarding.payment.portfolio_agreement': 'اتفاقية خدمة لمحفظة مكونة من {count} أصل مختلط الاستخدام.',
        'onboarding.payment.base_amc': 'عقد الصيانة السنوي الأساسي (AMC)',
        'onboarding.payment.generating_manifest': 'جاري إنشاء بيان الإيداع...',
        'onboarding.payment.awaiting_verification': 'في انتظار التحقق: بانتظار التسوية الإدارية.',
        'onboarding.payment.verified_success': 'تم التحقق من الدفع: تم تحديث السجل المؤسسي.',
        'onboarding.payment.verification_note': 'ملاحظة التحقق',
        'onboarding.payment.contact_instruction': 'تعليمات التواصل',
        'onboarding.payment.initiation_desc': 'بمجرد بدء عملية الدفع، سيقوم فريقنا الإداري بالتحقق من التسوية.',
        'activation.title': 'تم التحقق من التسوية',
        'activation.title_pending': 'تزويد التسوية',
        'activation.subtitle': 'جاري تهيئة البنية التحتية السيادية...',
        'activation.subtitle_pending': 'ربط الهوية ببيان التسوية اليدوية...',
        'activation.sovereign_access': 'الوصول السيادي',
        'activation.benefit1.title': 'محرك العائد على الاستثمار في الوقت الفعلي',
        'activation.benefit1.desc': 'تتبع التقدير المؤسسي ومقاييس سلامة الأصول مباشرة.',
        'activation.benefit2.title': 'Global BMS-Link™',
        'activation.benefit2.desc': 'تكامل حصري بين طبقات الاستخبارات لدينا وأصولك.',
        'activation.selected_contract': 'عقد الأصول المختار',
        'activation.node_status': 'عقدة المحفظة النشطة',
        'activation.identity_creation': 'إنشاء هوية المالك',
        'activation.pending_handshake': 'في انتظار المصافحة السيادية: هوية عقدك معلقة بانتظار التحقق من الدفع من السجل.',
        'activation.field.name': 'الاسم الكامل للشركة / الفرد',
        'activation.field.name_placeholder': 'مجموعة بن القابضة ذ.م.م',
        'activation.field.name_helper': 'تأكد من مطابقة ذلك لرخصتك التجارية أو هويتك.',
        'activation.field.locked_helper': 'البروتوكول مقفل: تحقق من الدفع لفتح ربط الهوية.',
        'activation.field.portfolio_id': 'معرف المحفظة الأساسي (البريد الإلكتروني)',
        'activation.field.encryption_guard': 'حارس التشفير الآمن (كلمة المرور)',
        'activation.field.contact_phone': 'جهة اتصال المهام الحرجة (الهاتف)',
        'activation.btn.activate': 'تفعيل المركز السيادي',
        'activation.btn.awaiting': 'بانتظار الدفع',
        'activation.progress.establishing': 'جاري إنشاء ارتباط آمن...',
        'activation.progress.encryption': 'جاري إنشاء مفاتيح التشفير وربط أصول BMS العقارية ذات المهام الحرجة.',
        'activation.progress.sync': 'مزامنة BIN-IDENTITY™: طبقة الوكيل 4',
        'activation.error.name': 'البروتوكول السيادي: يرجى إدخال اسم شركة أو فرد صالح (3-50 حرفاً).',
        'activation.error.credentials': 'خطأ في الملف الشخصي: بيانات الاعتماد مفقودة.',
        'activation.error.phone': 'تنبيه الهوية: تنسيق الاتصال في الإمارات غير صالح. استخدم +971-50-XXX-XXXX.',
        'activation.error.contract_id': 'خطأ في البروتوكول السيادي: معرف العقد مفقود.',
        'activation.error.payment_failed': 'تنبيه أمني: فشل التحقق من الدفع في السجل. لا يمكن تزويد الحساب.',
        'activation.info.existing_detected': '💎 [التعرف السيادي] تم اكتشاف محفظة موجودة. جاري التحقق من بيانات الاعتماد...',
        'activation.error.existing_rejection': 'فشل التعرف: تم رفض بيانات الاعتماد للملف السيادي الموجود.',
        'activation.error.generic': 'خطأ في التزويد: {message}',
    }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
    const [lang, setLangState] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            return (localStorage.getItem('app_lang') as Language) || 'en';
        }
        return 'en';
    });

    const setLang = (newLang: Language) => {
        setLangState(newLang);
        if (typeof window !== 'undefined') {
            localStorage.setItem('app_lang', newLang);
            document.dir = newLang === 'ar' ? 'rtl' : 'ltr';
        }
    };

    useEffect(() => {
        if (typeof window !== 'undefined') {
            document.dir = lang === 'ar' ? 'rtl' : 'ltr';
        }
    }, [lang]);

    const t = (key: string, variables?: Record<string, any>) => {
        let text = translations[lang][key] || key;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v));
            });
        }
        return text;
    };
    const isRTL = lang === 'ar';

    return (
        <LanguageContext.Provider value={{ lang, setLang, t, isRTL }}>
            <div 
                dir={isRTL ? 'rtl' : 'ltr'}
                style={{ 
                    direction: isRTL ? 'rtl' : 'ltr', 
                    minHeight: '100vh',
                    fontFamily: "'Cairo', 'Inter', sans-serif",
                    backgroundColor: '#000',
                    color: '#fff'
                }}
            >
                {children}
            </div>
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error("useLanguage must be used within a LanguageProvider");
    }
    return context;
}
