import React, { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { Box } from "@mui/material";

type Language = 'en' | 'ar';

interface LanguageContextType {
    lang: Language;
    language: Language;          // alias for lang — used by portal apps
    setLang: (lang: Language) => void;
    toggleLanguage: () => void;  // convenience toggle — used by portal apps
    t: (key: string, variables?: Record<string, any>) => string;
    tx: (key: string, fallback: string, variables?: Record<string, any>) => string;
    isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.dashboard': 'Dashboard',
        'nav.onboarding': 'Onboarding',
        'nav.financial': 'Financials',
        'nav.tech': 'Technician',
        'nav.admin': 'BIN-Groups Admin',
        'nav.tenants': 'Tenants',
        'nav.tickets': 'Mission Logs',
        'nav.financials': 'Treasury',
        'nav.audit': 'Institutional Audit',
        'nav.brokers': 'Brokers',
        'nav.settings': 'Privacy Policy',
        'nav.live_map': 'Live Map',
        'nav.sos_feed': 'SOS Feed',
        'nav.reports': 'Reports',
        'nav.logout': 'Logout',
        'nav.login': 'Login',
        'nav.get_started': 'Get Started',
        'nav.admin_user': 'Admin User',
        'nav.version_info': 'v1.0.0 | Go-Go-Live: Jun 6, 2026',
        'nav.admin_panel_title': 'BIN-ADMINISTRY™ Command',
        'nav.sovereign_core': 'SOVEREIGN CORE',
        'nav.operations': 'OPERATIONS',
        'nav.support': 'Support',
        'nav.owner_portal_link': 'Owner Portal ↗',
        'nav.administry': 'ADMINISTRY',
        'landing.title': 'The Operating System for UAE Real Estate.',
        'landing.subtitle': 'BIN GROUP is the UAE\'s premier institutional asset management platform. We solve the complexity of large-scale property operations by unifying tenant management, predictive maintenance, and sovereign data compliance.',
        'landing.hero_title_line1': 'BINCONSTRUCTION™',
        'landing.hero_title_line2': 'SOVEREIGN MAINTENANCE',
        'landing.cta': 'Onboard Your Asset →',
        'landing.partner_login': 'PARTNER LOGIN',
        'landing.mission_overline': 'INSTITUTIONAL MISSION',
        'landing.mission_title': 'Institutional Mission',
        'landing.mission_desc': 'To establish the gold standard for property maintenance and construction in the UAE, ensuring every asset—from government councils to private estates—reflects the nation\'s vision for institutional excellence.',
        'landing.about_overline': 'CORPORATE PROFILE',
        'landing.about_title': 'Premium Sovereignty',
        'landing.about_desc': 'As a sovereign-aligned entity, we specialize in the high-stakes maintenance of government assets, heritage sites, and elite residential portfolios, delivering uncompromising technical precision and institutional security.',
        'landing.contact_title': 'Institutional Correspondence',
        'landing.email': 'Ceo@bin-groups.com',
        'landing.phone': '+971 55 242 3233',
        'landing.address': 'United Arab Emirates',
        'ai.image_upload_failed': 'Image upload failed. Please retry or choose another image.',
        'onboarding.ocr_scanner_busy': 'Scanner node busy or document unclear. Please fill data manually or retry.',
        'landing.sectors_title': 'Sectors We Master',
        'landing.sector.govt_title': 'Government & Sovereign',
        'landing.sector.govt_desc': 'Institutional-grade maintenance for Majlis, Ministries, and Federal assets with specialized protocol readiness.',
        'landing.sector.luxury_title': 'Luxury Hospitality',
        'landing.sector.luxury_desc': 'Preserving the gold standard for UAE’s elite hotel portfolios and ultra-luxury private residences.',
        'landing.sector.infra_title': 'Critical Infrastructure',
        'landing.sector.infra_desc': 'Technical support for logistics nodes, district cooling systems, and high-stakes commercial centers.',
        'landing.about_us': 'About Us',
        'landing.contact_us': 'Contact Us',
        'landing.support': 'Support',
        'landing.get_quote': 'Get Quote',
        'landing.who_we_are': 'Who We Are',
        'landing.who_we_are_desc': 'BIN GROUP is a UAE-based institutional powerhouse dedicated to the lifecycle management of premium and sovereign assets. We represent the intersection of advanced engineering and national data security.',
        'landing.what_we_do': 'What We Do',
        'landing.what_we_do_desc': 'From predictive maintenance for government Majlis to structural retrofitting for luxury towers, we provide the technical infrastructure that keeps the UAE\'s most valuable assets operational.',
        'landing.why_choose_us': 'Why BIN GROUP?',
        'landing.why_choose_us_desc': 'We are the only platform in the region that guarantees 100% data sovereignty on UAE soil while providing military-grade maintenance SLAs.',
        'landing.how_it_works': 'How It Works',
        'landing.how_it_works_desc': 'Onboard your portfolio, receive an institutional-grade audit, and deploy our specialized technician corps via our centralized command terminal.',
        'landing.hero_onboard_cta': 'Onboard Premium Asset',
        'landing.solve_title': 'The Headache Solved',
        'landing.solve_subtitle': 'We eliminate the friction of traditional maintenance, moving at the speed of your portfolio.',
        'landing.zero_friction': 'Zero Friction',
        'landing.zero_friction_desc': 'No manual coordination. Everything from ticketing to invoicing is digitally handled within the Sovereign OS.',
        'landing.gps_dispatch': 'Real-Time GPS Dispatch',
        'landing.gps_dispatch_desc': 'Watch your service order fulfill in real-time. Our technicians are dispatched immediately via GPS routing.',
        'landing.auto_financials': 'Automated Financials',
        'landing.auto_financials_desc': 'Rental yields and maintenance fees are routed through mathematically precise automated protocols.',
        'landing.transparency': '100% Transparency',
        'landing.transparency_desc_v2': 'Immutable portfolio tracking. No hidden costs. No administrative delays. Just absolute visibility.',
        'landing.deployment_title': 'MISSION DEPLOYMENT CAPABILITIES',
        'landing.elite_infra': 'Elite Infrastructure Maintenance',
        'landing.executive_access': 'Direct Executive Access',
        'landing.executive_desc': 'Institutional Partnerships require direct communication. For high-value asset onboarding or regional collaboration, connect directly with our leadership.',
        'landing.whatsapp_ceo': 'WhatsApp CEO (0552423233)',
        'landing.registered_trademark': 'Registered Trademark • UAE Nationwide Operations',
        'landing.sign_in_dash': 'Sign In to Dashboard',
        'landing.auth_authorize': 'AUTHORIZE ACCESS',
        'landing.identity_verify': 'Verify Identity',
        'landing.secure_global': 'SECURE GLOBAL VERIFICATION',
        'onboarding.title': 'Institutional Onboarding',
        'onboarding.location_title': 'PROPERTY LOCATION',
        'onboarding.location_desc': 'Pinpoint the geographical coordinates for operational dispatch.',
        'onboarding.location_placeholder': 'Search for property address in UAE...',
        'onboarding.location_manual': 'Manual Review Mode',
        'onboarding.location_manual_title': 'MANUAL LOCATION ENTRY',
        'onboarding.location_manual_info': 'Manual geo requires Administrative Review before technician dispatch.',
        'onboarding.description': 'BIN GROUP provides elite maintenance for all asset classes: Government Majlis, Government Properties, Hotels, Residential, Commercial, and Institutional nodes.',
        'onboarding.bulk_intake': 'Bulk Property Intake (1–500)',
        'onboarding.analysis': 'Asset Analysis',
        'onboarding.quote': 'BIN-Groups Quote',
        'onboarding.payment': 'Activation',
        'step.intake': 'Property Intake',
        'step.analysis': 'Asset Analysis',
        'step.quote': 'BIN-Groups Quote',
        'step.tier': 'Contract Selection',
        'step.addons': 'Add-Ons',
        'step.summary': 'Security Deposit',
        'step.account': 'Account Activation',
        'step.type': 'Property Type',
        'step.location': 'Location',
        'step.data': 'Building Data',
        'step.systems': 'Systems & Services',
        'step.contract': 'Contract Selection',
        'step.terms': 'Payment Terms',
        'step.review': 'Review Summary',
        'step.submit': 'Final Activation',
        'onboarding.systems_audit': 'CRITICAL SYSTEMS AUDIT',
        'onboarding.property_operational_matrix': 'PROPERTY OPERATIONAL MATRIX',
        'onboarding.systems_desc': 'Declare institutional systems for lifecycle modeling and SLA compliance.',
        'onboarding.addons_title': 'OPERATIONAL ADD-ONS',
        'onboarding.addons_subtitle': 'SELECT ADD-ON SERVICES',
        'onboarding.addons_desc': 'Mission-critical service layers tailored to your specific asset type and regulatory requirements.',
        'onboarding.total_annual': 'TOTAL ANNUAL',
        'onboarding.selected_addons': 'SELECTED ADD-ONS',
        'onboarding.sovereign_stack': 'SOVEREIGN STACK',
        'onboarding.mandatory': 'MANDATORY',
        'onboarding.reason': 'REASON',
        'onboarding.annual': 'ANNUAL',
        'onboarding.back_to_models': 'BACK TO MODELS',
        'field.emirate': 'Emirate',
        'field.area': 'Area / Cluster',
        'field.type': 'Property Type',
        'field.subtype': 'Sub-Type',
        'field.usetype': 'Usage Type',
        'field.floors': 'Floors',
        'field.units': 'Units',
        'field.sqft': 'Square Footage',
        'field.age': 'Building Age',
        'field.lifts': 'Lifts',
        'field.pool': 'Pool',
        'field.tank': 'Water Tank',
        'field.sira': 'SIRA / CCTV',
        'field.fire': 'Fire Systems',
        'field.dist_cooling': 'District Cooling',
        'field.majlis': 'Government Majlis Protocol',
        'field.heritage': 'Heritage Sensitivity',
        'field.grade': 'Asset Grade',
        'field.status': 'Current Status',
        'btn.next': 'Next',
        'btn.back': 'Back',
        'btn.add_prop': 'Add Property (+)',
        'btn.bulk_csv': 'Upload CSV',
        'btn.exit': 'Exit',
        'btn.quote': 'GET INSTITUTIONAL QUOTE',
        'status.sovereign': 'BIN-GROUPS GRADE',
        'login.portal': 'PARTNER PORTAL',
        'login.auth_access': 'AUTHENTICATED INSTITUTIONAL ACCESS',
        'login.email': 'Email Address',
        'login.password': 'Password',
        'login.signin': 'SECURE SIGN IN',
        'login.google': 'SIGN IN WITH GOOGLE',
        'login.or_sso': 'OR INSTITUTIONAL SSO',
        'login.forgot_password': 'Forgot Password',
        'login.iso_secure': 'ISO 27001 SECURE',
        'login.iso_secure_badge': 'ISO 27001 Certified & Sovereign Secured',
        'login.inst_grade': 'INSTITUTIONAL GRADE',
        'login.uae_ops': 'UAE PORTFOLIO OPS',
        'login.footer': '© 2026 BIN-GROUP UAE. UNAUTHORIZED ACCESS IS MONITORED.',
        'login.authorized_only': 'Authorized client and partner access only.',
        'gateway.title': 'Select Your Operational Node',
        'gateway.subtitle': 'Enter the BIN GROUP Sovereign OS via your authorized role.',
        'gateway.role.owner': 'Continue as Owner',
        'gateway.role.tenant': 'Continue as Tenant',
        'gateway.role.technician': 'Continue as Technician',
        'gateway.role.broker': 'Continue as Broker',
        'gateway.role.admin': 'Continue as Admin',
        'dash.title': 'Portfolio Intelligence',
        'dash.terminal': 'Terminal',
        'dash.locked_assets': 'Locked Assets',
        'dash.onboard_cta': '+ ONBOARD NEW ASSET',
        'dash.kpi.gross_val': 'GROSS CONTRACT VALUE',
        'dash.kpi.annual_yield': 'ANNUAL YIELD (EST)',
        'dash.kpi.radius': 'PORTFOLIO RADIUS',
        'dash.kpi.majlis_readiness': 'INSTITUTIONAL READINESS',
        'dash.kpi.net_roi': 'NET ROI',
        'dash.kpi.gross_roi': 'GROSS ROI',
        'dash.kpi.esg': 'SOVEREIGN ESG',
        'dash.kpi.compliance': 'COMPLIANCE SCORE',
        'dash.kpi.integrity': 'ASSET INTEGRITY',
        'dash.kpi.satisfaction': 'TENANT SATISFACTION',
        'dash.kpi.trend.live': 'LIVE',
        'dash.kpi.trend.active': 'ACTIVE',
        'dash.kpi.trend.optimal': 'OPTIMAL',
        'dash.ledger': 'ASSET LEDGER',
        'dash.asset_node': 'ASSET NODE',
        'dash.health_index': 'HEALTH INDEX',
        'dash.annual_amc': 'ANNUAL AMC',
        'dash.protocol_status': 'PROTOCOL STATUS',
        'dash.private_asset': 'Private Asset',
        'dash.alerts': 'SOVEREIGN ALERTS',
        'dash.intel.deck': 'SOVEREIGN INTELLIGENCE DECK',
        'dash.intel.forecast': 'AI FORECAST',
        'dash.intel.integrity_decay': 'INTEGRITY DECAY',
        'dash.intel.horizon': '12-MONTH HORIZON',
        'dash.intel.projected_yield': 'PROJECTED YIELD',
        'dash.intel.annualized_net': 'ANNUALIZED NET',
        'dash.intel.guidance_title': 'STRATEGIC MISSION GUIDANCE',
        'dash.intel.protocol_commands': 'SOVEREIGN PROTOCOL COMMANDS',
        'dash.intel.download_audit': 'DOWNLOAD INTEGRITY AUDIT (PDF)',
        'dash.intel.generating_audit': 'GENERATING SOVEREIGN AUDIT...',
        'dash.command_deck': 'SOVEREIGN ASSET COMMAND',
        'dash.command_subtitle': 'Institutional Grade Auditing & National Zone Interface',
        'dash.empty_title': 'PORTFOLIO OFFLINE',
        'dash.empty_subtitle': 'You have no active bin-group institutional service contracts. Begin your sovereign asset onboarding to unlock live monitoring.',
        'dash.empty_cta': '+ START ASSET ONBOARDING',
        'dash.mission_feed': 'MISSION FEED',
        'dash.listening': 'Listening for mission-critical protocol alerts...',
        'dash.hash_anchor': 'SOVEREIGN HASH ANCHOR',
        'dash.municipality_adapter': 'MUNICIPALITY ADAPTER',
        'dash.risk_grade': 'INSURER RISK GRADE',
        'dash.gateway_status': 'GATEWAY STATUS',
        'dash.audit_btn': 'GENERATE INSTITUTIONAL AUDIT',
        'dash.sync_btn': 'MANUAL SYNC',
        'dash.status.optimal': 'P.1 (OPTIMAL)',
        'dash.status.stable': 'P.2 (STABLE)',
        'sos.btn': 'TRIGGER SOS DISPATCH',
        'sos.title': 'SOS Dispatch',
        'sos.subtitle': 'Report critical infrastructure failures for immediate institutional restoration.',
        'sos.success_title': 'DISPATCH TRIGGERED',
        'sos.success_subtitle': 'Mission parameters received. V4 Geo-Engine is routing your request.',
        'sos.emergency_protocol': 'EMERGENCY PROTOCOL',
        'sos.fault_category': 'FAULT CATEGORY',
        'sos.mission_description': 'MISSION DESCRIPTION',
        'sos.description_placeholder': 'Provide unit details and fault specifics...',
        'sos.attach_evidence': 'ATTACH VISUAL EVIDENCE',
        'sos.trigger_btn': 'TRIGGER DISPATCH',
        'sos.cat.ac': 'AC / HVAC CRITICAL FAILURE',
        'sos.cat.plumbing': 'MAJOR PLUMBING / FLOODING',
        'sos.cat.electrical': 'ELECTRICAL SHORT / BLACKOUT',
        'sos.cat.security': 'SECURITY / ACCESS BREACH',
        'sos.return_dash': 'RETURN TO DASHBOARD',
        'sos.location_locked': 'MISSION LOCATION LOCKED',
        'sos.timing_label': 'Preferred Timing',
        'sos.asap': 'ASAP (Emergency)',
        'sos.morning': 'Morning (8AM - 12PM)',
        'sos.afternoon': 'Afternoon (12PM - 4PM)',
        'sos.evening': 'Evening (4PM - 8PM)',
        'sos.photo_attached': 'Photo Attached',
        'sos.attach_photo': 'Attach Photo Proof',
        'tech.service_node': 'Service Node',
        'tech.subtitle': 'Live maintenance grid and sovereign asset restoration.',
        'tech.mission_dispatch': 'MISSION DISPATCH',
        'tech.kpi.mttr': 'MTTR (AVG)',
        'tech.kpi.sla': 'SLA COMPLIANCE',
        'tech.kpi.uptime': 'ZONE UPTIME',
        'tech.trend.live': 'LIVE',
        'tech.trend.optimal': 'OPTIMAL',
        'tech.trend.sovereign': 'SOVEREIGN',
        'tech.trend.stable': 'STABLE',
        'tech.protocol': 'PROTOCOL ALPHA-4',
        'tech.priority.normal': 'NORMAL',
        'tech.priority.emergency': 'EMERGENCY',
        'tech.status_tracking': 'STATUS TRACKING',
        'tech.open_node': 'OPEN NODE',
        'tech.empty': 'No active mission dispatches in this sector.',
        'tech.unknown_unit': 'Unknown Unit',
        'tech.status.live': 'LIVE',
        'tech.status.syncing': 'SYNCING',
        'tech.live_ops': 'LIVE OPERATIONS',
        'tech.urgent_dispatch': 'URGENT DISPATCH',
        'tech.navigate': 'NAVIGATE',
        'tech.mission_brief': 'MISSION BRIEF',
        'tech.enable_alerts': 'ENABLE ALERTS',
        'tech.alerts_on': 'ALERTS ACTIVE',
        'tech.missions': 'Missions',
        'tech.hr_duty': 'HR & Duty',
        'tech.mission_pool': 'Mission Pool',
        'tech.pool_id': 'POOL ID',
        'tech.accept': 'Accept',
        'tech.notif_handshake_success': 'SUCCESS: Sovereign Notification Channel Established.',
        'tech.notif_link': 'Notification Link',
        'tech.notif_ios_pwa': 'Required for emergency dispatches on iOS PWAs.',
        'tech.notif_active': 'DISPATCH LINK ACTIVE',
        'tech.notif_enable': 'Enable Push Notifications',
        'tech.duty_sync': 'Duty Synchronization',
        'tech.duty_subtitle': 'Set your availability for the automated dispatch engine.',
        'tech.on_duty': 'ON DUTY',
        'tech.off_duty': 'OFF DUTY',
        'tech.workload_node': 'Workload Node',
        'tech.standard_hours': 'Standard Hours (This Week)',
        'tech.reward_unlocked': 'SOVEREIGN REWARD UNLOCKED',
        'tech.vacation_unlocked': 'Congratulations! You have unlocked your 35-Day Annual Vacation.',
        'tech.action.start_duty': 'START DUTY',
        'tech.action.end_duty': 'END DUTY',
        'tech.action.take_break': 'TAKE BREAK',
        'tech.action.resume_duty': 'RESUME DUTY',
        'tech.action.accept_job': 'ACCEPT MISSION',
        'tech.action.en_route': 'EN ROUTE',
        'tech.action.arrived': 'I HAVE ARRIVED',
        'tech.action.start_work': 'START MISSION',
        'tech.action.complete': 'FINALIZE MISSION',
        'tech.status.working': 'WORKING',
        'tech.status.break': 'ON BREAK',
        'tech.status.off': 'OFF DUTY',
        'tech.protocol.before_photo': 'BEFORE PHOTO',
        'tech.protocol.after_photo': 'AFTER PHOTO',
        'tech.protocol.signature': 'TENANT SIGNATURE',
        'tech.protocol.notes': 'MISSION NOTES',
        'tech.protocol.required': 'PROTOCOL VIOLATION: Full Evidence Required.',
        'tech.protocol.success': 'MISSION SYNCED TO SOVEREIGN VAULT',
        'footer.home': 'Home',
        'footer.privacy': 'Privacy Policy',
        'footer.terms': 'Terms of Service',
        'footer.support': 'Institutional Support',
        'footer.copyright': '© 2026 BINCONSTRUCTION™ UAE. ALL RIGHTS RESERVED.',
        'common.system': 'SYSTEM',
        'common.sys_init_fault': 'SYSTEM INITIALIZATION FAULT',
        'common.reload_sys': 'RELOAD SYSTEM',
        'common.auth_sync': 'Authenticating BIN-Groups Identity...',
        'common.identity_fault': 'IDENTITY FAULT',
        'common.role_error_prefix': 'Role Authorization Error:',
        'status.owner': 'Owner',
        'common.asset': 'Asset',
        'status.pending': 'Pending',
        'status.open': 'Open',
        'status.assigned': 'Assigned',
        'status.en_route': 'En Route',
        'status.arrived': 'Arrived',
        'status.in_progress': 'In Progress',
        'status.completed': 'Completed',
        'status.resolved': 'Resolved',
        'status.closed': 'Closed',
        'status.settled': 'Settled',
        'status.estimated': 'Estimated',
        'status.awaiting_owner_approval': 'Awaiting Owner Approval',
        'status.approved': 'Approved',
        'status.rejected': 'Rejected',
        'status.revised_quote_sent': 'Revised Quote Sent',
        'status.overdue_approval': 'Overdue Approval',
        'status.active': 'Active',
        'status.inactive': 'Inactive',
        'onboarding.payment.verify_btn': 'Verify Payment',
        'onboarding.payment.manifest_prefix': 'Manifest Generated:',
        'onboarding.payment.initiation_error': 'Payment Initiation Error',
        'onboarding.payment.verified_success': 'Payment Verified Successfully',
        'onboarding.payment.awaiting_verification': 'Awaiting Manual Verification',
        'onboarding.payment.instructions': 'Please follow the instructions below to complete your activation.',
        'onboarding.payment.cheque': 'Corporate Cheque',
        'onboarding.payment.cash': 'Cash Payment',
        'onboarding.payment.verification_note': 'Verification Note',
        'onboarding.payment.cheque_desc': 'Deliver to BIN GROUP HQ. Include your Property IDs on the back.',
        'onboarding.payment.contact_instruction': 'Contact Instruction',
        'onboarding.payment.cash_desc': 'Please arrange delivery with your assigned account manager.',
        'onboarding.payment.title': 'Activation Pending',
        'onboarding.payment.portfolio_agreement': 'Portfolio Agreement ({count} Assets)',
        'onboarding.payment.agreement_summary': 'Agreement Summary',
        'onboarding.payment.base_amc': 'Base AMC',
        'onboarding.payment.total_amc': 'Total AMC',
        'onboarding.payment.vat_excl': 'VAT Exclusive',
        'onboarding.payment.appreciation_title': 'Thank you for choosing BIN GROUP',
        'onboarding.payment.appreciation_desc': 'Your portfolio is being onboarded into the Sovereign Engine.',
        'onboarding.payment.official_settlement': 'Official Settlement',
        'onboarding.payment.due_now': 'DUE NOW',
        'onboarding.payment.generate_manifest': 'GENERATE SECURE MANIFEST',
        'onboarding.payment.bank_transfer': 'Bank Transfer',
        'onboarding.payment.coming_soon': 'Coming Soon',
        'onboarding.payment.generating_manifest': 'GENERATING MANIFEST...',
        'onboarding.payment.initiation_desc': 'Your contract is prepared. Please select a secure settlement channel.',
        'onboarding.payment.verifying': 'VERIFYING...',
        'onboarding.payment.proceed_manual_btn': 'CONTINUE TO DASHBOARD',
        'onboarding.payment.change_method': 'Change Payment Method',
        'onboarding.payment.verified_title': 'VERIFIED',
        'onboarding.payment.verified_desc': 'Your portfolio is now active in the Sovereign Engine.',
        'onboarding.payment.proceed_btn': 'ENTER DASHBOARD',
        'onboarding.payment.secure_note': 'SECURE INSTITUTIONAL PORTAL',
        'onboarding.payment.asset_class': 'ASSET CLASS',
        'ai.title': 'SOVEREIGN AI',
        'ai.assistant_label': 'ASSISTANT',
        'ai.thinking': 'Sovereign AI Thinking...',
        'ai.init.default': 'BIN GROUP Sovereign AI Initialized. How can I assist you today?',
        'ai.init.tenant': 'Sovereign Assistant Online. How is your residence today? I can help with ticket status or basic maintenance troubleshooting.',
        'ai.init.tech': 'Mission Guidance Node Active. Provide a Ticket ID or ask about part availability for your current assignment.',
        'ai.init.owner': 'Strategic Terminal Active. Analysis of financial velocity and system health is available. What do you wish to audit?',
        'ai.action.check_sos_status': 'Check SOS Status',
        'ai.action.maintenance_tips': 'Maintenance Tips',
        'ai.action.mission_guidance': 'Mission Guidance',
        'ai.action.route_help': 'Route Help',
        'ai.action.audit_roi': 'Audit ROI',
        'ai.action.property_health': 'Property Health',
        'ai.action.queue_summary': 'Queue Summary',
        'ai.action.system_alerts': 'System Alerts',
        'ai.error_undefined': 'Mission control returned an undefined error.',
        'ai.error_unreadable': 'Received unreadable data from Sovereign Engine.',
        'ai.error_unexpected': 'An unexpected error occurred.',
        'ai.error_limit': 'AI Operational Limit Reached (20/24h). Please contact BIN GROUP Admin for credential escalation.',
        'ai.error_unauthenticated': 'Please sign in again to use Sovereign AI.',
        'ai.error_invalid': 'Your request was invalid. Please try again.',
        'ai.error_internal': 'AI backend temporarily unavailable. Please try again.',
        'ai.error_config': 'AI service is not fully configured.',
        'status.tenant': 'Tenant',
        'status.technician': 'Technician',
        'status.admin': 'Admin',
        'support.title': 'Institutional Support',
        'support.subtitle': 'Secure communication channel for asset owners and institutional partners.',
        'support.email': 'Email Support',
        'support.phone': 'Direct Hotline',
        'support.office': 'Headquarters',
        'support.office_address': 'Binconstruction HQ, Level 88, Sovereign Tower, Sheikh Zayed Road, Dubai, UAE',
        'report.tech_summary': 'OPERATIONAL PERFORMANCE AUDIT',
        'report.completion_rate': 'Completion Rate',
        'report.avg_resolution': 'Avg. Resolution',
        'report.active_missions': 'Active Missions',
        'report.tenant_summary': 'RESIDENCY HEALTH AUDIT',
        'report.safety_index': 'Safety Index',
        'report.avg_response': 'Avg. Response',
        'report.active_sos': 'Active SOS',
        'status.pending_dispatch': 'Pending Dispatch',
        'ai.directive_placeholder': 'Type your directive...',
        'status.specialist': 'Specialist',
        'tech.verified_specialist': 'VERIFIED SPECIALIST',
        'tech.secure_identity_verified': 'SECURE IDENTITY VERIFIED',
        'tech.qr_registry_note': 'Scanning this code connects to the Sovereign Registry to verify real-time credentials.',
        'tech.dismiss_id': 'DISMISS ID',
        'tech.show_digital_id': 'SHOW DIGITAL ID',
        'admin.contract_ref': 'CONTRACT REF',
        'fin.log.date': 'DATE',
        'admin.amount': 'AMOUNT',
        'fin.log.status': 'STATUS',
        'dash.kpi.outstanding_rent': 'OUTSTANDING RENT',
        'dash.kpi.occupancy_rate': 'OCCUPANCY RATE',
        'dash.missing_requirements': 'MISSING CRITICAL REQUIREMENTS',
        'dash.escalation_title': 'INSTITUTIONAL ESCALATION',
        'dash.executive_desk': 'EXECUTIVE OPERATIONS DESK',
        'login.authorizing': 'AUTHORIZING SECURE ACCESS...',
        'login.inst_grade_badge': 'INSTITUTIONAL GRADE',
        'login.uae_ops_badge': 'UAE PORTFOLIO OPS',
        'login.change_role': 'CHANGE ROLE',
        'marketing.owners': 'Owners',
        'marketing.tenants': 'Tenants',
        'marketing.technicians': 'Technicians',
        'marketing.brokers': 'Brokers',
        'marketing.security': 'Security',
        'marketing.get_started': 'Get Started',
        'marketing.hero_chip': 'UAE REAL-TIME PROPERTY OPERATIONS',
        'marketing.hero_title': 'BIN-GROUPS — The Real-Time Property Operations OS for the UAE',
        'marketing.hero_desc': 'From villas to skyscrapers, malls, hospitals, stadiums, hotels, government properties, and Majlis operations — BIN-GROUPS connects owners, tenants, technicians, brokers, payments, documents, contracts, and AI design in one verified command system.',
        'marketing.onboard_property': 'Onboard Your Property',
        'marketing.inst_login': 'Institutional Login',
        'marketing.req_contract': 'Request Contract',
        'marketing.built_for_ops': 'Built For Real Operations',
        'marketing.built_for_ops_desc': 'Owner onboarding, emergency dispatch, technician jobs, property operations, AI design, PDF reports, title deed scanning, and contracts are planned as one connected system.',
        'marketing.service_protocols': 'Institutional Service Protocols',
        'marketing.coverage_title': 'UAE-Wide Portfolio Coverage',
        'marketing.inquiry_title': 'Institutional Inquiry',
        'marketing.inquiry_desc': 'Tell BIN-GROUPS what you manage. Your portfolio audit starts here.',
        'marketing.submit_audit': 'Submit for Audit',
        'marketing.live_command': 'LIVE COMMAND',
        'marketing.online': 'ONLINE',
        'marketing.owner_contract': 'Owner Contract',
        'marketing.active_protocol': 'Active Protocol',
        'marketing.tenant_sos': 'Tenant SOS Dispatch',
        'marketing.tech_assigned': 'Technician assigned',
        'marketing.eta': '8 min ETA',
        'marketing.move_out_audit': 'Move-Out Audit',
        'marketing.evidence_captured': 'Evidence captured',
        'marketing.verified': 'Verified',
        'marketing.broker_comm': 'Broker Commission',
        'marketing.finance_approved': 'Finance approved',
        'sector.owners.eyebrow': 'Owner Command Center',
        'sector.owners.title': 'Operate every property with verified contracts, documents, payments, and approvals.',
        'sector.owners.subtitle': 'Owners get onboarding, service plans, add-ons, tenant requests, reports, AI Design Studio, property health, and rent ledger in one real-time system.',
        'sector.owners.b1': 'Institutional Dashboard with real-time portfolio analytics',
        'sector.owners.b2': 'Title Deed OCR extraction and verification protocol',
        'sector.owners.b3': 'Master Service Agreements and automated e-signatures',
        'sector.owners.b4': 'Live rent ledger, move-in/out reports, and property health scores',
        'sector.tenants.eyebrow': 'Tenant Care',
        'sector.tenants.title': 'Fast maintenance requests, technician tracking, and clear move-in/move-out support.',
        'sector.tenants.subtitle': 'Tenants can submit emergencies, upload evidence, follow technician status, verify completion, and access unit documents.',
        'sector.tenants.b1': 'Sovereign SOS: Instant emergency maintenance routing',
        'sector.tenants.b2': 'Real-time technician tracking and GPS-arrival alerts',
        'sector.tenants.b3': 'Digital move-in/out checklists and condition evidence',
        'sector.tenants.b4': 'Direct support chat and community announcements',
        'sector.tech.eyebrow': 'Technician Corps',
        'sector.tech.title': 'A field command center for jobs, routes, duty, overtime, and performance.',
        'sector.tech.subtitle': 'Technicians see assigned jobs, mission pool, route hints, HR duty state, workload, notification link, and digital ID.',
        'sector.tech.b1': 'Area-based auto-assignment and smart route optimization',
        'sector.tech.b2': 'Offline mode for consistent updates in data-dead zones',
        'sector.tech.b3': 'Digital ID and certified credential management',
        'sector.tech.b4': 'Performance tracking, overtime visibility, and certified task completion',
        'sector.brokers.eyebrow': 'Broker Network',
        'sector.brokers.title': 'Track leads, contract attribution, commission status, and payout readiness.',
        'sector.brokers.subtitle': 'Brokers can bring owners, properties, and tenants while finance/admin controls payment verification and payout approval.',
        'sector.brokers.b1': 'Broker ID and automated lead attribution tracking',
        'sector.brokers.b2': 'Real-time commission pipeline and approval status',
        'sector.brokers.b3': 'Contract management and payout proof archive',
        'sector.brokers.b4': 'Direct communication line with Finance and Admin',
        'sector.security.eyebrow': 'Sovereign Security',
        'sector.security.title': 'Document protection, audit logs, role access, and evidence protocols.',
        'sector.security.subtitle': 'Sensitive documents, payments, contracts, and identity flows are protected by institutional-grade encryption and access controls.',
        'sector.security.b1': 'Firebase App Check and device-integrity enforcement',
        'sector.security.b2': 'Immutable audit logs for every operational event',
        'sector.security.b3': 'Encrypted document vault and role-based data isolation',
        'sector.security.b4': 'Protocol-driven evidence capture for all field work',
        'proof.owner_onboarding': 'Owner onboarding',
        'proof.owner_onboarding_desc': 'Documents, service plan, add-ons, payment, approval.',
        'proof.tenant_dispatch': 'Tenant dispatch',
        'proof.tenant_dispatch_desc': 'Emergency request, technician status, completion proof.',
        'proof.tech_jobs': 'Technician jobs',
        'proof.tech_jobs_desc': 'Mission cards, navigation, duty, workload.',
        'proof.owner_command': 'Owner Command Center',
        'proof.owner_command_desc': 'Portfolio reports, approvals, maintenance history, payments, documents, and property performance.',
        'proof.ai_studio': 'AI Design Studio',
        'proof.ai_studio_desc': 'Room concepts, scope, material and quote path.',
        'proof.pdf_reports': 'PDF reports',
        'proof.pdf_reports_desc': 'Contracts, move-in/out, maintenance, owner reports.',
        'prop.villas': 'Villas',
        'prop.apartments': 'Apartments',
        'prop.res_buildings': 'Residential buildings',
        'prop.com_buildings': 'Commercial buildings',
        'prop.offices': 'Offices',
        'prop.hotels': 'Hotels',
        'prop.malls': 'Malls',
        'prop.hospitals': 'Hospitals',
        'prop.clinics': 'Clinics',
        'prop.schools': 'Schools',
        'prop.warehouses': 'Warehouses',
        'prop.labour_camps': 'Labour camps',
        'prop.gov_properties': 'Government properties',
        'prop.gov_majlis': 'Government Majlis',
        'prop.pri_majlis': 'Private Majlis',
        'prop.mixed_towers': 'Mixed-use towers',
        'prop.skyscrapers': 'Skyscrapers',
        'prop.stadiums': 'Stadiums',
        'prop.sports_complex': 'Sports complexes',
        'prop.event_venues': 'Event venues',
        'prop.resorts': 'Resorts',
        'prop.retail_centers': 'Retail centers',
        'prop.industrial': 'Industrial properties',
        'prop.staff_acc': 'Staff accommodation',
        'prop.farms': 'Farms / estates',
        'form.name': 'Name',
        'form.contact': 'Phone / Email',
        'form.prop_type': 'Property Type',
        'form.emirate': 'Emirate',
        'form.details': 'Portfolio Details',
        'form.ceo_note': 'CEO escalation is available in addition to normal support tickets and chat.',
        'plan.maintenance': 'Maintenance Only (Alpha)',
        'plan.management': 'Property Management (Beta)',
        'plan.hybrid': 'Total Care Hybrid (Omega)',
        'plan.enterprise': 'Enterprise Custom Protocol',
        'fin.title': 'Financial Command',
        'fin.subtitle': 'Revenue, payouts, liquidity, and overdue balances',
        'fin.kpi.total_collection': 'Total Collection',
        'fin.sovereign_payout': 'Sovereign Payouts',
        'fin.net_position': 'Net Position',
        'fin.overdue_deficit': 'Overdue Deficit',
        'fin.ledger': 'Institutional Ledger',
        'fin.export_btn': 'Export Report',
        'fin.table.date': 'Date',
        'fin.table.description': 'Description',
        'fin.table.category': 'Category',
        'fin.table.amount': 'Amount',
        'fin.table.type': 'Type',
        'fin.payroll_title': 'Payroll Command',
        'fin.payroll_subtitle': 'Technician disbursements and labor overhead tracking',
        'fin.payroll_empty': 'No pending payroll disbursements in the sovereign pool.',
        'fin.payroll': 'Payroll Hub',
        'fin.gen_payroll_btn': 'Execute Payroll Run',
        'fin.active_liabilities': 'Active Liabilities',
        'fin.pending_disbursement': 'Pending Disbursement',
        'fin.table.technician': 'Technician',
        'fin.table.month': 'Month',
        'fin.settle_payment': 'Settle Payment',
        'fin.gen_payroll_title': 'Execute Sovereign Payroll',
        'fin.gen_payroll_desc': 'Triggering this will authorize funds for all active technician nodes.',
        'fin.gen_payroll_info': 'Are you sure you want to authorize the current pool?',
        'fin.confirm_execute': 'Confirm Execution',
        'design.manager_title': 'Design Studio Manager',
        'design.manager_subtitle': 'Review and manage AI-generated design requests',
        'design.empty': 'No design requests yet.',
        'design.table.owner': 'Owner',
        'design.table.property': 'Property',
        'design.table.budget': 'Budget',
        'design.table.status': 'Status',
        'design.table.actions': 'Actions',
        'admin.audit_shield': 'Audit Shield',
        'admin.compliance_vault': 'Compliance Vault',
        'admin.orphan_war_room': 'Orphan War Room',
        'admin.manual_approvals': 'Manual Approvals',
        'admin.control_center': 'Control Center',
        'admin.pricing_matrix': 'Pricing Matrix 2026',
        'admin.active_tenants': 'Active Tenants',
        'admin.technician_corps': 'Technician Corps',
        'admin.duty_command': 'Duty Command Center',
        'admin.systemic_audit': 'Systemic Audit Log',
        'admin.hr_command': 'HR Command',
        'vault.title': 'Document Vault',
        'vault.subtitle': 'Institutional record management and document verification.',
        'vault.empty': 'No documents uploaded yet.',
        'audit.title': 'Institutional Audit',
        'audit.subtitle': 'Real-time systemic event logging and compliance tracking.',
        'audit.empty': 'No audit events recorded yet.',
        'design.action.review': 'Review',
        'design.action.assign': 'Assign',
        'design.action.quote': 'Generate Quote',
        'payroll.title': 'Payroll Hub',
        'payroll.subtitle': 'Technician disbursements and staff salary management.',
        'payroll.empty': 'No payroll records yet.',
        'payment.verify_title': 'Verify Payment',
        'payment.verify_subtitle': 'Pending bank transfers and manual settlement verification.',
        'payment.empty': 'No payment submissions pending verification.',
        'admin.terminal.title': 'BIN-ADMINISTRY™ TERMINAL',
        'admin.terminal.subtitle': 'INSTITUTIONAL GRADE PROPERTY OPERATIONS CORE',
        'admin.node.smart_building': 'Smart Building Monitor',
        'admin.node.duty_monitor': 'Duty Monitor',
        'admin.node.security_vault': 'Security Vault',
        'admin.node.orphan_war_room': 'Orphan War Room',
        'admin.node.financial_command': 'Financial Command',
        'admin.node.audit_shield': 'Audit Shield',
        'admin.node.pricing_matrix': 'Pricing Matrix',
        'admin.node.system_audit': 'System Audit',
        'dash.hello': 'Hello',
        'onboarding.retry_scan': 'Retry Scan'
    },
    ar: {
        'nav.dashboard': 'لوحة القيادة',
        'nav.onboarding': 'التسجيل',
        'nav.financial': 'المالية',
        'nav.tech': 'فني',
        'nav.admin': 'إدارة مجموعة بن',
        'nav.tenants': 'المستأجرون',
        'nav.tickets': 'سجلات المهام',
        'nav.financials': 'الخزينة',
        'nav.audit': 'التدقيق المؤسسي',
        'nav.brokers': 'الوسطاء',
        'nav.settings': 'سياسة الخصوصية',
        'nav.live_map': 'الخريطة المباشرة',
        'nav.sos_feed': 'تغذية الاستغاثة',
        'nav.reports': 'التقارير',
        'nav.logout': 'تسجيل الخروج',
        'nav.login': 'دخول',
        'nav.get_started': 'ابدأ الآن',
        'nav.admin_user': 'مستخدم مسؤول',
        'nav.version_info': 'v1.0.0 | تاريخ الإطلاق: 6 يونيو 2026',
        'nav.admin_panel_title': 'لوحة تحكم BIN-ADMINISTRY™',
        'nav.sovereign_core': 'النواة السيادية',
        'nav.operations': 'العمليات',
        'nav.support': 'الدعم',
        'nav.owner_portal_link': 'بوابة الملاك ↗',
        'nav.administry': 'الإدارة',
        'landing.title': 'نظام التشغيل للعقارات في الإمارات.',
        'landing.subtitle': 'مجموعة بن هي المنصة المؤسسية الرائدة في الإمارات لإدارة الأصول. نحن نحل تعقيدات العمليات العقارية واسعة النطاق من خلال توحيد إدارة المستأجرين، والصيانة التنبؤية، والامتثال للبيانات السيادية.',
        'landing.hero_title_line1': 'بن للإنشاءات™',
        'landing.hero_title_line2': 'صيانة مجموعة بن',
        'landing.cta': 'سجل أصولك الآن ←',
        'landing.partner_login': 'دخول الشركاء',
        'landing.mission_overline': 'المهمة المؤسسية',
        'landing.mission_title': 'المهمة المؤسسية',
        'landing.mission_desc': 'إرساء المعايير الذهبية لصيانة العقارات والإنشاءات في دولة الإمارات، لضمان أن كل أصل - من المجالس الحكومية إلى العقارات الخاصة - يعكس رؤية الدولة للتميز المؤسسي.',
        'landing.about_overline': 'ملف الشركة',
        'landing.about_title': 'سيادة متميزة',
        'landing.about_desc': 'بصفتنا كياناً متوافقاً مع المعايير السيادية، نحن متخصصون في الصيانة عالية الأهمية للأصول الحكومية والمواقع التراثية والمحافظ السكنية النخبوية، ونقدم دقة تقنية لا تضاهى وأمناً مؤسسياً.',
        'landing.contact_title': 'المراسلات المؤسسية',
        'landing.email': 'Ceo@bin-groups.com',
        'landing.phone': '+971 55 242 3233',
        'landing.address': 'المقر الرئيسي لبن للإنشاءات، طابق 88، برج سوفرين، شارع الشيخ زايد، دبي، الإمارات',
        'landing.sectors_title': 'القطاعات التي نتقنها',
        'landing.sector.govt_title': 'الحكومة والجهات السيادية',
        'landing.sector.govt_desc': 'صيانة بمستوى مؤسسي للمجالس والوزارات والأصول الاتحادية مع جاهزية متخصصة للبروتوكولات.',
        'landing.sector.luxury_title': 'الضيافة الفاخرة',
        'landing.sector.luxury_desc': 'الحفاظ على المعايير الذهبية لمحفظة الفنادق النخبة في الإمارات والإقامات الخاصة فائقة الفخامة.',
        'landing.sector.infra_title': 'البنية التحتية الحيوية',
        'landing.sector.infra_desc': 'الدعم الفني للعقد اللوجستية، وأنظمة تبريد المناطق، والمراكز التجارية عالية الأهمية.',
        'landing.about_us': 'من نحن',
        'landing.contact_us': 'اتصل بنا',
        'landing.support': 'الدعم',
        'landing.get_quote': 'احصل على تسعيرة',
        'landing.who_we_are': 'من نحن',
        'landing.who_we_are_desc': 'مجموعة بن هي قوة مؤسسية مقرها الإمارات مكرسة لإدارة دورة حياة الأصول الممتازة والسيادية. نحن نمثل نقطة التلاقي بين الهندسة المتقدمة وأمن البيانات الوطني.',
        'landing.what_we_do': 'ماذا نفعل',
        'landing.what_we_do_desc': 'من الصيانة التنبؤية للمجالس الحكومية إلى التحديث الهيكلي للأبراج الفاخرة، نوفر البنية التحتية التقنية التي تحافظ على تشغيل أهم الأصول في الإمارات.',
        'landing.why_choose_us': 'لماذا مجموعة بن؟',
        'landing.why_choose_us_desc': 'نحن المنصة الوحيدة في المنطقة التي تضمن سيادة البيانات بنسبة 100% على أراضي الإمارات مع تقديم اتفاقيات مستوى خدمة صيانة بمستوى عسكري.',
        'landing.how_it_works': 'كيف يعمل النظام',
        'landing.how_it_works_desc': 'قم بتسجيل محفظتك، واحصل على تدقيق بمستوى مؤسسي، وانشر فيلق الفنيين المتخصصين لدينا عبر محطة القيادة المركزية الخاصة بنا.',
        'landing.hero_onboard_cta': 'سجل أصولك المميزة',
        'landing.solve_title': 'حل لمشاكل الإدارة',
        'landing.solve_subtitle': 'نحن نقضي على صعوبات الصيانة التقليدية، ونتحرك بسرعة محفظتك العقارية.',
        'landing.zero_friction': 'صفر احتكاك',
        'landing.zero_friction_desc': 'لا يوجد تنسيق يدوي. يتم التعامل مع كل شيء من التذاكر إلى الفواتير رقمياً داخل النظام السيادي.',
        'landing.gps_dispatch': 'إرسال GPS في الوقت الفعلي',
        'landing.gps_dispatch_desc': 'شاهد تنفيذ أمر الخدمة الخاص بك في الوقت الفعلي. يتم إرسال فنيينا فوراً عبر توجيه GPS.',
        'landing.auto_financials': 'مالية مؤتمتة',
        'landing.auto_financials_desc': 'يتم توجيه عوائد الإيجار ورسوم الصيانة من خلال بروتوكولات مؤتمتة دقيقة رياضياً.',
        'landing.transparency': 'شفافية بنسبة 100%',
        'landing.transparency_desc_v2': 'تتبع المحفظة بشكل غير قابل للتغيير. لا توجد تكاليف خفية. لا تأخيرات إدارية. فقط رؤية مطلقة.',
        'landing.deployment_title': 'قدرات نشر المهام',
        'landing.elite_infra': 'صيانة البنية التحتية النخبوية',
        'landing.executive_access': 'وصول مباشر للإدارة التنفيذية',
        'landing.executive_desc': 'تتطلب الشراكات المؤسسية تواصلاً مباشراً. لتسجيل الأصول عالية القيمة أو التعاون الإقليمي، تواصل مباشرة مع قيادتنا.',
        'landing.whatsapp_ceo': 'واتساب المدير التنفيذي (0552423233)',
        'landing.registered_trademark': 'علامة تجارية مسجلة • عمليات في جميع أنحاء الإمارات',
        'landing.sign_in_dash': 'تسجيل الدخول إلى لوحة التحكم',
        'landing.auth_authorize': 'تفويض الدخول',
        'landing.identity_verify': 'التحقق من الهوية',
        'landing.secure_global': 'تحقق عالمي آمن',
        'onboarding.title': 'التسجيل المؤسسي',
        'onboarding.location_title': 'موقع العقار',
        'onboarding.location_desc': 'حدد الإحداثيات الجغرافية لعمليات الإرسال الميداني.',
        'onboarding.location_placeholder': 'ابحث عن عنوان العقار في الإمارات...',
        'onboarding.location_manual': 'وضع المراجعة اليدوية',
        'onboarding.location_manual_title': 'إدخال الموقع يدوياً',
        'onboarding.location_manual_info': 'يتطلب الموقع اليدوي مراجعة إدارية قبل إرسال الفنيين.',
        'onboarding.description': 'توفر مجموعة بن صيانة متميزة لجميع فئات الأصول: المجالس الحكومية، العقارات الحكومية، الفنادق، السكني، التجاري، والمراكز المؤسسية.',
        'onboarding.bulk_intake': 'إدخال العقارات بالجملة (1–500)',
        'onboarding.analysis': 'تحليل الأصول',
        'onboarding.quote': 'تسعيرة مجموعة بن',
        'onboarding.payment': 'التفعيل',
        'step.intake': 'إدخال العقار',
        'step.analysis': 'تحليل الأصول',
        'step.quote': 'تسعيرة مجموعة بن',
        'step.tier': 'اختيار العقد',
        'step.addons': 'الإضافات التشغيلية',
        'step.summary': 'مبلغ التأمين',
        'step.account': 'تفعيل الحساب',
        'step.type': 'نوع العقار',
        'step.location': 'الموقع',
        'step.data': 'بيانات المبنى',
        'step.systems': 'الأنظمة والخدمات',
        'step.contract': 'اختيار العقد',
        'step.terms': 'شروط الدفع',
        'step.review': 'ملخص المراجعة',
        'step.submit': 'التفعيل النهائي',
        'onboarding.systems_audit': 'تدقيق الأنظمة الحرجة',
        'onboarding.property_operational_matrix': 'مصفوفة تشغيل العقار',
        'onboarding.systems_desc': 'صرح بالأنظمة المؤسسية لنمذجة دورة الحياة والالتزام باتفاقيات مستوى الخدمة.',
        'onboarding.addons_title': 'الإضافات التشغيلية',
        'onboarding.addons_subtitle': 'اختر خدمات إضافية',
        'onboarding.addons_desc': 'طبقات خدمة حرجة مصممة خصيصاً لنوع أصلك ومتطلباتك التنظيمية.',
        'onboarding.total_annual': 'الإجمالي السنوي',
        'onboarding.selected_addons': 'الإضافات المختارة',
        'onboarding.sovereign_stack': 'المجموعة السيادية',
        'onboarding.mandatory': 'إلزامي',
        'onboarding.reason': 'السبب',
        'onboarding.annual': 'سنوي',
        'onboarding.back_to_models': 'العودة للنماذج',
        'field.emirate': 'الإمارة',
        'field.area': 'المنطقة / المجمع',
        'field.type': 'نوع العقار',
        'field.subtype': 'النوع الفرعي',
        'field.usetype': 'نوع الاستخدام',
        'field.floors': 'الأدوار',
        'field.units': 'الوحدات',
        'field.sqft': 'المساحة (قدم مربع)',
        'field.age': 'عمر المبنى',
        'field.lifts': 'المصاعد',
        'field.pool': 'المسبح',
        'field.tank': 'خزان المياه',
        'field.sira': 'سيرا / كاميرات المراقبة',
        'field.fire': 'أنظمة الحريق',
        'field.dist_cooling': 'تكييف المناطق',
        'field.majlis': 'بروتوكول المجالس الحكومية',
        'field.heritage': 'حساسية المواقع التراثية',
        'field.grade': 'فئة الأصول',
        'field.status': 'الحالة الحالية',
        'btn.next': 'التالي',
        'btn.back': 'السابق',
        'btn.add_prop': 'إضافة عقار (+)',
        'btn.bulk_csv': 'تحميل ملف CSV',
        'btn.exit': 'خروج',
        'btn.quote': 'احصل على تسعيرة مؤسسية',
        'status.sovereign': 'فئة مجموعة بن',
        'login.portal': 'بوابة الشركاء',
        'login.auth_access': 'دخول مؤسسي موثق',
        'login.email': 'البريد الإلكتروني',
        'login.password': 'كلمة المرور',
        'login.signin': 'دخول آمن',
        'login.google': 'الدخول عبر جوجل',
        'login.or_sso': 'أو الدخول المؤسسي الموحد',
        'login.forgot_password': 'نسيت كلمة المرور',
        'login.iso_secure': 'آمن بمعايير ISO 27001',
        'login.iso_secure_badge': 'معتمد بمعايير ISO 27001 ومؤمن سيادياً',
        'login.inst_grade': 'درجة مؤسسية',
        'login.uae_ops': 'عمليات محفظة الإمارات',
        'login.footer': '© 2026 مجموعة بن الإمارات. الدخول غير المصرح به مراقب.',
        'login.authorized_only': 'دخول العملاء والشركاء المصرح لهم فقط.',
        'gateway.title': 'اختر عقدة التشغيل الخاصة بك',
        'gateway.subtitle': 'ادخل إلى نظام BIN GROUP السيادي عبر دورك المصرح به.',
        'gateway.role.owner': 'المتابعة كمالك',
        'gateway.role.tenant': 'المتابعة كمستأجر',
        'gateway.role.technician': 'المتابعة كفني',
        'gateway.role.broker': 'المتابعة كوسيط',
        'gateway.role.admin': 'المتابعة كمسؤول',
        'dash.title': 'ذكاء المحفظة',
        'dash.terminal': 'المحطة',
        'dash.locked_assets': 'الأصول المقفلة',
        'dash.onboard_cta': '+ تسجيل أصل جديد',
        'dash.kpi.gross_val': 'إجمالي قيمة العقد',
        'dash.kpi.annual_yield': 'العائد السنوي (تقديري)',
        'dash.kpi.radius': 'نطاق المحفظة',
        'dash.kpi.majlis_readiness': 'الجاهزية المؤسسية',
        'dash.kpi.net_roi': 'صافي العائد على الاستثمار',
        'dash.kpi.gross_roi': 'إجمالي العائد',
        'dash.kpi.esg': 'معايير ESG',
        'dash.kpi.compliance': 'درجة الامتثال',
        'dash.kpi.integrity': 'سلامة الأصول',
        'dash.kpi.satisfaction': 'رضا المستأجرين',
        'dash.kpi.trend.live': 'مباشر',
        'dash.kpi.trend.active': 'نشط',
        'dash.kpi.trend.optimal': 'مثالي',
        'dash.ledger': 'سجل الأصول',
        'dash.asset_node': 'عقدة الأصول',
        'dash.annual_amc': 'عقد الصيانة السنوي (AMC)',
        'dash.protocol_status': 'حالة البروتوكول',
        'dash.private_asset': 'أصل خاص',
        'dash.alerts': 'تنبيهات مجموعة بن',
        'dash.intel.deck': 'منصة ذكاء مجموعة بن',
        'dash.intel.forecast': 'توقعات الذكاء الاصطناعي',
        'dash.intel.integrity_decay': 'تآكل السلامة',
        'dash.intel.horizon': 'أفق 12 شهراً',
        'dash.intel.annualized_net': 'صافي سنوي',
        'dash.intel.guidance_title': 'توجيه المهمة الاستراتيجية',
        'dash.intel.protocol_commands': 'أوامر بروتوكول مجموعة بن',
        'dash.intel.download_audit': 'تحميل تدقيق السلامة (PDF)',
        'dash.intel.generating_audit': 'جاري إصدار تدقيق مجموعة بن...',
        'dash.command_deck': 'قيادة أصول مجموعة بن',
        'dash.command_subtitle': 'التدقيق المؤسسي وواجهة المنطقة الوطنية',
        'dash.empty_title': 'المحفظة غير متصلة',
        'dash.empty_subtitle': 'ليس لديك عقود خدمات مؤسسية نشطة مع مجموعة بن. ابدأ تسجيل أصولك لفتح المراقبة المباشرة.',
        'dash.empty_cta': '+ ابدأ تسجيل الأصول',
        'dash.mission_feed': 'تغذية المهام',
        'dash.listening': 'الاستماع لتنبيهات البروتول للمهمات الحرجة...',
        'dash.hash_anchor': 'رابط تشفير مجموعة بن',
        'dash.municipality_adapter': 'محول البلدية',
        'dash.risk_grade': 'فئة مخاطر التأمين',
        'dash.gateway_status': 'حالة البوابة',
        'dash.audit_btn': 'إصدار تدقيق مؤسسي',
        'dash.sync_btn': 'مزامنة مع البوابة الوطنية',
        'dash.status.optimal': 'أمثل (P.1)',
        'dash.status.stable': 'مستقر (P.2)',
        'sos.btn': 'تفعيل استغاثة SOS',
        'sos.title': 'إرسال استغاثة',
        'sos.subtitle': 'الإبلاغ عن أعطال البنية التحتية الحرجة للإصلاح المؤسسي الفوري.',
        'sos.success_title': 'تم تفعيل الإرسال',
        'sos.success_subtitle': 'تم استلام معايير المهمة. محرك الجغرافيا V4 يقوم بتوجيه طلبك.',
        'sos.emergency_protocol': 'بروتوكول الطوارئ',
        'sos.fault_category': 'فئة العطل',
        'sos.mission_description': 'وصف المهمة',
        'sos.description_placeholder': 'قدم تفاصيل الوحدة وتفاصيل العطل...',
        'sos.attach_evidence': 'إرفاق دليل مرئي',
        'sos.trigger_btn': 'تفعيل الإرسال',
        'sos.cat.ac': 'عطل حرج في التكييف',
        'sos.cat.plumbing': 'عطل سباكة رئيسي / فيضان',
        'sos.cat.electrical': 'ماس كهربائي / انقطاع تيار',
        'sos.cat.security': 'خرق أمني / دخول',
        'sos.return_dash': 'العودة للوحة القيادة',
        'sos.location_locked': 'تم قفل موقع المهمة',
        'sos.timing_label': 'التوقيت المفضل',
        'sos.asap': 'في أسرع وقت (طوارئ)',
        'sos.morning': 'صباحاً (8ص - 12ظ)',
        'sos.afternoon': 'بعد الظهر (12ظ - 4ع)',
        'sos.evening': 'مساءً (4ع - 8م)',
        'sos.photo_attached': 'تم إرفاق الصورة',
        'sos.attach_photo': 'إرفاق دليل مصور',
        'tech.service_node': 'عقدة الخدمة',
        'tech.subtitle': 'شبكة الصيانة المباشرة وترميم أصول مجموعة بن.',
        'tech.mission_dispatch': 'إرسال المهمة',
        'tech.kpi.mttr': 'متوسط وقت الإصلاح',
        'tech.kpi.sla': 'الالتزام بـ SLA',
        'tech.kpi.uptime': 'جاهزية المنطقة',
        'tech.trend.live': 'مباشر',
        'tech.trend.optimal': 'مثالي',
        'tech.trend.sovereign': 'مجموعة بن',
        'tech.trend.stable': 'مستقر',
        'tech.protocol': 'بروتوكول ألفا-4',
        'tech.action.start_duty': 'بدء المناوبة',
        'tech.action.end_duty': 'إنهاء المناوبة',
        'tech.action.take_break': 'أخذ استراحة',
        'tech.action.resume_duty': 'استئناف العمل',
        'tech.action.accept_job': 'قبول المهمة',
        'tech.action.en_route': 'في الطريق',
        'tech.action.arrived': 'لقد وصلت',
        'tech.action.start_work': 'بدء المهمة',
        'tech.action.complete': 'إنهاء المهمة',
        'tech.status.working': 'يعمل حالياً',
        'tech.status.break': 'في استراحة',
        'tech.status.off': 'خارج المناوبة',
        'tech.protocol.before_photo': 'الصورة قبل العمل',
        'tech.protocol.after_photo': 'الصورة بعد العمل',
        'tech.protocol.signature': 'توقيع المستأجر',
        'tech.protocol.notes': 'ملاحظات المهمة',
        'tech.protocol.required': 'مخالفة البروتوكول: الأدلة الكاملة مطلوبة.',
        'tech.protocol.success': 'تمت مزامنة المهمة في الخزنة السيادية',
        'tech.priority.normal': 'عادي',
        'tech.priority.emergency': 'طوارئ',
        'tech.status_tracking': 'تتبع الحالة',
        'tech.open_node': 'فتح العقدة',
        'tech.empty': 'لا توجد مهمات نشطة في هذا القطاع.',
        'tech.unknown_unit': 'وحدة غير معروفة',
        'tech.status.live': 'مباشر',
        'tech.status.syncing': 'جاري المزامنة',
        'tech.live_ops': 'العمليات المباشرة',
        'tech.urgent_dispatch': 'إرسال عاجل',
        'tech.navigate': 'توجيه',
        'tech.mission_brief': 'ملخص المهمة',
        'tech.enable_alerts': 'تفعيل التنبيهات',
        'tech.alerts_on': 'التنبيهات نشطة',
        'tech.missions': 'المهمات',
        'tech.hr_duty': 'الموارد البشرية والدوام',
        'tech.mission_pool': 'مجمع المهمات',
        'tech.pool_id': 'معرف المجمع',
        'tech.accept': 'قبول',
        'tech.notif_handshake_success': 'نجاح: تم إنشاء قناة تنبيهات مجموعة بن.',
        'tech.notif_link': 'رابط التنبيهات',
        'tech.notif_ios_pwa': 'مطلوب للإرسال العاجل على تطبيقات iOS PWA.',
        'tech.notif_active': 'رابط الإرسال نشط',
        'tech.notif_enable': 'تفعيل تنبيهات الدفع',
        'tech.duty_sync': 'مزامنة الدوام',
        'tech.duty_subtitle': 'حدد توافرك لمحرك الإرسال الآلي.',
        'tech.on_duty': 'في الدوام',
        'tech.off_duty': 'خارج الدوام',
        'tech.workload_node': 'عقدة عبء العمل',
        'tech.standard_hours': 'الساعات القياسية (هذا الأسبوع)',
        'tech.reward_unlocked': 'تم فتح مكافأة سيادية',
        'tech.vacation_unlocked': 'تهانينا! لقد حصلت على إجازتك السنوية لمدة 35 يوماً.',
        'report.tech_summary': 'تدقيق الأداء التشغيلي',
        'report.completion_rate': 'معدل الإنجاز',
        'report.avg_resolution': 'متوسط وقت الحل',
        'report.active_missions': 'المهام النشطة',
        'report.tenant_summary': 'تدقيق سلامة الإقامة',
        'report.safety_index': 'مؤشر السلامة',
        'report.avg_response': 'متوسط الاستجابة',
        'report.active_sos': 'استغاثات نشطة',
        'status.pending_dispatch': 'قيد الإرسال',
        'status.specialist': 'الأخصائي المعين',
        'ai.init.tenant': 'المساعد السيادي متصل. كيف حال إقامتك اليوم؟ يمكنني المساعدة في حالة التذاكر أو استكشاف أخطاء الصيانة الأساسية.',
        'ai.init.tech': 'عقدة توجيه المهام نشطة. قدم معرف التذكرة أو اسأل عن توفر القطع لمهمتك الحالية.',
        'ai.init.owner': 'المحطة الاستراتيجية نشطة. تحليل التدفق المالي وصحة النظام متاح. ماذا تريد أن تدقق؟',
        'ai.directive_placeholder': 'اكتب توجيهك هنا...',
        'footer.home': 'الرئيسية',
        'footer.privacy': 'سياسة الخصوصية',
        'footer.terms': 'شروط الخدمة',
        'footer.support': 'الدعم المؤسسي',
        'footer.copyright': '© 2026 بن للإنشاءات™ الإمارات. جميع الحقوق محفوظة.',
        'common.system': 'النظام',
        'common.sys_init_fault': 'خطأ في تهيئة النظام',
        'common.reload_sys': 'إعادة تحميل النظام',
        'common.auth_sync': 'جاري توثيق هوية مجموعة بن...',
        'status.owner': 'مالك',
        'common.asset': 'أصل',
        'status.pending': 'قيد الانتظار',
        'status.estimated': 'تم التقدير',
        'status.awaiting_owner_approval': 'بانتظار موافقة المالك',
        'status.approved': 'تمت الموافقة',
        'status.rejected': 'مرفوض',
        'status.revised_quote_sent': 'تم إرسال تسعيرة معدلة',
        'status.overdue_approval': 'موافقة متأخرة',
        'onboarding.payment.verify_btn': 'التحقق من الدفع',
        'onboarding.payment.vat_excl': 'غير شامل ضريبة القيمة المضافة',
        'onboarding.payment.appreciation_title': 'شكراً لاختياركم مجموعة بن',
        'onboarding.payment.appreciation_desc': 'جاري تسجيل محفظتكم في المحرك السيادي.',
        'onboarding.payment.official_settlement': 'تسوية رسمية',
        'onboarding.payment.due_now': 'يستحق الآن',
        'onboarding.payment.generate_manifest': 'إصدار بيان تسوية موثق',
        'onboarding.payment.cheque': 'شيك شركة',
        'onboarding.payment.cash': 'دفع نقدي',
        'onboarding.payment.bank_transfer': 'حوالة بنكية',
        'onboarding.payment.coming_soon': 'قريباً',
        'onboarding.payment.secure_note': 'بوابة مؤسسية آمنة',
        'onboarding.payment.initiation_error': 'خطأ في بدء عملية الدفع',
        'onboarding.payment.manifest_prefix': 'تم إصدار البيان:',
        'onboarding.payment.verified_success': 'تم تأكيد الدفع بنجاح',
        'onboarding.payment.awaiting_verification': 'بانتظار التحقق اليدوي',
        'onboarding.payment.instructions': 'يرجى اتباع التعليمات أدناه لإكمال التفعيل.',
        'onboarding.payment.verification_note': 'ملاحظة التحقق',
        'onboarding.payment.cheque_desc': 'يرجى تسليمه في المقر الرئيسي لمجموعة بن. اكتب أرقام العقار بالخلف.',
        'onboarding.payment.contact_instruction': 'تعليمات التواصل',
        'onboarding.payment.cash_desc': 'يرجى ترتيب التسليم مع مدير حسابكم.',
        'onboarding.payment.title': 'التفعيل قيد الانتظار',
        'onboarding.payment.portfolio_agreement': 'اتفاقية المحفظة العقارية ({count} أصول)',
        'onboarding.payment.agreement_summary': 'ملخص الاتفاقية',
        'onboarding.payment.base_amc': 'تكلفة الصيانة الأساسية',
        'onboarding.payment.total_amc': 'تكلفة الصيانة الإجمالية',
        'onboarding.payment.generating_manifest': 'جاري إصدار البيان...',
        'onboarding.payment.initiation_desc': 'لقد تم تجهيز عقدك. يرجى اختيار قناة تسوية آمنة.',
        'onboarding.payment.verifying': 'جاري التحقق...',
        'onboarding.payment.proceed_manual_btn': 'المتابعة للوحة القيادة',
        'onboarding.payment.change_method': 'تغيير طريقة الدفع',
        'onboarding.payment.verified_title': 'تم التوثيق',
        'onboarding.payment.verified_desc': 'محفظتك الآن نشطة في المحرك السيادي.',
        'onboarding.payment.proceed_btn': 'الدخول للوحة القيادة',
        'onboarding.payment.asset_class': 'فئة الأصول',
        'ai.init.default': 'النظام السيادي جاهز للمساعدة. كيف يمكنني خدمتك اليوم؟',
        'ai.thinking': 'النظام السيادي يحلل المعطيات...',
        'ai.action.check_sos_status': 'حالة استغاثة الطوارئ',
        'ai.action.maintenance_tips': 'نصائح الصيانة',
        'ai.action.mission_guidance': 'إرشادات المهمة',
        'ai.action.route_help': 'توجيه المسار',
        'ai.action.audit_roi': 'تدقيق العائد المالي',
        'ai.action.property_health': 'سلامة الأصول',
        'ai.action.queue_summary': 'ملخص قائمة الانتظار',
        'ai.action.system_alerts': 'تنبيهات النظام',
        'ai.title': 'النظام السيادي',
        'ai.assistant_label': 'مساعد',
        'ai.error_undefined': 'أعاد مركز التحكم خطأ غير معروف.',
        'ai.error_unreadable': 'تم استلام بيانات غير مقروءة من المحرك السيادي.',
        'ai.error_unexpected': 'حدث خطأ غير متوقع.',
        'ai.error_limit': 'تم الوصول إلى الحد التشغيلي (20/24ساعة).',
        'ai.error_unauthenticated': 'يرجى تسجيل الدخول مرة أخرى لاستخدام الذكاء الاصطناعي.',
        'ai.error_invalid': 'الطلب غير صالح. يرجى المحاولة مرة أخرى.',
        'ai.error_internal': 'الخدمة الخلفية غير متوفرة حالياً.',
        'ai.error_config': 'خدمة الذكاء الاصطناعي غير مهيأة بالكامل.',
        'admin.dashboard': 'لوحة تحكم المسؤول',
        'admin.total_revenue': 'إجمالي الإيرادات',
        'admin.active_tenants': 'المستأجرون النشطون',
        'common.currency': 'درهم',
        'common.currency_aed': 'درهم',
        'tech.ai_proposal': 'مقترحات بروتوكول الذكاء الاصطناعي',
        'dash.sovereign_ai': 'الذكاء الاصطناعي السيادي',
        'landing.transparency_title': 'شفافية النمو والمخاطر',
        'landing.transparency_desc': 'يتم تأمين جميع عمليات الإرسال المالية عبر رابط التشفير السيادي.',
        'fin.title': 'القيادة المالية',
        'fin.subtitle': 'الإيرادات، المدفوعات، السيولة، والأرصدة المتأخرة',
        'fin.kpi.total_collection': 'إجمالي التحصيل',
        'fin.sovereign_payout': 'المدفوعات السيادية',
        'fin.net_position': 'المركز الصافي',
        'fin.overdue_deficit': 'عجز المتأخرات',
        'fin.ledger': 'الدفتر المؤسسي',
        'fin.export_btn': 'تصدير التقرير',
        'fin.table.date': 'التاريخ',
        'fin.table.description': 'الوصف',
        'fin.table.category': 'الفئة',
        'fin.table.amount': 'المبلغ',
        'fin.table.type': 'النوع',
        'fin.payroll_title': 'قيادة الرواتب',
        'fin.payroll_subtitle': 'صرف مستحقات الفنيين وتتبع التكاليف التشغيلية',
        'fin.payroll_empty': 'لا توجد دفعات رواتب معلقة في المجمع السيادي.',
        'fin.payroll': 'الرواتب',
        'fin.gen_payroll_btn': 'تنفيذ دورة الرواتب',
        'fin.active_liabilities': 'الالتزامات النشطة',
        'fin.pending_disbursement': 'صرف معلق',
        'fin.table.technician': 'الفني',
        'fin.table.month': 'الشهر',
        'fin.settle_payment': 'تسوية الدفعة',
        'fin.gen_payroll_title': 'تنفيذ الرواتب السيادية',
        'fin.gen_payroll_desc': 'سيؤدي تفعيل هذا إلى اعتماد الأموال لجميع عقد الفنيين النشطة.',
        'fin.gen_payroll_info': 'هل أنت متأكد من رغبتك في اعتماد المجمع الحالي؟',
        'fin.confirm_execute': 'تأكيد التنفيذ',
        'design.manager_title': 'مدير استوديو التصميم',
        'design.manager_subtitle': 'مراجعة وإدارة طلبات التصميم بالذكاء الاصطناعي',
        'design.empty': 'لا توجد طلبات تصميم بعد.',
        'design.table.owner': 'المالك',
        'design.table.property': 'العقار',
        'design.table.budget': 'الميزانية',
        'design.table.status': 'الحالة',
        'design.table.actions': 'الإجراءات',
        'fin.total_deductions': 'إجمالي الاستقطاعات',
        'analysis.efficiency': 'الكفاءة التشغيلية',
        'dash.proposed': 'مقترح',
        'dash.sanctioned': 'موافق عليه',
        'dash.declined': 'مرفوض',
        'fin.income': 'الدخل',
        'fin.burn': 'المصروفات',
        'fin.logs_title': 'سجلات الدفتر النظامي',
        'admin.contract_ref': 'مرجع العقد',
        'fin.log.date': 'التاريخ',
        'admin.amount': 'المبلغ',
        'fin.log.status': 'الحالة',
        'dash.kpi.outstanding_rent': 'الإيجارات المتأخرة',
        'dash.kpi.occupancy_rate': 'معدل الإشغال',
        'dash.missing_requirements': 'متطلبات حرجة مفقودة',
        'dash.escalation_title': 'التواصل المؤسسي المباشر',
        'dash.executive_desk': 'مكتب العمليات التنفيذية',
        'login.authorizing': 'جاري توثيق الدخول الآمن...',
        'login.inst_grade_badge': 'درجة مؤسسية',
        'login.uae_ops_badge': 'عمليات محفظة الإمارات',
        'login.change_role': 'تغيير الدور',
        'marketing.owners': 'الملاك',
        'marketing.tenants': 'المستأجرون',
        'marketing.technicians': 'الفنيون',
        'marketing.brokers': 'الوسطاء',
        'marketing.security': 'الأمن',
        'marketing.get_started': 'ابدأ الآن',
        'marketing.hero_chip': 'عمليات عقارية فورية في الإمارات',
        'marketing.hero_title': 'BIN-GROUPS — نظام تشغيل العمليات العقارية الفورية في الإمارات',
        'marketing.hero_desc': 'من الفلل إلى الأبراج والمراكز التجارية والمستشفيات والملاعب والفنادق والعقارات الحكومية والمجالس — تربط BIN-GROUPS بين الملاك والمستأجرين والفنيين والوسطاء والمدفوعات والمستندات والعقود والتصميم بالذكاء الاصطناعي في نظام تحكم موثق واحد.',
        'marketing.onboard_property': 'سجل عقارك',
        'marketing.inst_login': 'دخول المؤسسات',
        'marketing.req_contract': 'طلب عقد',
        'marketing.built_for_ops': 'مصمم للعمليات الحقيقية',
        'marketing.built_for_ops_desc': 'يتم التخطيط لتسجيل الملاك، والإرسال الطارئ، ووظائف الفنيين، وعمليات العقارات، وتصميم الذكاء الاصطناعي، وتقارير PDF، ومسح سندات الملكية، والعقود كنظام واحد متصل.',
        'marketing.service_protocols': 'بروتوكولات الخدمة المؤسسية',
        'marketing.coverage_title': 'تغطية المحافظ العقارية في جميع أنحاء الإمارات',
        'marketing.inquiry_title': 'استفسار مؤسسي',
        'marketing.inquiry_desc': 'أخبر BIN-GROUPS عما تديره. يبدأ تدقيق محفظتك من هنا.',
        'marketing.submit_audit': 'تقديم للتدقيق',
        'marketing.live_command': 'التحكم المباشر',
        'marketing.online': 'متصل',
        'marketing.owner_contract': 'عقد المالك',
        'marketing.active_protocol': 'البروتوكول النشط',
        'marketing.tenant_sos': 'إرسال استغاثة مستأجر',
        'marketing.tech_assigned': 'تم تعيين فني',
        'marketing.eta': '8 دقائق للوصول',
        'marketing.move_out_audit': 'تدقيق الخروج',
        'marketing.evidence_captured': 'تم التقاط الأدلة',
        'marketing.verified': 'موثق',
        'marketing.broker_comm': 'عمولة الوسيط',
        'marketing.finance_approved': 'تمت الموافقة المالية',
        'sector.owners.eyebrow': 'مركز قيادة الملاك',
        'sector.owners.title': 'تشغيل كل عقار بعقود ووثائق ومدفوعات وموافقات موثقة.',
        'sector.owners.subtitle': 'يحصل الملاك على التسجيل، وخطط الخدمة، والإضافات، وطلبات المستأجرين، والتقارير، واستوديو التصميم بالذكاء الاصطناعي، وصحة الممتلكات، وسجل الإيجار في نظام واحد في الوقت الفعلي.',
        'sector.owners.b1': 'لوحة تحكم مؤسسية مع تحليلات المحفظة في الوقت الفعلي',
        'sector.owners.b2': 'بروتوكول استخراج والتحقق من سند الملكية عبر OCR',
        'sector.owners.b3': 'اتفاقيات الخدمة الرئيسية والتوقيعات الإلكترونية المؤتمتة',
        'sector.owners.b4': 'سجل الإيجار المباشر، وتقارير الانتقال للداخل/الخارج، ودرجات صحة الممتلكات',
        'sector.tenants.eyebrow': 'رعاية المستأجرين',
        'sector.tenants.title': 'طلبات صيانة سريعة، تتبع الفنيين، ودعم واضح للانتقال للداخل والخارج.',
        'sector.tenants.subtitle': 'يمكن للمستأجرين تقديم طلبات الطوارئ، وتحميل الأدلة، ومتابعة حالة الفنيين، والتحقق من الإنجاز، والوصول إلى مستندات الوحدة.',
        'sector.tenants.b1': 'SOS السيادي: توجيه فوري لصيانة الطوارئ',
        'sector.tenants.b2': 'تتبع الفنيين في الوقت الفعلي وتنبيهات الوصول عبر GPS',
        'sector.tenants.b3': 'قوائم مراجعة الانتقال الرقمية وأدلة حالة الوحدة',
        'sector.tenants.b4': 'دردشة دعم مباشرة وإعلانات المجتمع',
        'sector.tech.eyebrow': 'فيلق الفنيين',
        'sector.tech.title': 'مركز قيادة ميداني للوظائف والمسارات والدوام والإضافي والأداء.',
        'sector.tech.subtitle': 'يرى الفنيون الوظائف المسندة، ومجمع المهام، وتلميحات المسار، وحالة دوام الموارد البشرية، وعبء العمل، ورابط التنبيهات، والهوية الرقمية.',
        'sector.tech.b1': 'التعيين التلقائي القائم على المنطقة وتحسين المسار الذكي',
        'sector.tech.b2': 'وضع عدم الاتصال للتحديثات المتسقة في المناطق الضعيفة التغطية',
        'sector.tech.b3': 'الهوية الرقمية وإدارة الاعتمادات الموثقة',
        'sector.tech.b4': 'تتبع الأداء، ورؤية الوقت الإضافي، وإكمال المهام المعتمد',
        'sector.brokers.eyebrow': 'شبكة الوسطاء',
        'sector.brokers.title': 'تتبع العملاء المحتملين، وإسناد العقود، وحالة العمولات، وجاهزية الدفع.',
        'sector.brokers.subtitle': 'يمكن للوسطاء جلب الملاك والعقارات والمستأجرين بينما يتحكم المالية/المسؤول في التحقق من الدفع والموافقة على الصرف.',
        'sector.brokers.b1': 'هوية الوسيط وتتبع إسناد العملاء المحتملين المؤتمت',
        'sector.brokers.b2': 'خط أنابيب العمولات في الوقت الفعلي وحالة الموافقة',
        'sector.brokers.b3': 'إدارة العقود وأرشيف إثبات الدفع',
        'sector.brokers.b4': 'خط اتصال مباشر مع المالية والمسؤول',
        'sector.security.eyebrow': 'الأمن السيادي',
        'sector.security.title': 'حماية الوثائق، سجلات التدقيق، الوصول حسب الدور، وبروتوكولات الأدلة.',
        'sector.security.subtitle': 'تتم حماية الوثائق الحساسة والمدفوعات والعقود وتدفقات الهوية بواسطة تشفير من الدرجة المؤسسية وضوابط الوصول.',
        'sector.security.b1': 'Firebase App Check وإنفاذ سلامة الجهاز',
        'sector.security.b2': 'سجلات تدقيق غير قابلة للتغيير لكل حدث تشغيلي',
        'sector.security.b3': 'خزنة مستندات مشفرة وعزل البيانات القائم على الدور',
        'sector.security.b4': 'التقاط الأدلة القائم على البروتوكول لجميع الأعمال الميدانية',
        'proof.owner_onboarding': 'تسجيل الملاك',
        'proof.owner_onboarding_desc': 'المستندات، خطة الخدمة، الإضافات، الدفع، الموافقة.',
        'proof.tenant_dispatch': 'إرسال المستأجرين',
        'proof.tenant_dispatch_desc': 'طلبات الطوارئ، حالة الفنيين، إثبات الإنجاز.',
        'proof.tech_jobs': 'وظائف الفنيين',
        'proof.tech_jobs_desc': 'بطاقات المهام، الملاحة، الدوام، عبء العمل.',
        'proof.owner_command': 'مركز قيادة الملاك',
        'proof.owner_command_desc': 'تقارير المحفظة، الموافقات، سجل الصيانة، المدفوعات، المستندات، وأداء الممتلكات.',
        'proof.ai_studio': 'استوديو التصميم بالذكاء الاصطناعي',
        'proof.ai_studio_desc': 'مفاهيم الغرف، النطاق، المواد ومسار التسعيرة.',
        'proof.pdf_reports': 'تقارير PDF',
        'proof.pdf_reports_desc': 'العقود، الانتقال للداخل/الخارج، الصيانة، تقارير الملاك.',
        'dash.health_index': 'مؤشر صحة الأصل',
        'dash.intel.projected_yield': 'العائد المتوقع',
        'prop.villas': 'فلل',
        'prop.apartments': 'شقق',
        'prop.res_buildings': 'مباني سكنية',
        'prop.com_buildings': 'مباني تجارية',
        'prop.offices': 'مكاتب',
        'prop.hotels': 'فنادق',
        'prop.malls': 'مراكز تسوق',
        'prop.hospitals': 'مستشفيات',
        'prop.clinics': 'عيادات',
        'prop.schools': 'مدارس',
        'prop.warehouses': 'مستودعات',
        'prop.labour_camps': 'سكن عمال',
        'prop.gov_properties': 'عقارات حكومية',
        'prop.gov_majlis': 'مجالس حكومية',
        'prop.pri_majlis': 'مجالس خاصة',
        'prop.mixed_towers': 'أبراج متعددة الاستخدام',
        'prop.skyscrapers': 'ناطحات سحاب',
        'prop.stadiums': 'ملاعب',
        'prop.sports_complex': 'مجمعات رياضية',
        'prop.event_venues': 'أماكن فعاليات',
        'prop.resorts': 'منتجعات',
        'prop.retail_centers': 'مراكز تجزئة',
        'prop.industrial': 'عقارات صناعية',
        'prop.staff_acc': 'سكن موظفين',
        'prop.farms': 'مزارع / عزبات',
        'form.name': 'الاسم',
        'form.contact': 'الهاتف / البريد الإلكتروني',
        'form.prop_type': 'نوع العقار',
        'form.emirate': 'الإمارة',
        'form.details': 'تفاصيل المحفظة',
        'form.ceo_note': 'يتوفر تصعيد للمدير التنفيذي بالإضافة إلى تذاكر الدعم العادية والدردشة.',
        'plan.maintenance': 'صيانة فقط (ألفا)',
        'plan.management': 'إدارة عقارات (بيتا)',
        'plan.hybrid': 'رعاية شاملة هجين (أوميغا)',
        'plan.enterprise': 'بروتوكول مخصص للمؤسسات',
        'admin.terminal.title': 'محطة BIN-ADMINISTRY™',
        'admin.terminal.subtitle': 'نواة العمليات العقارية من الدرجة المؤسسية',
        'admin.node.smart_building': 'مراقب المباني الذكية',
        'admin.node.duty_monitor': 'مراقب الدوام',
        'admin.node.security_vault': 'خزنة الأمن',
        'admin.node.orphan_war_room': 'غرفة عمليات الأصول اليتيمة',
        'admin.node.financial_command': 'القيادة المالية',
        'admin.node.audit_shield': 'درع التدقيق',
        'admin.node.pricing_matrix': 'مصفوفة التسعير',
        'admin.node.system_audit': 'تدقيق النظام',
        'dash.hello': 'مرحباً',
        'onboarding.retry_scan': 'إعادة المحاولة'
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    // Fixed SSR issue with typeof window check
    const [lang, setLang] = useState<Language>(() => {
        if (typeof window !== 'undefined') {
            const saved = localStorage.getItem('app_lang');
            return (saved as Language) || 'en';
        }
        return 'en';
    });

    useEffect(() => {
        localStorage.setItem('app_lang', lang);
        const dir = lang === 'ar' ? 'rtl' : 'ltr';
        document.dir = dir;
        document.documentElement.dir = dir;
        document.body.dir = dir;
        document.documentElement.lang = lang;
        console.info("[BIN i18n]", {
            lang,
            dir: document.documentElement.dir,
            stored: localStorage.getItem("app_lang")
        });
    }, [lang]);

    const t = (key: string, variables?: Record<string, any>) => {
        let text = translations[lang]?.[key] || translations['en']?.[key];
        
        if (!text) {
            // Humanize the key for fallback
            const parts = key.split('.');
            const lastPart = parts[parts.length - 1];
            text = lastPart.charAt(0).toUpperCase() + lastPart.slice(1).replace(/_/g, ' ');
        }

        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                text = text.replace(`{${k}}`, String(v));
            });
        }
        return text;
    };

    const tx = (key: string, fallback: string, variables?: Record<string, any>) => {
        const text = translations[lang]?.[key] || translations['en']?.[key];
        if (!text) return fallback;
        
        let result = text;
        if (variables) {
            Object.entries(variables).forEach(([k, v]) => {
                result = result.replace(`{${k}}`, String(v));
            });
        }
        return result;
    };

    const isRTL = lang === 'ar';
    const toggleLanguage = () => setLang(lang === 'en' ? 'ar' : 'en');

    return (
        <LanguageContext.Provider value={{ lang, language: lang, setLang, toggleLanguage, t, tx, isRTL }}>
            <Box 
                id="bin-app-root"
                dir={isRTL ? 'rtl' : 'ltr'}
                sx={{ 
                    minHeight: '100vh',
                    fontFamily: 'inherit',
                    bgcolor: 'background.default',
                    color: 'text.primary',
                    direction: isRTL ? 'rtl' : 'ltr'
                }}
            >
                {children}
            </Box>
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
};
