import React from 'react';
import { Box, Card, CardContent, Stack, Typography } from '@mui/material';

export default function TenantRenewalsPage() {
  return (
    <Box>
      <Stack spacing={3}>
        <Box>
          <Typography variant="overline" sx={{ color: '#B8932F', fontWeight: 950, letterSpacing: 2 }}>
            LEASE RENEWAL CENTER
          </Typography>
          <Typography variant="h4" sx={{ color: '#fff', fontWeight: 950 }}>
            Your renewal timeline
          </Typography>
          <Typography sx={{ color: 'rgba(255,255,255,0.62)', fontWeight: 700, mt: 1 }}>
            Renewal status, notice PDFs, owner response, and next steps will appear here when linked to your active unit.
          </Typography>
        </Box>
        <Card sx={{ bgcolor: '#111827', color: '#fff', border: '1px solid rgba(184,147,47,0.34)', borderRadius: 4 }}>
          <CardContent>
            <Typography sx={{ fontWeight: 800 }}>
              No active renewal record is linked yet. This page is ready for live renewal watch records generated by Firebase Functions.
            </Typography>
          </CardContent>
        </Card>
      </Stack>
    </Box>
  );
}
