import React, { useEffect, useMemo, useState } from 'react';
import { Box, Button, Card, CardContent, Chip, CircularProgress, Stack, Typography } from '@mui/material';
import { useNavigate } from 'react-router-dom';
import { db, collection, getDocs, limit, orderBy, query, where, Timestamp } from '../../lib/firebase';
import { useRole } from '../../context/RoleContext';

type RenewalWatchRecord = {
  id: string;
  propertyName?: string;
  unitNumber?: string;
  expiryAt?: Timestamp;
  daysRemaining?: number;
  renewalStatus?: string;
  status?: string;
  pdfUrl?: string | null;
  sourceCollection?: string;
  sourceId?: string;
};

async function loadRenewalsBy(field: string, value?: string) {
  if (!value) return [] as RenewalWatchRecord[];
  const snap = await getDocs(
    query(
      collection(db, 'contract_renewal_watch'),
      where(field, '==', value),
      orderBy('daysRemaining', 'asc'),
      limit(20)
    )
  );
  return snap.docs.map((docSnap) => ({ id: docSnap.id, ...(docSnap.data() as Omit<RenewalWatchRecord, 'id'>) }));
}

export default function TenantRenewalsPage() {
  const navigate = useNavigate();
  const { user } = useRole();
  const [loading, setLoading] = useState(true);
  const [renewals, setRenewals] = useState<RenewalWatchRecord[]>([]);

  useEffect(() => {
    let cancelled = false;
    const run = async () => {
      if (!user?.uid) {
        setLoading(false);
        return;
      }
      try {
        const map = new Map<string, RenewalWatchRecord>();
        const addAll = (items: RenewalWatchRecord[]) => items.forEach((item) => map.set(item.id, item));
        addAll(await loadRenewalsBy('tenantId', user.uid));
        if (user.email) addAll(await loadRenewalsBy('tenantEmail', String(user.email).trim().toLowerCase()));
        const merged = Array.from(map.values()).sort((a, b) => (a.daysRemaining ?? 9999) - (b.daysRemaining ?? 9999));
        if (!cancelled) setRenewals(merged);
      } catch (error) {
        console.error('[TenantRenewals] Failed to load renewal watch records:', error);
        if (!cancelled) setRenewals([]);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    run();
    return () => {
      cancelled = true;
    };
  }, [user?.uid, user?.email]);

  const headline = useMemo(() => {
    if (!renewals.length) return 'No active renewal record is linked yet.';
    const nearest = renewals[0];
    const days = nearest.daysRemaining;
    if (typeof days !== 'number') return 'Renewal records are available for your unit.';
    if (days < 0) return `At least one renewal is overdue by ${Math.abs(days)} day(s).`;
    if (days === 0) return 'A lease renewal reaches expiry today.';
    return `Nearest renewal milestone in ${days} day(s).`;
  }, [renewals]);

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 8 }}>
        <CircularProgress sx={{ color: '#B8932F' }} />
      </Box>
    );
  }

  return (
    <Box>
      <Stack spacing={3}>
        <Box>
          <Typography variant="overline" sx={{ color: '#B8932F', fontWeight: 950, letterSpacing: 2 }}>
            LEASE RENEWAL CENTER
          </Typography>
          <Typography variant="h4" sx={{ color: '#fff', fontWeight: 950 }}>
            Your renewal timeline
          </Typography>
          <Typography sx={{ color: 'rgba(255,255,255,0.62)', fontWeight: 700, mt: 1 }}>
            Renewal status, notice PDFs, owner response, and next steps will appear here when linked to your active unit.
          </Typography>
        </Box>
        <Card sx={{ bgcolor: '#111827', color: '#fff', border: '1px solid rgba(184,147,47,0.34)', borderRadius: 4 }}>
          <CardContent>
            <Typography sx={{ fontWeight: 800 }}>{headline}</Typography>
            <Typography sx={{ color: 'rgba(255,255,255,0.72)', mt: 1 }}>
              Renewal records are generated by the contract renewal watcher and include notice timing, status, and linked PDF evidence.
            </Typography>
          </CardContent>
        </Card>

        {renewals.map((record) => {
          const expiry = record.expiryAt?.toDate?.();
          const statusLabel = String(record.renewalStatus || record.status || 'RENEWAL_WATCH').toUpperCase();
          const urgency =
            typeof record.daysRemaining === 'number'
              ? record.daysRemaining < 0
                ? 'error'
                : record.daysRemaining <= 14
                  ? 'warning'
                  : 'success'
              : 'default';
          return (
            <Card key={record.id} sx={{ bgcolor: '#0B1220', color: '#fff', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 4 }}>
              <CardContent>
                <Stack spacing={1.5}>
                  <Stack direction="row" spacing={1} alignItems="center" useFlexGap flexWrap="wrap">
                    <Typography sx={{ fontWeight: 900 }}>
                      {record.propertyName || 'Property'} {record.unitNumber ? `· Unit ${record.unitNumber}` : ''}
                    </Typography>
                    <Chip size="small" color={urgency as any} label={statusLabel} />
                    {typeof record.daysRemaining === 'number' && (
                      <Chip
                        size="small"
                        variant="outlined"
                        label={record.daysRemaining < 0 ? `${Math.abs(record.daysRemaining)} day(s) overdue` : `${record.daysRemaining} day(s) remaining`}
                        sx={{ color: '#fff', borderColor: 'rgba(255,255,255,0.35)' }}
                      />
                    )}
                  </Stack>
                  <Typography sx={{ color: 'rgba(255,255,255,0.7)' }}>
                    Expiry: {expiry ? expiry.toLocaleDateString('en-GB') : 'Not provided'}
                  </Typography>
                  <Stack direction="row" spacing={1.5} useFlexGap flexWrap="wrap">
                    <Button variant="outlined" sx={{ borderColor: '#B8932F', color: '#B8932F' }} onClick={() => navigate('/tenant/documents')}>
                      Open Lease Documents
                    </Button>
                    {record.pdfUrl ? (
                      <Button
                        variant="contained"
                        sx={{ bgcolor: '#B8932F', color: '#111' }}
                        onClick={() => window.open(record.pdfUrl || '', '_blank', 'noopener,noreferrer')}
                      >
                        Open Renewal PDF
                      </Button>
                    ) : null}
                  </Stack>
                </Stack>
              </CardContent>
            </Card>
          );
        })}
      </Stack>
    </Box>
  );
}
